### ISSUE TITLE
`eth_getLogs` does not return results if multiple topic ids are provided

### ISSUE THREAD

**Issue by iron4548** [hashgraph/hedera-json-rpc-relay#1015]
### Description

For 'eth_getLogs' call when passing multiple 'topics' parameters it would return no result for a given block range. However, if I only pass exactly one topic in the array then I will get results.

Example using https://mainnet.hashio.io/api

The following will result in one log event returned. 

```
{
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [
        {
            "fromBlock": "0x2bbd8e6",
            "toBlock": "0x2bbd8e9",
            "topics": [
                "0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1"
            ]
        }
    ],
    "id": 1
}
```

The following would result in a bunch of logs (good) using a different topic id

```
{
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [
        {
            "fromBlock": "0x2bbd8e6",
            "toBlock": "0x2bbd8e9",
            "topics": [
                "0x831ac82b07fb396dafef0077cea6e002235d88e63f35cbd5df2c065107f1e74a"
            ]
        }
    ],
    "id": 1
}
```

BUT the following would result in zero logs returned if both topic ids were provided. I expect to get combined logs from both topic ids. That's the bug.

```
{
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [
        {
            "fromBlock": "0x2bbd8e6",
            "toBlock": "0x2bbd8e9",
            "topics": [
                "0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1",
                "0x831ac82b07fb396dafef0077cea6e002235d88e63f35cbd5df2c065107f1e74a"
            ]
        }
    ],
    "id": 1
}
```

### Steps to reproduce

1. Go to https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/hashgraph/hedera-json-rpc-relay/main/docs/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false

2. Send the following parameters to: https://mainnet.hashio.io/api

```
{
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [
        {
            "fromBlock": "0x2bbd8e6",
            "toBlock": "0x2bbd8e9",
            "topics": [
                "0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1",
                "0x831ac82b07fb396dafef0077cea6e002235d88e63f35cbd5df2c065107f1e74a"
            ]
        }
    ],
    "id": 1
}
```

3. Expect multiple log events but got none

### Hedera network

mainnet

### Version

0.21.0-SNAPSHOT

### Operating system

Windows

**Comment by iron4548** [comment]
![image](https://user-images.githubusercontent.com/22169356/227710409-765197d5-af21-4305-a3ca-3fedafd7c74b.png)

**Comment by natanasow** [comment]
@iron4548 Hello, you are passing `topic0` as `topic1` param. The proper way to get your information is by passing an array of `topics0` (as I see in your example). It's described pretty well in the docs `OneOf(string or ArrayOf)` :point_down:
```
...
"topics": [
    topic0 or array of topics0,
    topic1 or array of topics1,
    ...
]
...
```
#### Your example is querying for topic0 and topic1
```
{
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [
        {
            "fromBlock": "0x2bbd8e6",
            "toBlock": "0x2bbd8e9",
            "topics": [
                "0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1", // topic0
                "0x831ac82b07fb396dafef0077cea6e002235d88e63f35cbd5df2c065107f1e74a" // topic1
            ]
        }
    ],
    "id": 1
}
```
#### What you want to do is query for array of topics0
```
{
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [
        {
            "fromBlock": "0x2bbd8e6",
            "toBlock": "0x2bbd8e9",
            "topics": [
                // array of topics 0
                ["0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1", "0x831ac82b07fb396dafef0077cea6e002235d88e63f35cbd5df2c065107f1e74a"] 
            ]
        }
    ],
    "id": 1
}
```

Hope that helps you :pray:

**Comment by iron4548** [comment]
Ohh I see!!

Thank you, that did the job. Sorry for the false report! :)
