### ISSUE TITLE
Return relay config in web3_clientVersion

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#1024]
### Problem

As a developer, I would like to know what the config is for the relay provider I am using.

The rationale for this is somewhat related to #850 however is more expansive.

### Solution

The web3_clientVersion returns a json response body that looks something like the following:

```json
{
    "jsonrpc": "2.0",
    "result": "relay/0.20.0",
    "id": 0
}
```

To accommodate for the ask in this issue modify the response body in either of the following ways:
1. add an additional field say `config` to the response object which is a json object corresponding to all non-secure/secret fields(every config variable except for `OPERATOR_KEY_MAIN`) OR
2. `result` should be `JSON.stringify({config, result})` where `result` is the current value for `result` and `config`is an object containing all non-secure config variables.

**Comment by Nana-EC** [comment]
Thanks @mshakeg 
Interesting suggestion. I see the potential value as an operator.

Is the request since you need to pull this information programmatically to understand unique configurations from a deployment e.g. previewnet may have more relaxes thresholds than testnet and mainnet.
Can you share some more examples of which configs values you'd want exposed?

I wonder also if instead of exposing this on an existing well defined endpoint that the better way would be to consider a new configuration related endpoint that relays can optionally expose

**Comment by mshakeg** [comment]
@Nana-EC thanks for the reply.

> I wonder also if instead of exposing this on an existing well defined endpoint that the better way would be to consider a new configuration related endpoint that relays can optionally expose

That works too, if I'm not mistaken there are already endpoint/s that have been implemented beyond the json rpc spec such as a health endpoint, though I couldn't find those endpoint/s documented anywhere.

---

> Is the request since you need to pull this information programmatically to understand unique configurations from a deployment e.g. previewnet may have more relaxes thresholds than testnet and mainnet.

Correct that's more or less the reason, but more generally insights into the config of any relay operated by hashio or other 3rd parties. Obviously, it doesn't guarantee that that is in fact the config, but useful in the case of an honest relay provider.

---

> Can you share some more examples of which configs values you'd want exposed?

**Ideally, all config variables** that do not need to be private should be exposed and as far as I can tell the only one that is required to be private is `OPERATOR_KEY_MAIN`. Nonetheless, the variables I think would be most useful would be the following:

### Server

* HBAR_RATE_LIMIT_DURATION
* HBAR_RATE_LIMIT_TINYBAR
* INPUT_SIZE_LIMIT
* RATE_LIMIT_DISABLED

### Relay

* DEFAULT_RATE_LIMIT
* ETH_CALL_CACHE_TTL
* ETH_CALL_DEFAULT_TO_CONSENSUS_NODE

**Comment by Nana-EC** [comment]
Thanks for the response and context.
This gives us a better understanding.
We'll explore this further and update this ticket in the next sprint

**Comment by mshakeg** [comment]
Another thought comes to mind. In addition to returning the config of the relay it maybe useful to also return the config of all of the relay's upstream dependencies for example the config of the mirror node, as relay providers may set up a mirror node that serves a relay behind a VPN and so is not directly accessible to relay clients but is to the relay. However this will require that the mirror node also be expose an endpoint for retrieving the config similarly to how this issue proposes returning the config for the relay.

**Comment by Nana-EC** [comment]
Hey @mshakeg 
Implementing this would break the conformance with the Ethereum JSON RPC API.
The result for `web3_clientVersion` should be the version so this wouldn't be the right endpoint to extract config properties.
I don't think any endpoint in the API describes a good location for this.
Also it's not clear that relay operators would want this to be exposed without consideration

**Comment by Nana-EC** [comment]
Closing as implementing would break conformance with API response expectations
