### ISSUE TITLE
Upgrading proxy contracts is failing intermittent

### ISSUE THREAD

**Issue by attest08** [hashgraph/hedera-json-rpc-relay#1036]
### Description

**Preconditions**
Use the local-node version from the following PR:  https://github.com/hashgraph/hedera-local-node/pull/312 
from **hedera-local-node** branch **309-improve-stability-of-local-node**

**The following tests are sporadically failing:**
```
Proxy Upgrade Contracts Test Suite
    DEX Upgradable Contract Test Suite
      - should deposit, buy and sell tokens from ExchangeV1
      ✔ should not be able to get version
      1) should upgrade contract to V2
      - should deposit, buy and withdraw tokens from ExchangeV2
    Counter Upgradable Contract Test Suite
      ✔ should be able to increase and decrease counter on V1 (1940ms)
      ✔ should not be able to change name
      2) should be able to upgrade contract to V2
      3) should be able to increase and decrease counter on V2

 Error: No contract at address 0x83f6f0087879c92240D8872415d41287b9889868 (Removed from manifest)

```

### Steps to reproduce

1. Start hedera-local-node
2. Execute the proxyUpgradeContracts.js tests from hedera-smart-contracts
3. Restart hedera-local-node
4. Execute the tests again
5. Check the results and observe the behaviour

_Note: After the initial start of the node the tests are failing. If they are retried after a couple of of minutes they start to run successfully!_

### Additional context

Full logs from **json-rpc-relay** -> 
[relay-logs.txt](https://github.com/hashgraph/hedera-json-rpc-relay/files/11170449/relay-logs.txt)

### Hedera network

localnet 

### Version

main/latest

### Operating system

None

**Comment by georgi-l95** [comment]
This is not a bug, what is happening is that hardhat-upgrades is saving a json file with the details of the contract (proxy address, transaction hashes, implementation address and more). If you don't have this file on the disk it's fine, if you do have them hardhat is using them to fetch the contract. However when we restart the local-node, those saved transaction hashes no longer exist, therefore this issue occurs. One option is to delete this file after local-node restart. This will not be needed, if you deploy on public network.
