### ISSUE TITLE
There's no valid scenario right now to query the consensus node with the blockNum.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#1038]
### Description

There's no valid scenario right now to query the consensus node with the blockNum.  The Consensus node only supports current account info.  There's no concept of past account info.  If there's a blockNum we should hit the Mirror Node with the timestamp on the account query. If that fails the transaction should fail.

### Steps to reproduce

1. Running a value transfer.
2. Batch3 test "Returns revert reason in receipt for payable methods" consistently triggers an error in previewnet when the code to be replaced, the consensus query code, is run.

### Hedera network

previewnet

### Version

v0.21.0

### Operating system

None

**Comment by Nana-EC** [comment]
Should be address by #1103
