### ISSUE TITLE
Expand subgraph example with HAPI events

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#1040]
### Problem

Until recently we didn't have support for events from HAPI transactions such as mint, wipe, burn etc. Now we do have and we need to update our subgraph example with this.

### Solution

Enhance subgraph tools example with the support for events from HAPI transactions.

**Comment by Nana-EC** [comment]
Now depending on https://github.com/hashgraph/hedera-json-rpc-relay/pull/1518
