### ISSUE TITLE
Tests need to be updated and stabilized

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#1048]
### Description

https://github.com/hashgraph/hedera-services/issues/6029 may be contributing to failing tests.  Failing tests cause releases to be time consuming.  We need to stabilize the tests or improve the release process.

### Steps to reproduce

1. Run the acceptance tests against previewnet.
2. Run the acceptance tests against testnet.
3. Observe the failing tests.  Do they fail consistently.  Are they related to 0.35.2?

### Hedera network

previewnet

### Version

v0.21

### Operating system

None

**Comment by ebadiere** [comment]
Also, perhaps more of the release process can be off loaded into CI?  Easy candidates for this could be the K6 performance tests, and then each acceptance test.  Leveraging GH Actions could free up the developer cutting the release to continue working while simply pushing buttons and running the builds in a stable environment in the background.

**Comment by Nana-EC** [comment]
@ebadiere can this be closed?
