### ISSUE TITLE
Add cache support to eth_blockNumber

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1057]
### Problem

Currently the `eth_blockNumber` queries the Mirror Node for the latest block.
Under high load a mirror node may limit RPS

### Solution

To reduce the number of calls needed and therefore the load on a mirror node a cache may be added to `eth_blockNumber` endpoint.

Mirror Node processes a block every 2 secs, so a cache of 500 or 1000ms may be a fair balance between optimization and data freshness.
This should be added as a configureable property

**Comment by david-bakin-sl** [comment]
(I wonder if mirror node would like to support a callback for this? to get notifications of new blocks?)

**Comment by AlfredoG87** [comment]
> (I wonder if mirror node would like to support a callback for this? to get notifications of new blocks?)

Yeah, I thought about that too, like a webSocket style `push` notification instead of `pull` 
it would be a nice to have from the mirror node.
