### ISSUE TITLE
Improve retry logic for MirrorClient getBlocks

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1060]
### Problem

Currently the getBlocks method in MirrorNodeCLietn support retry for 400 and 404 responses.
However, for an operating network these are not valid responses.
The result is under high load the Mirror Node may return one of these and the relay keeps retrying.
Should confirm this, as the right path should be 504's on rate limiting.

Eventually the relay fails with a timeout. In this case the relay shouldn't retry as the rate limit is likely longer than the 10 seconds the relay retries for. In this case we should just fail fast and reduce the number of iterations

### Solution

After confirming the correct responses codes from the mirror node during throttling we should
- update retry logic to not retry when latest block method is called e.g.`api/v1/blocks?limit=1`

**Comment by ebadiere** [comment]
Looking in the logs explorer, there has not been a retry with a /api/v1/blocks?limit=1 call in the last twelve hours.
