### ISSUE TITLE
Intermittent RPC errors with message: "Unknown error invoking RPC"

### ISSUE THREAD

**Issue by bguiz** [hashgraph/hedera-json-rpc-relay#1104]
### Description

- sent deployment transactions
  - `[Request ID: ed2b0630-b17d-4e64-82e8-f7aea3196f82] Unknown error invoking RPC`
  - `[Request ID: 960839a7-76c3-4781-83d0-7345ce2e04d7] Unknown error invoking RPC`
  - `[Request ID: b916dea1-c3b4-4888-af04-a75378510a54] Unknown error invoking RPC`
- sent RPC requests to read data from a deployed SC
  - `[Request ID: af5b1adf-8e0a-4792-b847-ca6328d21511] Unknown error invoking RPC`

### Steps to reproduce

- send multiple deployment transactions of the exact same smart contract using ethersjs
- send multiple read transactions (exact same ones) using ethersjs
- observe that some fail while some pass, intermittently

### Hedera network

testnet

### Version

ethersjs v5

### Operating system

macOS

**Comment by georgi-l95** [comment]
Hey @bguiz are you trying to perform batch transactions? Can you provide some code snippets ?

**Comment by bguiz** [comment]
> Hey @bguiz are you trying to perform batch transactions? Can you provide some code snippets ?

nope @georg-getz - I'm actually doing individual transactions. EVM transactions with EVM accounts (not the Hedera-native type)

**Comment by bguiz** [comment]
Closing this, as unable to reproduce in after last week's network upgrade
