### ISSUE TITLE
eth_getCode cache

### ISSUE THREAD

**Issue by natanasow** [hashgraph/hedera-json-rpc-relay#1107]
### Description

We are caching the contract's bytecode which is acceptable in most cases because the bytecode is immutable and can not be changed. The problem appears when the user calls `selfdestruct` the the bytecode must be deleted, and if the end-user calls `eth_getCode` again, the cached response will be returned, which is not accurate and not corresponding to the state.

### Steps to reproduce

- Deploy a contract with `selfdestruct` via hardhat example
- Get the contract bytecode via `ethers.provider.getCode(<contractAddress>)` which will call `eth_getCode`
- Call the selfdestruct function
- Get the contract bytecode again - the returned value should be `0x` because the contract has been deleted

PS: to make sure that `selfdestruct` is called, you can transfer a hbars to the contract beforehand and check the balances before/after the destruction

### Solution
- [ ] Remove the cache from `eth_getCode`
- [ ] Add test

### Hedera network

other

### Version

latest

### Operating system

Linux

**Comment by Nana-EC** [comment]
Hmm removing the cache doesn't seem preferable.
Are there other options, can we search the byte code for the SELF DESTRUCT opcode. 
May we cache less or don't cache those cases.
Could we combine this logic with an `eth_call` request to tell us if SELF DESTRUCT has been called?

**Comment by natanasow** [comment]
We can disassemble the bytecode to opcodes and find the `selfdestruct`, but this will work only for contracts without `delegatecall` or `callcode` opcodes in it.

Let's take a look over this case :point_down:
```
//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;

contract A {
	function destroy(address B) public {
		B.delegatecall(abi.encodeWithSignature("deleteContract()"));
	}
}

contract B {
	function deleteContract() public {
		selfdestruct(payable(msg.sender));
	}
}
```
We're deploying contracts **A** and **B**, the **A** bytecode doesn't contain `selfdestruct`. We call `A.destroy()` which copies the `B.deleteContract()` opcodes into **A** and contract **A** will be deleted. In this case, we can not cache contract **A** even if it's not containing `selfdestruct` opcode.

And another example :point_down:
```
contract A {
    function callB(address _B, address _C, address _D) public {
        _B.call(abi.encodeWithSignature("callC(address,address)", _C, _D));
    }
}

contract B {
    function callC(address _C, address _D) public {
        _C.delegatecall(abi.encodeWithSignature("callD(address)", _D));
    }
}

contract C {
    function callD(address _D) public {
        _D.call(abi.encodeWithSignature("destroy()"));
    }
}

contract D {
    function destroy() public {
        selfdestruct(payable(msg.sender));
    }
}
```
We can:
- cache **A** and **C** because they are not containing `selfdestruct || delegatecall || callcode` opcodes
- not cache **B** because even if it's not containing `selfdestruct` we cannot be sure that passed _C will not contain `selfdestruct` or another call
- not cache **D** because can be deleted

So I propose to check the contact's bytecode for opcodes and cache the contract only if it doesn't contain one of `selfdestruct || delegatecall || callcode` opcodes. If the bytecode contains one of the opcodes, we have to query the mirror node for `deleted` status every time.

**Comment by Nana-EC** [comment]
Thanks for the considerations @natanasow 

I guess additionally we should also cache if a certain bytecode contains one of those codes that needs an extra mirror node call, that way the relay doesn't unnecessarily do the same logic multiple times for the same contract.
