### ISSUE TITLE
Enable cAdvisor metrics in Helm chart

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1119]
### Problem

The current kubernetes architecture does not utilize [cAdvisor metrics collection](https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/)

### Solution

Enable cAdvisor metrics in Helm chart

**Comment by Nana-EC** [comment]
@rustyShacklefurd we can close this as done right?

**Comment by AlfredoG87** [comment]
Will close it, otherwise we can re-open.
