### ISSUE TITLE
Remove duplicate tests and refactor constants

### ISSUE THREAD

**Issue by attest08** [hashgraph/hedera-json-rpc-relay#1129]
### Problem

- The events and the gas limit values are hardcoded in the tests. Extract them in a separate constants file.

- Check the htsPrecompile set, compare the existing tests with the ones from the smart-contracts repository and remove the duplicate ones.

### Solution

Refactor constants and remove duplicate tests.

**Comment by Nana-EC** [comment]
I think this was covered in some clean ups
