### ISSUE TITLE
Add an OpenRPC Document

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#114]
### Problem

We currently don't have complete documentation for the endpoints provided

### Solution

We should utilize the [OpenRPC](https://open-rpc.org/) standard and the [OpenRPC Playground](https://playground.open-rpc.org)

- Create an OpenRPC compliant spec in the repo
- Note the spec in the main README with a link to the playground to view it e.g. https://playground.open-rpc.org/?schemaUrl={repoSchemaUrl}
- Add a test case to validate spec and ensure compliance - see [Open RPC Schema Test example](https://github.com/open-rpc/examples/blob/master/src/index.test.ts)

See [Open RPC examples](https://github.com/open-rpc/examples/tree/master/service-descriptions) and [OpenRPC in the wild](https://open-rpc.org/use) for notable examples

**Comment by ar-conmit** [comment]
The ticket has some progress in this [branch](https://github.com/hashgraph/hedera-json-rpc-relay/tree/114-openrpc-doc). The following methods are already documented:
`eth_getBlockByHash`
`eth_getBlockByNumber`
`eth_getBlockTransactionCountByHash`
`eth_getBlockTransactionCountByNumber`
`eth_getUncleCountByBlockHash`
`eth_getUncleCountByBlockNumber`
`eth_protocolVersion`
`eth_chainId`
`eth_syncing`
`eth_coinbase`
`eth_accounts`
`eth_blockNumber`
