### ISSUE TITLE
Allow array of consensus nodes with round robin

### ISSUE THREAD

**Issue by abhishek-bcw** [hashgraph/hedera-json-rpc-relay#1169]
### Problem

When we configure the relay the `.env` has an object for specifying the Node id under `HEDERA_NETWORK` This typical;ly ends up pointing to Node 0 which can overwhelm a single node. 

It is possible to switch node ID but that will remain hardcoded in the container environment and will require a deployment to switch the container to another node id since we can only select one. Which may not be responsive at times or simply overloaded.

It seems there is possibility of specifying a set of nodes as per the helm chart.
`{"$IPv4_ADDR_1:$PORT_1":"$ACCOUNT_ID_1","$IPv4_ADDR_2:$PORT_2":"$ACCOUNT_ID_2"}` in the helm chart. 
Does it use alternate account ids in round robin or failover?

https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/.env.example 

### Solution

@daniel-bcw for comments.
for e.g. 
- `HEDERA_NETWORK`   or `HEDERA_NETWORKS` which uses a set of nodes.
- The connection can retry in round robin from the list of hosts.

**Comment by Nana-EC** [comment]
Hi @abhishek-bcw 

Can you clarify if you're setting `HEDERA_NETWORK` to an environment e.g. `testnet` or `mainnet` or if you're actually specifying an object with a single or multiple node endpoint:acountId pairs?
You are free to do either. 
In both cases the SDK will randomly select a node in the applicable list of nodes for every transaction so you shouldn't get 1 node being overloaded unless you're not using the static env names and have set a small list of specific nodes.

You can get more details of the SDK operations https://docs.hedera.com/hedera/sdks-and-apis/sdks/client and https://github.com/hashgraph/hedera-sdk-js

**Comment by abhishek-bcw** [comment]
Hi Nana,
Thank you for your reply. We are testing this in the dev environment. I
will update my devops on adding multiple nodes in their test.
The SDK client source you shared is helpful, I had missed that.
