### ISSUE TITLE
Implement Precompiled Mock Contracts for Faster Local Development Experience

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#1172]
### Problem

Smart contract developers working with Hedera's precompiled contracts (HTS, Exchange Rate, and Prng) currently face challenges when trying to test their smart contracts in a local development environment using popular frameworks like Hardhat and Foundry. This is because these precompiled contracts are only available on Hedera networks, which slows down the development and testing process as even the hedera local node is significantly slower than the foundry and hardhat local nodes.

### Solution

Create mock contracts that mimic the behaviour of Hedera's precompiled contracts and publish them as either:

1. a separate package for easy integration into developers' projects or
2. under a new folder(say `hedera-precompiled-mocks`) in [hashgraph/hedera-smart-contracts/contracts](https://github.com/hashgraph/hedera-smart-contracts/tree/main/contracts)

This would enable a faster and more efficient development experience by allowing developers to test their smart contracts locally without the need to interact with a relatively slow hedera local node/network.

Develop Solidity smart contracts that implement the respective interfaces (`IHederaTokenService`, `IExchangeRate`, and `IPrng`) and mimic the behaviour of the precompiled/system contracts.

Provide documentation and examples for using these mock contracts in popular development frameworks such as Hardhat and Foundry. This could include guidance on deploying the mock contracts and updating the smart contract under test to interact with the mock contract addresses based on the network (main network vs. local development network); this is really only needed for frameworks that do NOT allow developers to specify a deployment address such as **Hardhat**, but not needed for frameworks that do such as **Foundry**.

## Hardhat example

Modify the `ExchangeRatePrecompile`, `PrngSystemContract` and `HederaTokenService` contracts to use the mock contract address when running on a local development network, and the actual precompile contract address when running on the Hedera networks (local, previewnet, testnet, and mainnet). For example the `HederaTokenService` contract can be modified as follows:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "./IHederaTokenService.sol";

abstract contract HederaTokenService is IHederaTokenService {
    address constant actualPrecompileAddress = address(0x167);
    address constant mockAddress = address(0x1234567); // whatever the deployment address of the mock contract is on the hardhat local node
    // to avoid having to frequently change this address the mock contract can be deployed via a deterministic-deployment-proxy such as https://github.com/Arachnid/deterministic-deployment-proxy
    // however the 10mb limit may have to be lifted in a local environment as large test suites may cause the mock contract's storage to exceed this

    // Replace precompileAddress constant with a view function
    function precompileAddress() internal view returns (address) {
        if (block.chainid == 295 || block.chainid == 296 || block.chainid == 297 || block.chainid == 298) {
            return actualPrecompileAddress;
        } else {
            return mockAddress; // ensure that the hardhat local node chainId is not equal to any of the Hedera network chainIds
        }
    }

    function associateTokens(address account, address[] memory tokens) internal returns (int responseCode) {
        address target = precompileAddress(); // will cost a bit more gas

        (bool success, bytes memory result) = target.call(
            abi.encodeWithSelector(IHederaTokenService.associateTokens.selector,
            account, tokens));
        responseCode = success ? abi.decode(result, (int32)) : HederaResponseCodes.UNKNOWN;
    }

    // other functions ...
}
```

## Foundry example

In Foundry, developers can use the `vm.etch` cheat code to deploy the mock contract at the same address as the precompiled contract on the Hedera network, and hence does NOT require any modifications to the `ExchangeRatePrecompile`, `PrngSystemContract` and `HederaTokenService` contracts to dynamically select a precompile address based on the network.

```solidity
HtsPrecompileMock htsPrecompileMock = new HtsPrecompileMock();
bytes memory code = address(htsPrecompileMock).code;
vm.etch(htsPrecompileAddress, code);
```

**Comment by Nana-EC** [comment]
Thanks @mshakeg for opening this.

**Comment by Nana-EC** [comment]
FYI @a-ridley might be of interest to you :)

**Comment by mshakeg** [comment]
So apparently Hardhat node offers a built-in solution that aligns with the needs of deploying contracts to known/pre-defined addresses. The custom JSON-RPC method, [hardhat_setCode](https://hardhat.org/hardhat-network/docs/reference#hardhat_setcode), can modify (or set) the bytecode of/at a given address.

Example usage would be as follows:

```javascript
const someSystemContractAddress = "0xSomeSystemContractAddress";
const someSystemContractBytecode = "0xSomeSystemContractBytecode";

await hre.network.provider.send("hardhat_setCode", [someSystemContractAddress, someSystemContractBytecode]);
```

After this deployment step, an instance of the system contract at the specified address can be created for interactions:

```javascript
const someSystemContract = await hre.ethers.getContractAt("SomeSystemContract", someSystemContractAddress);
```
