### ISSUE TITLE
Update gas calculation in eth method

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#118]
### Problem

Currently all the gas related items use an estimated static value since mIrror Node had not yet implemented the fee retrieval logic.

As such the gas prices used are not precise

### Solution

Update the logic to consume the Mirror Node endpoint

- Add a `getNetworkFees()` to `mirrorNodeClient`
- Call method from `eth` methods to get the gas fee
- Updated `eth.spec.ts` with tests

### Alternatives

if Mirror Node endpoint is still not available add middle of sprint then consensusNode may be consulted
- Add a  `getNetworkFees()` to `sdkClient`, parsing out gas price
- Call method from `eth` methods to get the gas fee
- Updated `eth.spec.ts` with tests

In this manor `eth` should be oblivious to the implementation of the source retrieval.
This in a future sprint the mirrorNode may be consulted for information

**Comment by Daniel-K-Ivanov** [comment]
Long term solution depends on https://github.com/hashgraph/hedera-mirror-node/issues/3578
