### ISSUE TITLE
Bump JS SDK version to 2.24.2

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1189]
### Problem

The relay currently utilizes v2.19.0 of the js sdk.

### Solution

Update to use a newer version of the sdk with https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.24.2

**Comment by AlfredoG87** [comment]
This was already addressed on PR #1241 
https://github.com/hashgraph/hedera-json-rpc-relay/pull/1241/files#diff-0ecec40455fd7053cd82ab9f46e65c0dc1e0fb19910a7cf1bd7f6c0211851619L8-L10
