### ISSUE TITLE
Add logic to renew sdk client instance

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1197]
### Problem

The relay utilizes the js SDK client in a  long lived manner submitting multiple queries and transactions over time.
This has performance consideration over time

### Solution

Add logic to renew the instance of the client every so often to ensure freshness.

Consider both timed options e.g. every 2hrs or a counter of transactions e.g. every 100k.
Both if considered separately or combined should be dynamic configurations that can be set

Notably this may require some coordination between `relay.ts` (where it's created), `eth.ts` (where it's used) and `sdkClient.ts` (where it's exposed)

**Comment by david-bakin-sl** [comment]
Or it could just be done brute-force by rolling over relay instances behind a load balancer ...

**Comment by mshakeg** [comment]
This sounds like functionality that should be made available directly by the js SDK for all dApps to configure and take advantage of.

Btw how does not renewing the client adversely affect performance?
