### ISSUE TITLE
Intermittent INVALID_TRANSACTION_BODY failures on eth_call

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1222]
### Description

The relay is occasionally experience errors on consensus node calls with the error
`transaction <relayAccountId>@<validStartNs> failed precheck with status INVALID_TRANSACTION_BODY`.

The problem relates to contract queries and transactions, specifically the response for `ContractCallQuery`, `AccountInfoQuery` and `EthereumTransaction`. This impacts `eth_call`, `eth_getTransactionCount` submissions and some `eth_sendRawTransaction` calls.

### Steps to reproduce

Occasional observed on `eth_call`, `eth_getTransactionCount` or `eth_sendRawTransaction` calls

### Hedera network

other

### Version

v0.22.0

### Operating system

None

**Comment by AlfredoG87** [comment]
@Nana-EC, I think this has been completely mitigated with fixes already implemented. I would recommend to close this ticket.

**Comment by Nana-EC** [comment]
Indeed
