### ISSUE TITLE
Intermittent FAIL_INVALID failures on eth_call

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1223]
### Description

The relay is occasionally experience errors on consensus node calls with the error
transaction <relayAccountId>@<validStartNs> failed precheck with status FAIL_INVALID

### Steps to reproduce

Make the occasional eth_call
More info to come

### Hedera network

other

### Version

v0.22.0

### Operating system

None

**Comment by ebadiere** [comment]
No occurrences on previewnet, testnet, or mainnet lately.
