### ISSUE TITLE
BlockByNumber method implementation error

### ISSUE THREAD

**Issue by AlexRipoll** [hashgraph/hedera-json-rpc-relay#1238]
### Description

When utilizing the go-ethereum (v1.10.25 or superior) library and Hedera's JSON-RPC (v0.23.1) relay, there are instances where invoking the `BlockByNumber` method functions correctly. However, on other occasions, invoking this method for a specific block number results in the following error message: "`missing required field maxPriorityFeePerGas for txdata`". 

### Steps to reproduce

1.Create a new main.go file with the following code.
```
package main

import (
    "context"
    "fmt"
    "log"
    "math/big"

    "github.com/ethereum/go-ethereum/ethclient"
)

func main() {
    url := "https://testnet.hashio.io/api"
    blockNum := 3689094

    client, err := ethclient.Dial(url)
    if err != nil {
        log.Fatal(err)
    }

    block, err := client.BlockByNumber(context.Background(), big.NewInt(int64(blockNum)))
    if err != nil {
        log.Fatal(err)
    }
    fmt.Println(block)
}
```
2. Create module `go mod init example.com/hedera` and download dependencies with `go mod tidy`
3. Run the code `go run main.go`

### Hedera network

testnet

### Version

v0.23.1

### Operating system

Linux

**Comment by Nana-EC** [comment]
@AlexRipoll please see https://github.com/hashgraph/hedera-json-rpc-relay/pull/1419
We'll be setting null instead of undefined. This should go into the next 0.27.0
Let us know if this resolves you issue as expected
