### ISSUE TITLE
The test 'should be able to transfer both fungible and non-fungible tokens in single cryptoTransfer' triggers the relay budget based rate limiting

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#1239]
### Description

This was discovered while trying to fix the test after the updated security model.  The contract function "cryptoTransferPublic" causes a lot eth_getTransactionCount calls which ends in an error with code -32606 HBAR Rate limit exceeded.

### Steps to reproduce

1. Run the test locally, perhaps in debug or surround the  ```  await mainContract.cryptoTransferPublic(tokenTransferList); ``` with debug logger messages.
2. Observe the message in the console log of the running json rpc relay.

### Hedera network

other

### Version

v0.23.0

### Operating system

None

**Comment by ebadiere** [comment]
The budget rateLimiting can be increased using the HBAR_RATE_LIMIT_TINYBAR, and the HBAR_RATE_LIMIT_DURATION environment variables: https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/docs/configuration.md

**Comment by Nana-EC** [comment]
@ebadiere should we close this or move to milestone 0.37?
