### ISSUE TITLE
Add default values to .env.example

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-json-rpc-relay#1246]
### Problem

Currently, it's difficult to know which values should be set in the .env file because the example does not provide default values. This sometimes results in misconfiguration, causing the JSON RPC relay to not work properly.

### Solution

To make running JSON-RPC easier, we should set default values in the .env file for developers so that they can easily get the server up and running.

**Comment by Nana-EC** [comment]
Thanks @pathornteng 
Which config values are you having issues with?
Many have defaults set as noted in https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/docs/configuration.md.
Note the relay requires a valid mirror and consensus node endpoint to operate, defaults for that depend on the environment hence leaving them empty but we could explore a default env.

Let us know which you may be having issues with so we can improve the defaults and docs.

**Comment by pathornteng** [comment]
@Nana-EC, I think most of them will go with empty .env as they just rename from .env.example to .env. I know that we have the document there but it's hidden in the repo and not mentioned in readme. 

I would suggest we pre-fill all variables in https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/.env.example so people can start the server without having to go through everything. The only blank ones should be account id and private key used by the relay.

**Comment by georgi-l95** [comment]
Also I believe most of the values have default ones in the code, so If you don't fill them, they will assume the default ones. So it would be helpful if you know which ones are causing issues, so we can fix them. In my mind, i'm seeing the ones in the `.env` as your custom ones that you want to use and if you want to use the relay with default configuration, you can just not set any and use it will assume default ones upon startup. (ofc i'm excluding the operator id and key)

**Comment by Nana-EC** [comment]
Thanks @pathornteng 
We could consider setting it default to testnet for someone to spin up.
The below would be the fix.

```
HEDERA_NETWORK=testnet
OPERATOR_ID_MAIN=<AccountID, can be obtained from portal.hedera.com>
OPERATOR_KEY_MAIN=<DER Encoded Private Key, can be obtained from portal.hedera.com>
CHAIN_ID=0x128
MIRROR_NODE_URL=https://testnet.mirrornode.hedera.com
```

**Comment by Nana-EC** [comment]
@pathornteng handled this in https://github.com/hashgraph/hedera-json-rpc-relay/pull/1413
