### ISSUE TITLE
FR: eth_newFilter and eth_getFilterChanges support

### ISSUE THREAD

**Issue by kabaluyot** [hashgraph/hedera-json-rpc-relay#1287]
### Problem

Using `eth_newFilter` and `eth_getFilterChanges` is another way to "make sure" an indexer API can receive real-time events together with the websockets event.

### Solution

Support `eth_newFilter` and `eth_getFilterChanges` as described in respective sections: https://ethereum.org/en/developers/docs/apis/json-rpc/

**Comment by Nana-EC** [comment]
Thanks for the suggestion @kabaluyot .
This is something we've consider and would like to get to but we're making through other items such as HIP 58, eth_subscribe and other items.

Is this blocking scenarios you're working on? If so I'd be interested to learn more. 

Additionally, we welcome community contributions so if you or someone from your team have some spare cycles  in the next few months you could consider contributing here with design and implementation.
If not we'll circle back to this at a later time.

**Comment by kabaluyot** [comment]
No worries, that's just another way for getting real-time events .. but really the most priority (and thank you in advance) is that eth_subscribe

**Comment by Nana-EC** [comment]
@kabaluyot FYI we've started to look into this.
Please see the design doc here https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/docs/design/eth-filter.md

**Comment by Nana-EC** [comment]
@kabaluyot closing the loop here but we implemented those endpoints some few months back.
Feel free to open a new ticket if you're experiencing any issues consuming them but they should be operational
