### ISSUE TITLE
eth_getTransactionCount returning `502` error

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#1323]
### Description

while working on `testnet` and using the method: `eth_getTransactionCount` sometimes, randomly but often we are getting the following error:

```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

### Steps to reproduce

Consume method `eth_getTransactionCount` many times until you get it.

### Hedera network

testnet

### Version

v0.25.0

### Operating system

None

**Comment by mshakeg** [comment]
@AlfredoG87 thanks, I would just add that it affects more than the `eth_getTransactionCount` method specifically `eth_sendRawTransaction`(for contract deploys and txs) and is potentially related to hashgraph/hedera-json-rpc-relay/issues/1139

**Comment by mshakeg** [comment]
Hey @AlfredoG87 just came across [paradigmxyz/flood](https://github.com/paradigmxyz/flood/) and thought it might be useful for load testing the relay and ensuring no serious performance degradation occurs with new releases.

**Comment by AlfredoG87** [comment]
@mshakeg will take a look into it, Thank you!! 👍

**Comment by AlfredoG87** [comment]
@mshakeg

`502 ServerError` is thrown after `timeouts` due to a limitation of the used LoadBalancer/Gateway that will consume the actual error, and always throw a `502` instead of the actual status code and error message. This "bug" is only on HashIO Environments and not when running the relay instance locally.

Seems like with the recent rollout of some method optimizations and also load type normalized and methods stopped timing out, and throwing `502` errors.

During the exploration of the error timeout was moved from `30s` to `60s` but since load diminished and optimizations were released there is a very low timeouts above `30s` and none above `60s`. For that reason we might consider leaving it at `60s` for a little longer while we add more optimizations that can further avoid getting timeouts.


Please could you confirm that the error is no longer happening so we can close this issue?

**Comment by mshakeg** [comment]
@AlfredoG87 thanks for the update. I can confirm that I no longer have this issue on testnet but that's likely because even large contract deployments take <60s, however, on mainnet those same contracts would take close to 2 minutes and so I would suspect that the issue(though not major as the contracts do eventually deploy successfully) would still exist on mainnet.

**Comment by AlfredoG87** [comment]
Hi @mshakeg  we believe the timeout issues are solved. I think we should close this ticket based on current statistics.

We have been doing a lot of optimizations to improve performance, tweaking some internal parameters, and also found and [fixed](https://github.com/hashgraph/hedera-json-rpc-relay/pull/1519) a known issue of NodeJS that was responsible for delays when many simultaneous outgoing requests are made.

<img width="1895" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/ab1b90e6-2dae-49af-a0fa-a41ed38a77b3">

I will be closing this ticket but if you believe this is happening again, please let us know! 👍
