### ISSUE TITLE
Update eth_sendRawTransaction to utilize Mirror Node on transaction record calls

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1333]
### Problem

Currently the relay primarily calls the consensus node to retrieve the `TransactionRecord` to retrieve the `ethereumHash` to return.
However, this is not performant for the relay balance as it can be retrieved from the Mirror Node

### Solution

Call the `api/v1/contracts/results/{transactionIdOrHash}` and return the `hash` as this is the value

Note, `TransactionRecord` was also used to get the fee charged.
This can be retrieve from the `api/v1/contracts/results/{transactionId}` using the `charged_tx_fee` value

**Comment by AlfredoG87** [comment]
might be good to include this other ticket in this refactor: https://github.com/hashgraph/hedera-json-rpc-relay/issues/1336
