### ISSUE TITLE
eth_sendRawTransaction is returning hash when receiving wrong_nonce (bigger than expected) instead of error

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#1336]
### Description

Currently if sending a transaction using a wrong nonce, there are 2 possibilities:
1. Nonce is too low, we are returning the appropriate message
2. Nonce is too big (bigger than the expected current nonce). We are returning a computed hash for the transaction, but that hash does not exist, since the SDK returned `wrong_nonce` 

### Steps to reproduce

 you can use this transaction on `previewnet` to replicate the issue.
 
 ```
0xf8ed818b85f7f6f25a008301c3e89410df38c7381cf2154a0fc3fb5455ab60b0483b0b80b884a4136862000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000304772656574696e67732066726f6d204175746f6d617465642054657374204e756d626572203133392c2048656c6c6f2100000000000000000000000000000000820276a0029a12dad96a95df97926ad0e044092ed7faf02948a16022818a0814523592cea07cedecff37a0ffd57ef9653580b118d79350c240f8e3923505e395764f3d59d5
 ```

```
curl --location 'https://previewnet.hashio.io/api' \
--header 'Content-Type: application/json' \
--data '{
    "method": "eth_sendRawTransaction",
    "params": [
        "0xf8ed818b85f7f6f25a008301c3e89410df38c7381cf2154a0fc3fb5455ab60b0483b0b80b884a4136862000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000304772656574696e67732066726f6d204175746f6d617465642054657374204e756d626572203133392c2048656c6c6f2100000000000000000000000000000000820276a0029a12dad96a95df97926ad0e044092ed7faf02948a16022818a0814523592cea07cedecff37a0ffd57ef9653580b118d79350c240f8e3923505e395764f3d59d5"
    ],
    "id": 120,
    "jsonrpc": "2.0"
}'
```

### Additional context

This transactions are also logging an error that the transaction record was not found (since the sdk did not processed the transaction due to wrong nonce, but still the relay is returning the `computed hash`

<img width="1313" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/041b3d51-04ba-4b53-a55b-1afcb69e7684">

<img width="870" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/f79bbb87-03df-4d37-8943-62b9eaa104f4">

There are 2 ways to avoid this.

1. To verify before submitting the transaction to the SDK if the nonce is too high.
2. To handle the response from the SDK `WRONG_NONCE` and return an appropriate error message to the user.

The logic in question is happening here: https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L1102C5-L1127

### Hedera network

mainnet, testnet, previewnet

### Version

v0.25.0

### Operating system

None

**Comment by AlfredoG87** [comment]
Might be worked together with this other ticket: 

https://github.com/hashgraph/hedera-json-rpc-relay/issues/1333

**Comment by georgi-l95** [comment]
Easier way to reproduce this is by sending a transaction via metamask (for example simple contract call or transfer) and entering custom higher nonce.
