### ISSUE TITLE
502s are returned on some accounts with thousands of transactions in a block.  An error should be returned.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#1357]
### Description

502s are returned with some requests against testnet.  The release and K6 performance tests may trigger these.  If so we'll need to update the accounts/addresses used.

### Steps to reproduce

The following curl request will reproduce it.

```
curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":"2","method":"eth_getBlockByHash","params":["0xfd601bc88c27e104f52cc35c2397c5bda69fd47b808d0ec59f0987283df62b5d", true]}'  https://testnet.hashio.io/api
```

```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```
Timing details:

```
Establish Connection: 0.209954s
TTFB: 0.237018s
Total: 30.305170s
0.01s user 0.01s system 0% cpu 30.210 total
```

### Hedera network

testnet

### Version

v0.25.0

### Operating system

None

**Comment by Nana-EC** [comment]
We should explore the use of a `predefined.MAX_BLOCK_SIZE` error concept in the mean time until we've optimized it.
Also we should make it's enablement configureable.
