### ISSUE TITLE
Update try/catch test logic to verify errors are thrown

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1371]
### Problem

In some cases we have tests that check for an error using a try / catch.
However they don't check for if the error was actually thrown, which means we may have tests that should be failing but aren't.

### Solution

Update try/catch test logic to verify errors are thrown.
Either
- add a flag that is updated on catch and check for the update e.g. #1370 
- Switch try/catch for some asynchronous throws verification in mocha

This may span across many files so multiple PR's or tickets can be broken out of this as applicable

**Comment by konstantinabl** [comment]
Findings while working on the issue:

1. In different tests we send raw transactions in different ways - relay.call or relay.sendRawTransaction. Possibly approach should be unified
2. Assertions.expectedError() used, but not needed

**Comment by Ivo-Yankov** [comment]
Breaking this down into smaller issues:

- [ ] #1437 
- [ ] #1438 
- [ ] #1439 
- [ ] #1440
