### ISSUE TITLE
All Contract Deploys fails with INSUFFICIENT_TX_FEE

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#1373]
### Description

Recently I haven't been able to deploy contracts to testnet(including contracts that I've previously deployed fine). The transaction fails with `INSUFFICIENT_TX_FEE`.

Take the following tx as an example:
https://hashscan.io/testnet/tx/0xbadb03cb0865d0b86b482d3c5c34cf504653e729a5574fb500ecf417d3c07562

### Steps to reproduce

1. Checkout to [this fork](https://github.com/mshakeg/hedera-json-rpc-relay)
2. Run the `test:smc:testnet` script in `./tools/hardhat-example`. The script should fail and you should be able to extract the transaction hash from the error logs. Observe that the tx failed due to `INSUFFICIENT_TX_FEE`

### Hedera network

testnet

### Version

relay/0.25.0

### Operating system

None

**Comment by mshakeg** [comment]
Using a gas price that is 2x the result from eth_gasPrice seems to fix it.

**Comment by kabaluyot** [comment]
try this:

```
  const erc20DAOFactory = await ERC20DAOFactory.deploy({
    gasLimit: 5000000
  });
```

**Comment by kabaluyot** [comment]
And you mentioned it seems to work now when setting gas price to 2x of eth_gasPrice?

**Comment by kabaluyot** [comment]
My usual errors when deploying contracts in hedera-hardhat is HEADER_TIMEOUT from RPC testnet :/

**Comment by Nana-EC** [comment]
@IvanKavaldzhiev please see this. We might be seeing regressions from Mirror Node gas values returned from HIP 584 work.

@mshakeg and @kabaluyot are you still experiencing this.
Also did you say it was intermittent or did you mean it formerly worked and recently started displaying this consistent issue of gasEstimate being too low?

**Comment by mshakeg** [comment]
@Nana-EC it's intermittent now however around the time this issue(and up to at least 1 day after) was created it was definitely guaranteed from my experience. I was deploying using hardhat ethers and I suspect the issue was the relay returning an invalid(lower than actual) gas price, hence why specifying a gasPrice override equal to the returned gasPrice did not work but 2x(the returned gasPrice) did.

**Comment by IvanKavaldzhiev** [comment]
Hey @Nana-EC, this [PR](https://github.com/hashgraph/hedera-mirror-node/pull/6056) has fixed having proper contract create gas estimation. It's in 0.82 release, so from then on, we shouldn't have problems with estimating contract creates. I think on testnet we have 0.82, so I believe the issue won't be on Mirror Archive Node side but could be related to the json-rpc instance there or the environment itself.

cc @georgi-l95

**Comment by Nana-EC** [comment]
@mshakeg can you confirm you're no longer seeing this. mirror node 0.82 has been out for some time and 0.84 is going out and in previewnet already, with 0.83 in testnet.

**Comment by mshakeg** [comment]
@Nana-EC thanks for the update. As of now, the INSUFFICIENT_TX_FEE issue does not seem to be occurring on the testnet.

However, I'd like to bring up the deployment times. It's taking about 240 seconds to deploy 10 medium-sized contracts (~10KB each), which is approximately 24 seconds per contract. For example, see [contract/0.0.15063291](https://hashscan.io/testnet/contract/0.0.15063291). From my experience, these times are likely to be longer on the mainnet, and for larger contracts (~25KB), it takes close to a minute on the testnet and nearly 2 minutes on the mainnet.

The underlying reason seems to be that the contract bytecode is uploaded to the Hedera File System (HFS) in 2KB chunks sequentially, taking around 5 seconds per chunk.

Could the chunk size be increased to reduce deployment times, for instance, to 10KB? This could reduce the number of uploads needed and likely speed up the contract deployment process.

I'd appreciate your thoughts on this.

**Comment by Nana-EC** [comment]
Thanks @mshakeg 
Will resolve this ticket and open a separate one for chunking optimization. 

To clarify were you referring to [sdkClient.createFile()](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/clients/sdkClient.ts#L533)?
You might be mixing it up with the ContractCreateFlow where the chunkSize is indeed 2KB [in the sdk](https://github.com/hashgraph/hedera-sdk-js/blob/develop/src/contract/ContractCreateFlow.js#L367), the relay [defaults to 4kb](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/clients/sdkClient.ts#L533).

We can definitely look into it and see how much higher we can set it but not we can't go above the HAPI transaction 6kb limitation, so 10kb won't be possible.

**Comment by Nana-EC** [comment]
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1522 created based on above.
@mshakeg feel free to respond to that ticket regarding the FilleAppend details .

Closing this ticket
