### ISSUE TITLE
Add acceptance test support for getLogs

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#140]
### Problem

#103 added support for getLogs.
However , this preceded the acceptance tests so support was not added

### Solution

Add a tests that calls `eth_getLogs` with coverage for a combination of the following params
- fromBlock
- toBlock
- address
- topics
- blockhash

**Comment by Daniel-K-Ivanov** [comment]
- If nothing is passed in the filter (filter is empty) f.e:
```
{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "eth_getLogs",
  "params": [
    {}
  ]
}
```
The response must be all logs from the most recent block
- If only `fromBlock` is specified, we must query all logs from the beginning (specified block) until now for all contracts.
- If only `toBlock` is specified, we must query all blocks until the `toBlock`
- Add tests with 1, 2, 3, and 4 topics filter -> topics must be considered OR filter not AND
- If we are passing only `address` -> we must return all logs for that address (address can be account or contract). If no events are found the response should be:

```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": []
}
```

**Comment by Kalina-Todorova** [comment]
We can use this contract to test all options:
`// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.0;

contract Logs {

    event Log0(uint256 num1) anonymous; // Does not include topic
    event Log1(uint256 indexed num0);
    event Log2(uint256 indexed num0, uint256 indexed num1);
    event Log3(uint256 indexed num0, uint256 indexed num1, uint256 indexed num2);
    event Log4(uint256 indexed num0, uint256 indexed num1, uint256 indexed num2, uint256 num3);

    function log0(uint n) public {
        emit Log0(n);
    }

    function log1(uint n) public {
        emit Log1(n);
    }

    function log2(uint n0, uint n1) public {
        emit Log2(n0, n1);
    }

    function log3(uint n0, uint n1, uint n2) public {
        emit Log3(n0, n1, n2);
    }

    function log4(uint n0, uint n1, uint n2, uint n3) public {
        emit Log4(n0, n1, n2, n3);
    }
}`
