### ISSUE TITLE
CORS issue on HashIO

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-json-rpc-relay#1423]
### Description

Currently, the JSON RPC relay does not return the correct `CORS` header when it receives an `OPTIONS` request from the browser. The `OPTIONS` request is automatically sent to the server as part of the preflight process. Therefore, if the response during the preflight is not correct, the browser will not send a real request and throw an error as follow 

<img width="673" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/2261017/2905a0b9-9d82-4245-aef2-f3c47803fa0d">

### Steps to reproduce

Go to the following website 
https://cors-test.codehappy.dev/?url=https%3A%2F%2Ftestnet.hashio.io%2Fapi&origin=https%3A%2F%2Fcors-test.codehappy.dev%2F&method=options

Choose `OPTIONS` and then click test.

The following is the response from HashIO testnet server and it indicates that the header in the response does not contain `access-control-allow-origin`

<img width="814" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/2261017/2c46cd84-d57d-4e3b-8c44-1d8a226d7c8f">
 

### Hedera network

mainnet, testnet, previewnet

### Version

latest

### Operating system

None

**Comment by Nana-EC** [comment]
Best approach would be to add support for an env variable that let's a relay operator set their desired `access-control-allow-origin` configs.
We use `koa-cors` so you can see how options may be configured here https://github.com/koajs/cors/blob/master/test/cors.test.js

In the relay we'd do this in the `server.ts` file (eventually in a separate middleware file)

**Comment by Nana-EC** [comment]
Actually i think the issue might simply be that the relay does not support HTTP OPTIONS requests, as the cors details are configured as noted.

The only API requests we support with use cases are `GET` and `POST`.
Is your app explicitly calling the OPTIONS method in advance to understand the server capabilities or is there some other scenario that's notable here?
