### ISSUE TITLE
RequestId can be embedded into a previously formatted requestId creating a buggy looking console log line

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#1445]
### Description

The requestId can be embedded into a previously formatted requestId creating a buggy looking console log line:
```
[2023-07-05 13:36:45.200 +0000] TRACE (relay-eth/81468 on Admins-Laptop.hsd1.co.comcast.net): [Request ID: [Request ID: df0aa6f2-b68c-4871-beca-70ef8103e4d5]] chainId()
```

### Steps to reproduce

1. Start the relay locally and run eth_chainId against it:
2. Observe the console log.

```
curl --location 'http://localhost:7546' \
--header 'Content-Type: application/json' \
--data '{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_chainId"
}'
```

### Additional context

This is caused by the formatter method:

```
/**
* Format message prefix for logger.
*/
const formatRequestIdMessage = (requestId?: string): string => {
    return requestId ? `[${constants.REQUEST_ID_STRING}${requestId}]` : '';
};
```
Removing the ternary operator should fix this issue, however it could also lead to empty request IDs being displayed which would also look buggy.  Reversing the ternary could also fix this but could lead to the same issue mentioned, empty request IDs being displayed.  Some research needs to be done.

### Hedera network

testnet

### Version

v0.26.0

### Operating system

macOS

**Comment by stefan-stefanooov** [comment]
Hello Mr @ebadiere

I am not able to reproduce it.
Can you please verify ?

**Comment by stefan-stefanooov** [comment]
I took the opportunity to fix some cases where **requestId** was not propagated down the pipeline of a request handlers.
It was displaying as **undefined**. In the same task.
