### ISSUE TITLE
EPIC: EVM Tool Support

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#1460]
### Problem

As a developer I'd like to be able to use evm tools and know how much support does the relay cover.

### Solution

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1136
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1491
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1492
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1511
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1040
```

### References

Ethers V6 SDK Issue - https://github.com/hashgraph/hedera-sdk-js/issues/1615
Solidity-coverage - https://github.com/hashgraph/hedera-json-rpc-relay/issues/416

**Comment by Nana-EC** [comment]
@georgi-l95 please confirm this is completed and close. Thanks

**Comment by georgi-l95** [comment]
Yes, this should be closed, it's resolved.
