### ISSUE TITLE
[Design] Add monitoring and alerting rules

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1472]
### Problem

The relay publishes metrics uses prometheus, however, no rules are defined to enable relay operators to observe and support alerting.

### Solution

Explore the design and necessary implementation steps to support this and update the relay.
Create sub epic tasklist to capture the necessary work

**Comment by Nana-EC** [comment]
@AlfredoG87 Please update and commit alert rules to repo under https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/charts/hedera-json-rpc/dashboards

Additionally please add a design ticket to explore an E2E monitoring application to replicate user requests from outside and utilize existing tests on a regular cadence and support alerting

**Comment by AlfredoG87** [comment]
> 

https://github.com/hashgraph/hedera-json-rpc-relay/issues/1690

**Comment by Nana-EC** [comment]
@AlfredoG87 did we complete this work?
If so let's close this

**Comment by AlfredoG87** [comment]
> @AlfredoG87 did we complete this work? If so let's close this

Yes, we can open up another one for follow-ups, since is a constant improvement but we are satisfied where we are now.
