### ISSUE TITLE
Add Solidity-Coverage support

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#1491]
### Problem

As a developer I'd like to be able to use solidity-coverage with the relay.

### Solution

Document the supported functionality in the tools documentation and how to use it.

**Comment by bibitibooo1** [comment]
To document in the repo you can use it without system contract + maybe add an example in the repo.

**Comment by Nana-EC** [comment]
@georgi-l95 and @stefan-stefanooov did we resolve this ticket based on the current content under https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/tools/solidity-coverage-example or what's the follow up?

**Comment by georgi-l95** [comment]
I think it's resolved, at least there is nothing more we can do at this point.

**Comment by bibitibooo1** [comment]
Moving it to Done then. :)
