### ISSUE TITLE
Update the acceptance test for eth_gasPrice

### ISSUE THREAD

**Issue by ar-conmit** [hashgraph/hedera-json-rpc-relay#150]
### Problem

The current released version of mirror-node(`0.57.2`) does not include the endpoint for retrieving gas fees `/network/fees`, so the acceptance test is temporary disabled.

### Solution

Enable the acceptance test for `eth_gasPrice` once a new version of mirror-node is released and the endpoint `/network/fees` exists.

**Comment by Nana-EC** [comment]
Yes, we're waiting on a `0.58.0-rc1`, which should be out today to unblock this.
Notably the test case exists but it uses the cached value so this is more an "Update" than an "Add"

**Comment by Nana-EC** [comment]
Addressed for #211
