### ISSUE TITLE
Optimize FileAppend flow on contract creation

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1522]
### Problem

Currently the relay uses [a 4kb default](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/clients/sdkClient.ts#L533) for chunk size of file creation.
It may be possible to increase it

Create in follow up from https://github.com/hashgraph/hedera-json-rpc-relay/issues/1373#issuecomment-1625126999

### Solution

Test out how much larger the chunk size can be made without hitting the HAPI transaction 6kb size limit.

Additionally, make the size configurable

**Comment by mshakeg** [comment]
@Nana-EC given the HAPI transaction size limit(i.e. 6kb) is very close to 4kb(for chunk size on file appends) I don't think there's a lot of improvement to be made here. However, if the chunk size for the initial file creation is 2kb there's more potential to be made by increasing this in the short term imo.

Longer term could the HAPI transaction size limit be increased beyond 6kb at least for HSCS transactions as Ethereum allows for much larger transactions constrained only by the gas limit. Take [this transaction](https://etherscan.io/tx/0x25e54394ab4e5f17d6e1240c02c1a6c4bb675ef9471f1105b006988f5fe5aec1) as an example which used ~3m gas and has a input data size of ~44KB. imu this would not be possible on Hedera due to the 6KB limit.

**Comment by Nana-EC** [comment]
Hey @mshakeg 
Notably the FileCreate also uses 4kb. 
Where are you seeing 2kb?

Unfortunately like similar conversations on the topic the transaction limit has much larger implications than just EthereumTransaction flows, so increasing the 6kb isn't an easy option to make through considerations.
Managing the 6kb threshold is a large reason for utilizing File contents in the ethereum flow as it impacts scalability and other items.

**Comment by Nana-EC** [comment]
Sounds like there's not much wiggle room here and it affirms why the 4kb was chosen. Will close unless something else comes up.

**Comment by mshakeg** [comment]
Hey @Nana-EC you're correct, it's 4KB for FileCreate as well.

Wouldn't this [HIP](https://github.com/hashgraph/hedera-improvement-proposal/discussions/531) require an increase to the HAPI transaction size limit? Wonder why other chains don't have an issue with a much higher transaction size limit.

**Comment by Nana-EC** [comment]
> Hey @Nana-EC you're correct, it's 4KB for FileCreate as well.
> 
> Wouldn't this [HIP](https://github.com/hashgraph/hedera-improvement-proposal/discussions/531) require an increase to the HAPI transaction size limit? Wonder why other chains don't have an issue with a much higher transaction size limit.

On the contrary I think the HIP will likely make it explicit that even if batched the transaction stays within the 6kb limit. See [HIP 551](https://github.com/hashgraph/hedera-improvement-proposal/pull/551) which is proposed HIP from that discussion.
You can comment on that HIP also as discussions are still live.

**Comment by Nana-EC** [comment]
> Hey @Nana-EC you're correct, it's 4KB for FileCreate as well.
> 
> Wouldn't this [HIP](https://github.com/hashgraph/hedera-improvement-proposal/discussions/531) require an increase to the HAPI transaction size limit? Wonder why other chains don't have an issue with a much higher transaction size limit.

Regarding why other chains don't hit this issue I'd speculate not many other L1's are able to do 1000's of TPS when throttled. They may also not break the historical data to the detail of what is stored and made available via the Mirror Node as similar speeds. Our challenge is we're designing for that speed and scalability whiles ensuring fair access to rich data amongst other items.
We definitely appreciate the challenge of the 6kb vs other considerations and it factors into the teams considerations.

As always we appreciate your perspective on this and other topics so thanks for highlighting.
Thanks

**Comment by Nana-EC** [comment]
Closing this issues are regarding the FileAppend there isn't a next step.
