### ISSUE TITLE
Make setMaxQueryPayment configurable

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-json-rpc-relay#1523]
### Problem

Currently, the JSON RPC relay uses the Hedera JavaScript SDK to query smart contract bytecodes from the consensus node 
https://github.com/hashgraph/hedera-json-rpc-relay/blob/3c2fe6784aeb973f4686c7ce32bd1dba1e25e6ac/packages/relay/src/lib/clients/sdkClient.ts#L138
The current default max query payment is 1 hbar, and it's not configurable from the relay. Therefore, it can cause some queries for big smart contracts to fail because the max query payment is set too low.

### Solution

- Make `setMaxPaymentQuery` configurable from the relay environment variable.

**Comment by Nana-EC** [comment]
Thanks @pathornteng 
I don't think as an operator we want to just bump up the maxFee.
However, I do agree the default maxFee of 1 HBAR is getting in the way.

Probably the better approach is to get the cost and set the max fee appropriately.

We'll address this. Thanks
