### ISSUE TITLE
Acceptance Tests are shaky

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#1539]
### Description

I think started to happen this week, but not sure when it started, but not too long ago.

What is happening is that acceptance tests are failing, some times, and take 50m or more to fail.
That is happening due to an error in the starting of the local-node, my guess is that a race condition could be happening, since does not always happen.

<img width="741" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/0956c473-d5a8-430f-af4e-83467de9f09e">

### Steps to reproduce

1. Do a PR for any change, a small change.
2. Wait for the Tests to finish and see if it happens (it might not happen everytime)

### Additional context

https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/5590787170/jobs/10220977558?pr=1538

### Hedera network

other

### Version

v0.27.0

### Operating system

Linux

**Comment by Nana-EC** [comment]
The image in question related to the Mirror Node db.
As part of startup the schema is set and all tables are created.
Curious failure 🤔

**Comment by ebadiere** [comment]
I am not seeing this in the CI jobs.  If I don't see it for another day I am going to close this.

**Comment by ebadiere** [comment]
I did not see this in the release of 0.31.1.
