### ISSUE TITLE
Acceptance Test: Release - 2 Tests are failing

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#1579]
### Description

The 2 following errors are failing when doing the `acceptancetest:release` against `tesnet`.

```
@release should execute "eth_getBlockByHash", hydrated transactions = true:
@release should execute "eth_getBlockByNumber", hydrated transactions = true:
```

They are failing since the test what it does is compare the amount of transactions  from the response from the `mirror node` and the amount of transactions from the response of the `relay` however these amounts are different due to the latter including `synthetic transactions`

see the following example:

**Mirror Node request:**

```
https://testnet.mirrornode.hedera.com/api/v1/contracts/results?timestamp=gte:1690494460.139291227&timestamp=lte:1690494461.718756003
```

**Mirror Node Response:**

```
{
"results": [
{
"address": "0x00000000000000000000000000000000000060c4",
"amount": 0,
"bloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
"call_result": "0x",
"contract_id": "0.0.24772",
"created_contract_ids": [],
"error_message": null,
"from": "0x00000000000000000000000000000000000060b1",
"function_parameters": "0x0419eca50000000000000000000000000000000000000000000000000000000000000001",
"gas_limit": 75000,
"gas_used": 60000,
"timestamp": "1690494461.279495003",
"to": "0x00000000000000000000000000000000000060c4",
"hash": "0xc5e8e198d81c38c47f4cee5b00c984d418555b8361914dcb15588a68f2761d3b"
}
],
"links": {
"next": null
}
}
```

**Relay request:**

```
curl --location 'https://testnet.hashio.io/api' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": ["0x1AA8", true],
    "id": 1
}'
```

In this example it has `88` txs the Relay vs the MirrorNode only `1` 

The extra 87 txs  are coming from logs with the same `Timestamp` range as the block.

**Mirror Node Logs Request:**

```
https://testnet.mirrornode.hedera.com/api/v1/contracts/results/logs?timestamp=gte:1690494460.139291227&timestamp=lte:1690494461.718756003&limit=1000&order=asc
```

### Steps to reproduce

Run the command 

```
npm run acceptancetest:release
```

with the .env configured against `testnet`

***Note:*** it might be needed to re-run the test a couple times.

### Hedera network

testnet

### Version

v0.28.1

### Operating system

None

**Comment by AlfredoG87** [comment]
@georgi-l95

I think the solution is to change the tests themselves.

I can think of 2 ways to change the test.

1. When comparing the amount of txns from mirror-node and relay, to ignore the synthetic txns.
2. When caomparing the amount of txns from mirror-node and relay, add to the number of txns from the block of the mirror node, also the amount of logs for that same timestamp range and then compare it with the results from the relay.

**Comment by Nana-EC** [comment]
> @georgi-l95
> 
> I think the solution is to change the tests themselves.
> 
> I can think of 2 ways to change the test.
> 
> 1. When comparing the amount of txns from mirror-node and relay, to ignore the synthetic txns.
> 2. When caomparing the amount of txns from mirror-node and relay, add to the number of txns from the block of the mirror node, also the amount of logs for that same timestamp range and then compare it with the results from the relay.

@AlfredoG87 For an initial approach I'd say # 2. Maybe in the order of 
1. Check for # returned txns = # mirror contract results + # synthetic logs 
2. Check details to ensure timestamps match up
3. Check other details

I think for now # 1 should be enough to unblock
