### ISSUE TITLE
CI/CD pipeline - add code coverage

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-json-rpc-relay#16]
Check if we have permissions to add codecov
Add code coverage checks to the CI/CD

**Comment by Nana-EC** [comment]
CI/CD setup through Github work flow was addressed in #48.
Currently there's an issue that once address by #89 we'll see the coverage start flowing

**Comment by Nana-EC** [comment]
@ebadiere noted we have sonar. @georgi-l95 agreed.
Closing
