### ISSUE TITLE
Fix pending test in rpc batch 2

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#1623]
Currently there are several tests set on pending because of issue https://github.com/hashgraph/hedera-mirror-node/issues/6620. When it's fixed and there is a image, we can fix the tests.

**Comment by Nana-EC** [comment]
@georgi-l95 can we close this now? Please go ahead if so

**Comment by georgi-l95** [comment]
@Nana-EC Can be closed, yes.
