### ISSUE TITLE
NX Dependency Override - remove whenever possible

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#1636]
once the dependency for NX fixes this issue, remove the override.

              We should note in comments why and when this override is no longer needed if possible

_Originally posted by @Nana-EC in https://github.com/hashgraph/hedera-json-rpc-relay/pull/1634#discussion_r1291857566_

**Comment by Nana-EC** [comment]
@AlfredoG87 is this still applicable?

**Comment by AlfredoG87** [comment]
we still have the dependency, not sure why 

> @AlfredoG87 is this still applicable?

I've created a PR for this, seems like the issue is resolved now. 👍 

https://github.com/hashgraph/hedera-json-rpc-relay/pull/2365
