### ISSUE TITLE
eth_getBalance returns 500 error due to account not found

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#1648]
### Description

Due to an increase of failed requests on both `previewnet` and `testnet` did some research and found the following:
1. Those failed requests were due to `eth_getBalance` method and the response status code was `500` (Server error)
2. The logic inside the `eth_getBalance` is trying to get account info, and getting `404` (null account)
3. trying to read null --> Error.

https://cloudlogging.app.goo.gl/zoCAEqJXRgNr4EWp6

### Steps to reproduce
```
curl --location 'https://testnet.hashio.io/api' \
--header 'Content-Type: application/json' \
--data '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "eth_getBalance",
    "params": [
        "0x00a338914aa6c7141241e8e61f613dc8f0baabbf",
        "0xdef41"
    ]
}'
```
### Additional context

https://cloudlogging.app.goo.gl/zoCAEqJXRgNr4EWp6

https://cloudlogging.app.goo.gl/WjWqwffPk3GRgMvWA

### Hedera network

testnet, previewnet

### Version

v0.29.1

### Operating system

macOS

**Comment by Nana-EC** [comment]
We should handle not found accounts with 0 HBAR response as is consistent on the EVM
