### ISSUE TITLE
FInalise the design of `eth_getTransactionCount` for Contracts

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hedera-json-rpc-relay#165]
**Problem**
Nonces for a contract are `1 + n` where `n` is the number of times the contract created other contracts through `CREATE` or `CREATE2`. The deployment of the contract itself is considered part of the nonce, that's why the nonce starts from 1.

Currently `eth_getTransactionCount` for contracts returns hardcoded value of `1`.

**Solution**
Clear out how services will handle `nonces` for contracts and whether they will do something with nonces. Once the design is defined, a discussion on how to handle them on the relay side must be conducted.

A potential solution for services -> Update the nonce of the contract for every CREATE / CREATE2 opcode executed from it.

**Comment by Kalina-Todorova** [comment]
Filed a ticket in hedera-services to address this: https://github.com/hashgraph/hedera-services/issues/3640
