### ISSUE TITLE
Add solidity-coverage example and docs under tools

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1668]
### Problem

There has been interest around the use of solidity-coverage.
The team has explored and tried out integration with Hedera networks

### Solution

Add a `solidity-coverage` folder under https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/tools with an independent npm project as a reference.
Update main README and add an individual README to highlight what's supported and what's not possible based on the product limitations 

```[tasklist]
### Tasks
```

**Comment by Nana-EC** [comment]
@bibitibooo1 and @stefan-stefanooov can we close this? Seems it wasn't connected to a PR that already addressed this

**Comment by stefan-stefanooov** [comment]
@Nana-EC Yes. It has been done for a while now. We can close it.
