### ISSUE TITLE
Flaky Test is failing intermittenly

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#1669]
### Description

When running PR CI Tests, there is one test that has been appearing up a lot of times:

```
1) RPC Server Acceptance Tests
       Acceptance tests
         @api-batch-1 RPC Server Acceptance Tests
           RPC Server Acceptance Tests
             Transaction related RPC Calls
               should execute "eth_sendRawTransaction" for London transactions:

      AssertionError: expected '0' to equal '10000000000'
      + expected - actual

      -0
      +10000000000
```

### Steps to reproduce

Not always happens, but any PR on the CI should potentially be able to make it happen.

### Hedera network

other

### Version

0.30.0-rc1

### Operating system

None

**Comment by AlfredoG87** [comment]
I have not seen this issue lately. maybe we can close this.

**Comment by ebadiere** [comment]
Could not reproduce.
