### ISSUE TITLE
Add additional E2E tests for HBAR/Token allowances.

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#1681]
### Problem

We don't have full coverage of approvals/transfers and allowances for HBAR/Token when wrapped like ERC20.

### Solution

Add and expand current test cases so we can have more coverage and notice, if there are regressions.

**Comment by Nana-EC** [comment]
@georgi-l95 should we close this or move to milestone 0.37?

**Comment by georgi-l95** [comment]
I believe we should close it, because we currently have enough coverage.

**Comment by AlfredoG87** [comment]
Closing this since is not necessary
