### ISSUE TITLE
EVM transactions DEBUG: `debug_traceTransaction` support: add endpoint on the relay side

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-json-rpc-relay#1698]
# Overview

### Definition

Add support for debugging historical transactions with different tracers.

### **Abstract**

Implement the `debug_traceTransaction` JSON-RPC endpoint.

### **Motivation**

Enhancing Mirror Archive Node with debug calls would allow users to replay historical transactions and inspect and analyse them by having detailed information for the execution based on a tracer type that is specified in the request. In addition, this enhancement would improve Hedera interoperability with different ethereum tools and providers, including Remix, Hardhat, Ganache, Geth, Alchemy, etc.
The JSON-RPC Relay should expose the new Mirror Node endpoints via its rpc API.

### **Rationale**

Add support of `debug_traceTransaction` in the JSON-RPC Relay which returns detailed information for a historical transaction that was executed in the past.

The JSON-RPC Relay will make a request to the Mirror Node REST API which will be enhanced with a couple of new endpoints that return debug logs.

### User stories

1. As a user, I want to perform `debug_traceTransaction` calls to explore the op code traces for a historical transaction.
2. As a user, I want to perform `debug_traceTransaction` calls to explore the sub calls that were executed for a historical transaction.

### **Specification**

1. Add the `debug_traceTransaction` endpoint to the JSON-RPC Relay
2. Handle requests to the new `debug_traceTransaction` endpoint by:
    1. decoding the input parameters
    2. calling the correct mirror node endpoint depending on the tracer 
    3. translating the input parameters from the JSON-RPC request to the correct format expected by the Mirror node REST API endpoint.
    4. translating and returning the information in the expected format
3. Create and implement a test plan - include scenarios that test if the mirror node supports 0, 1, or both of the endpoints; valid/invalid transaction hashes, inputs, flags, etc

### **Backwards compatibility**

We’re adding a new endpoint to the Relay so no impact on backwards compatibility is expected.

### **Security Implications**

Some outputs from tracing transactions (especially with the opcode logger tracer) can be pretty large and could have impact on the Relay performance.

### **References/Dependencies**

1. [HIP-584: Mirror EVM Archive Node](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-584.md) 
2. [EVM Archive Node with Historical block support for `eth_call` -design doc- [shared]](https://www.notion.so/EVM-Archive-Node-with-Historical-block-support-for-eth_call-design-doc-shared-7ffd952a53ff4677ac71fad1b46c9678?pvs=21)
3. [Draft HIP-XXX for `debug_traceTransaction` support [shared]](https://www.notion.so/Draft-HIP-XXX-for-debug_traceTransaction-support-shared-2e8b8673ab404621b6ac48d7532f4bb3?pvs=21)

**Comment by Nana-EC** [comment]
`debug_traceTransaction` endpoint was added
