### ISSUE TITLE
Mirror node client error when calling write function

### ISSUE THREAD

**Issue by kabaluyot** [hashgraph/hedera-json-rpc-relay#1707]
### Description

Recently this error is happening when invoking a write smart contract function. We are using our own node (w/ commit cf48856a9957712d7cdced47e6812663aeaf94d7 latest master) but issue happens in prior version.

The error is very generic too to inspect.

### Steps to reproduce

1. Call a write smart contract function
2. Logs says error 400 from mirrorNodeClient.js

### Additional context

(from own node logs)
![image](https://github.com/hashgraph/hedera-json-rpc-relay/assets/38805756/9cea2603-edc2-44e3-8cb1-e57743fba74b)

(client side)
<img width="1212" alt="Screen Shot 2023-09-03 at 9 05 27 PM" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/38805756/ad64ca25-1e77-47aa-9896-ecc273f30454">

### Hedera network

testnet

### Version

latest master (cf48856a9957712d7cdced47e6812663aeaf94d7)

### Operating system

None

**Comment by kabaluyot** [comment]
Hi @Nana-EC , will double check again. Was working previously (and we did not change anything) but somehow testing it again in the past days is now  returning errors

**Comment by Nana-EC** [comment]
> Hi @Nana-EC , will double check again. Was working previously (and we did not change anything) but somehow testing it again in the past days is now  returning errors

We'll also double check. HIP 584 is still in development on the mirror node so we'll verify there weren't any regressions.

Thanks

**Comment by kabaluyot** [comment]
An update that this has nothing to do with our EIP712 implementation. A sample transaction that went through is here: https://hashscan.io/testnet/tx/0x9fd74d5a0eefd271cfb1529d2efbd710ef5b3d132163bda5ef2cc205919a68fa

Also we notice that when we hardcode the gas limit to around, say 800,000 instead of letting metamask estimate the gas limit, there is a 50-50 chance the transaction will went through.

**Comment by ebadiere** [comment]
@kabaluyot I am not seeing this behavior.  Can you attach a version of the contract with the function you are calling to trigger this?
