### ISSUE TITLE
eth_getTransactionReceipt `effectiveGasPrice` field right populate instead of `0x0`

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#1736]
### Problem

when using method `eth_getTransactionReceipt` for synthetic transactions (HTS), Contract Create or Contract Call, the field `effectiveGasPrice` on the response is always set to false instead of the appropriate `gasPrice` at the time of the transaction.

### Solution

gasPrice is fixed at exchange rate and is updated each hour. is possible to see the `priceGas` at the time of the transaction using the mirror node:

**for tx hash:** `0xa8795e383e7ee5b138e61f5da7b0d85664e6feec3f2e5e24385f2ff265c401d3`

**timestamp is:** `1694561311.909203003`

**and gasPrice fee is:** `71` (this will need some conversion to hex and wei format)

```
https://previewnet.mirrornode.hedera.com/api/v1/contracts/results/0xa8795e383e7ee5b138e61f5da7b0d85664e6feec3f2e5e24385f2ff265c401d3?nonce=1

https://previewnet.mirrornode.hedera.com/api/v1/network/fees?order=desc&timestamp=1694561311.909203003

```

**Response:**

```
{
  "fees": [
    {
      "gas": 71,
      "transaction_type": "EthereumTransaction"
    },
    {
      "gas": 71,
      "transaction_type": "ContractCreate"
    },
    {
      "gas": 71,
      "transaction_type": "ContractCall"
    }
  ],
  "timestamp": "1692903147.842862003"
}
```

**Comment by Nana-EC** [comment]
@stefan-stefanooov can this be closed?
If so please link to the right PR and close
