### ISSUE TITLE
JsonRpcProvider failed to detect network and cannot start up

### ISSUE THREAD

**Issue by iron4548** [hashgraph/hedera-json-rpc-relay#1802]
### Description

```typescript

import * as ethers from 'ethers'; //ethers.js 6.7.3

async function main() {
  try {
    const networkId = 'testnet';
    const provider = new ethers.JsonRpcProvider(`https://${networkId}.hashio.io/api`);
        
    const network = await provider.getNetwork();
    console.log(network);

    const blockNumber = await provider.getBlockNumber();
    console.log(blockNumber);

  }
  catch (err:unknown) {
    console.warn(err);
  }
}
main();
```

For console.log(network) I got:

`Network {#name: 'unknown', #chainId: 296n, #plugins: Map(0)}`

The chainId is correct for testnet.

However provider.getBlockNumber() resulted in an error:

```
"JsonRpcProvider failed to detect network and cannot start up"
"Error: server response 400 Bad Request"
```

Any idea why?

### Steps to reproduce

package.json

```json
{
  "name": "ethersTest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "tsc",
    "lint": "eslint 'src/**/*.{ts,tsx}'",
    "start": "node dist/index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^20.7.2",
    "@typescript-eslint/eslint-plugin": "^6.7.3",
    "@typescript-eslint/parser": "^6.7.3",
    "dotenv": "^16.3.1",
    "eslint": "^8.50.0",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "ethers": "^6.7.1"
  }
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "CommonJS",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "sourceMap":true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "dist"
  },
  "paths": {
    "*": ["node_modules/*", "src/types/*"]
  },
  "include": ["src"]
}
```
Run `npm i`

Add to \src\index.ts

```typescript
import * as ethers from 'ethers'; //ethers.js 6.7.3

async function main() {
  try {
    const networkId = 'testnet';
    const provider = new ethers.JsonRpcProvider(`https://${networkId}.hashio.io/api`);
        
    const network = await provider.getNetwork();
    console.log(network);

    const blockNumber = await provider.getBlockNumber();
    console.log(blockNumber);

  }
  catch (err:unknown) {
    console.warn(err);
  }
}
main();
```

Run it.

### Hedera network

testnet

### Version

hashio testnet live

### Operating system

None

**Comment by Nana-EC** [comment]
Thanks @iron4548 ,
We'll take a look into this

**Comment by Neurone** [comment]
Hi @iron4548, that is not a bug; the problem is that ethers v6 enables batch requests by default ([max 100 at the same time](https://docs.ethers.org/v6/api/providers/jsonrpc/#JsonRpcApiProviderOptions)), and the JSON-RPC Relay does not support batch requests. 

To solve the issue, you can configure the `JsonRpcProvider` to serve a single eth method per request:

```JavaScript
    const provider = new ethers.JsonRpcProvider(
      `https://${networkId}.hashio.io/api`,
      "",
      {
        batchMaxCount: 1,
      }
    );
```

Please note using ethers v5 there is a clear distinction between an explicit batch-enabled rpcProvider ([`JsonRpcBatchProvider`](https://docs.ethers.org/v5/api/providers/other/#JsonRpcBatchProvider)) and a normal one ([`UrlJsonRpcProvider`](https://docs.ethers.org/v5/api/providers/other/#UrlJsonRpcProvider)), so you don't face that issue on ethers.js < 6.

**Comment by Neurone** [comment]
For the record, related to #476

**Comment by iron4548** [comment]
Thanks @Neurone, setting the batchMaxCount to 1 did indeed resolve my issue. I was using ethers.js for the first time (so installed the latest which was v6) so I wasn't aware that batch request was an option, and that 400 error message wasn't that entirely helpful. Good to know about this now.

Thanks again!
