### ISSUE TITLE
Both block.difficulty and block.prevrandao result in a contract call exception.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#1806]
### Description

The following solidity snippet causes a call exception:
```
    function getBlockPrevrando() external view returns (uint256) {
        return block.prevrandao;
    }
```
block.difficulty or block.prevrandao can be used by solidity developers to generate good enough randomness until we get a chainlink integrate which will allow VRF.  This should be supported.

### Steps to reproduce

The solidity smart contracts test BlockInfo test, 'should get the current block prevrandao using block.prevrandao' will reproduce this.

### Hedera network

other

### Version

v0.33.0

### Operating system

macOS

**Comment by Nana-EC** [comment]
I believe this issue was resolved with https://github.com/hashgraph/hedera-mirror-node/issues/7036.
We should confirm and update https://github.com/hashgraph/hedera-smart-contracts/blob/main/test/solidity/block/BlockInfo.js#L62

**Comment by ebadiere** [comment]
No longer an issue and covered by issue #721 in smart contracts.
