### ISSUE TITLE
Intermittent fails during transfer

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#1821]
### Description

We are experiencing intermittent fails on tests specifically with transfers, one example is the dapp-tests here and also some tests in the hedera-smart-contracts CI . Example run https://github.com/hashgraph/hedera-smart-contracts/actions/runs/6505271799/job/17668771202

More info can be found here: https://github.com/hashgraph/hedera-local-node/issues/294

### Steps to reproduce

1. Run the CI and see how it fails and try to reproduce it locally to find the issue

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by Nana-EC** [comment]
@georgi-l95 is this still occurring or can this be closed?
