### ISSUE TITLE
Batch Request - WebSockets

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#1879]
### Problem

WebSockets needs to support batch requests.

### Solution

Implement Batch Request for WS according to Design Doc.

Should Include AcceptanceTests

https://github.com/hashgraph/hedera-json-rpc-relay/pull/1877

**Comment by quiet-node** [comment]
closed as the feature was implemented in this PR https://github.com/hashgraph/hedera-json-rpc-relay/pull/2475
