### ISSUE TITLE
getTransactionReceipt returns revertReason

### ISSUE THREAD

**Issue by konstantinabl** [hashgraph/hedera-json-rpc-relay#1912]
### Description

The eth_getTransactionReceipt endpoint returns revertReason field. This field should not be returned according to the ethereum specs

### Steps to reproduce

1. Make request to eth_getTransactionReceipt

### Additional context
![Screenshot 2023-11-21 at 15 41 58](https://github.com/hashgraph/hedera-json-rpc-relay/assets/42917570/7b1326a9-8698-4f2e-9ece-8820532a450b)

### Hedera network

other

### Version

0.32.0

### Operating system

None

**Comment by ebadiere** [comment]
Could not reproduce.  No longer happening.  I ran the following on a transaction that reverted on testnet:
```
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_getTransactionReceipt",
  "params": [
    "0x3bca9df3973bae9f222b40b45d2840b03748591344d5185513ffdf238988e7d6"
  ]
}
```
