### ISSUE TITLE
getTransactionReceipt should return a revert reason on contract revert errors.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#1916]
### Description

Currently the relay is not surfacing the contract revert reason.  This needs to be returned to give the user an idea of what went wrong. Revert reasons are not correctly being returned in the relay

### Steps to reproduce

The new TokenVault `Should fail if withdraw is zero` currently validates the transaction data string, because there is no revert reason.  The correct hardhat validation is commented out.  Once this is fixed the commented out line should pass.

### Hedera network

other

### Version

v0.36.0

### Operating system

macOS

**Comment by georgi-l95** [comment]
Here's the docs: https://ethereum.github.io/execution-apis/api-documentation/

**Comment by AlfredoG87** [comment]
Closing this since is not needed.

DEV_MODE was already removed.
