### ISSUE TITLE
For 0.36 npm run biuild failed 

### ISSUE THREAD

**Issue by stanta** [hashgraph/hedera-json-rpc-relay#1922]
### Description

Got error when npm build
       node_modules/@hashgraph/sdk/lib/topic/TopicUpdateTransaction.d.ts(174,52): error TS2304: Cannot find name 'Long'.
       src/lib/clients/sdkClient.ts(150,21): error TS2304: Cannot find name 'Long'.
       src/lib/clients/sdkClient.ts(151,21): error TS2304: Cannot find name 'Long'.
       src/lib/eth.ts(660,25): error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number | bigint | BigNumber'.
         Type 'undefined' is not assignable to type 'number | bigint | BigNumber'.
       Waiting for the debugger to disconnect...
        ELIFECYCLE  Command failed with exit code 1.

### Steps to reproduce

git pull from   hedera-json-rpc-relay 0.36
rin npm i 
run  npm build, 
 
 got that "Cannot find name 'Long'."  errors

### Additional context

Need to add "@types/long" in package.json

### Hedera network

testnet

### Version

0.36

### Operating system

Linux
```[tasklist]
### Tasks
```

**Comment by Nana-EC** [comment]
Hi @stanta, Thanks for opening this ticket.
We resolved this shortly after but do let us know if you experience any other issues building.
Thanks
