### ISSUE TITLE
Precompute contract address on ethers deployment

### ISSUE THREAD

**Issue by natanasow** [hashgraph/hedera-json-rpc-relay#193]
### Description

On contract deployment, most of the tools pre-compute the contract address on the client-side, based on `sender address` and `nonce`. In the Hedera ecosystem, it's not like that, where it's just the next available id. 

[https://docs.ethers.io/v5/api/utils/address/#utils--contract-addresses](
https://docs.ethers.io/v5/api/utils/address/#utils--contract-addresses)
```
ethers.utils.getContractAddress( transaction )
from + nonce
 ```
In the end, the contract deployment is not 100% compatible with the Ethereum workflow.

### Steps to reproduce

Deploy a contract with an ECDSA account and alias.

### Hedera network

other

### Version

v0.1.0

**Comment by Daniel-K-Ivanov** [comment]
This issue cannot be resolved from our side. Unless a change is introduced in ethers, there is no workaround. My suggestion is to **explicitly** state in the developer documentation of the relay that this is one of the **incompatibilities** with existing web3 tooling. That being said, I do think that we might not have this issue with truffle/web3js

**Comment by Nana-EC** [comment]
@Daniel-K-Ivanov let's spend some time on this and see what work around may be possible and what the final solution should be

- Workaround add documentation to the etherjs tool dir with code snippet and workaround e.g [reinitialization](https://github.com/hashgraph/hedera-json-rpc-relay/blob/a66f3df3ba66418151546e310d11d270721ea917/packages/server/tests/acceptance/erc20.spec.ts#L339 )
- Final solution. Explore PR on etherjs or open a local ticket with described fix steps
