### ISSUE TITLE
proj: upgrade koa (major version)

### ISSUE THREAD

**Issue by bguiz** [hashgraph/hedera-json-rpc-relay#2064]
### Problem

When performing a fresh `npm install`, the following is output:

```text
npm WARN deprecated koa-router@10.1.1: **IMPORTANT 10x+ PERFORMANCE UPGRADE**: Please upgrade to v12.0.1+ as we have fixed an issue with debuglog causing 10x slower router benchmark performance, see https://github.com/koajs/router/pull/173
```

... and that perf upgrade looks like it might be worth getting!

### Solution

 Refactor to use new major version of Koa.

**Comment by AlfredoG87** [comment]
@bguiz, thank you for the recommendation 👍
