### ISSUE TITLE
fix: discrepancy between `eth_getTransactionCount` RPC values post-Testnet reset

### ISSUE THREAD

**Issue by bguiz** [hashgraph/hedera-json-rpc-relay#2074]
## What

- Using the same set of EVM accounts (generated from BIP-39 seed phrase) before and after the reset

## Why

Dropping down into RPC requests, appears to yields some clues as to why this might be happening:

- `eth_getTransactionCount(address, 'latest')` returns a low number (`0` before sending my first transaction after the reset)
- `eth_getTransactionCount(address, 'pending')` returns a high number (`140` in my case, which probably was the nonce prior to the reset)

So it is apparent that metamask (correctly) uses the `pending` value instead of the `latest` value... but the question is why the `pending` value seems to be stuck at this value, even after the reset. unknown what the underlying reason it being stuck is - is it caching within Metamask, or caching within RPC relay, or is the value being returned from Hedera nodes?

### Steps to reproduce

Before Testnet reset:

- in Metamask settings, enable the option for custom nonce
- in a DApp client connect using an EVM account (ECDSA with simple key) in MetaMask
- trigger something in the DApp that would ask you to sign and submit a transaction
- nonce appears *correctly*
- submitting the transaction with the pre-filled nonce value works

After Testnet reset:

- in Metamask settings, enable the option for custom nonce
- in a DApp client connect using the *same* EVM account  as before in MetaMask
- trigger something in the DApp that would ask you to sign and submit a transaction
- nonce appears *incorrectly*
- submitting the transaction with the pre-filled none value *does not* work, RPC errors saying that the nonce is incorrect
- submitting the transaction after overriding the pre-filled nonce value with the known-to-be-correct value (obtain this using `eth_getTransactionCount(address, 'latest')` works

### Hedera network

testnet

### Version

0.41.0-SNAPSHOT c288615a33e08dfa172df7754aa764bad12eeb71

### Operating system

macOS

**Comment by AlfredoG87** [comment]
I was able to experience the issue with MM, but indeed is the nonce you had previous to the reset, seems  like MM is using a cache out of its history.

You need to clear your data, go to:
Settings --> Advanced --> Clear activity tab data. 

![image](https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/b42efb48-1fa2-410f-b969-65fa382b3bdf)

I have done many combinations of tests and I haven't been able to replicate the issue afterward
This will solve your issue

**Comment by bguiz** [comment]
thanks - that worked!
