### ISSUE TITLE
Investigate potential DevEx issue

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hedera-json-rpc-relay#209]
**Problem**
Currently we do not have all the necessary pre-checks mapped 1-1 with what a normal RPC will behave. Some of the checks are executed at consensus time, which means that the relay will be returning a "success" response code out of the `sendRawTransaction` call.

Investigate what happens to the client-side applications in the case in which the transaction fails at consensus time that would otherwise fail on precheck (f.e balance is not sufficient for gas cost, gas limit to low etc. Prechecks are listed in #102 )

**Solution**
The output of this issue is expected to be a description on what happens on client side and will be used to asses how "important" is the addition/implementation of those prechecks.

**Comment by Nana-EC** [comment]
We aligned checks.
Relay now utilizes precheck.ts to cover some sanity transaction checks prior to submission.
Success is only returned once a transaction has gone E2E
