### ISSUE TITLE
Research: Increase calldata limit on `eth_estimateGas`

### ISSUE THREAD

**Issue by bibitibooo1** [hashgraph/hedera-json-rpc-relay#2105]
### Problem
There are some cases where calling eth_estimateGas with calldata more than 24KB fails in the archive node. This is due to limitation, which is far larger in the etereum world. Becase of this reason, in some scenarios call is failing.

### User Stories

1. As a user, I'd like to be able to deploy a factory contract, which accepts init bytocode for another contract as parameter. This fails, if the bytecode is larger than 24KB

**Comment by Nana-EC** [comment]
@isavov we bumped to 25kb https://github.com/hashgraph/hedera-mirror-node/pull/7795, do you know if this issue is resolved or does the scenario require a higher limit.
If so what size in kb?
