### ISSUE TITLE
Support Historical Blocks eth_call request on the Relay

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-json-rpc-relay#2119]
### Description

After the implementation of Historical Block Support on the mirror node, `eth_call` request should be able to support it using the Relay, however that is not the actual case.

### Steps to reproduce

It should return 0 balance:

```
{
    "id": "2",
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
            "to": "0x0000000000000000000000000000000000365d39",
            "data": "0x70a082310000000000000000000000000000000000000000000000000000000000365d3a"
        },
        "0x9AB78"
    ]
}
```

instead returns "latest" balance:

```
{
    "result": "0x0000000000000000000000000000000000000000000000000000000000002350",
    "jsonrpc": "2.0",
    "id": "2"
}
```

it should return 0x since SC does not exists:

```
{
    "id": "2",
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
            "to": "0x0000000000000000000000000000000000365d39",
            "data": "0x70a082310000000000000000000000000000000000000000000000000000000000365d3a"
        },
        "0x9AB10"
    ]
}
```

Returns the same as latest.

### Additional context

If querying the mirror node directly it works:

the following eth_call data was encoded using an ERC20 ABI, using `balanceOf` method for address para: `0x0000000000000000000000000000000000365d3a`

**token address:** `0x0000000000000000000000000000000000365d39`
**When Smart Contract Exists and Address has Balance:**

```
curl --location 'https://testnet.mirrornode.hedera.com/api/v1/contracts/call' \
--header 'Content-Type: application/json' \
--data '{
    "to": "0x0000000000000000000000000000000000365d39",
    "data": "0x70a082310000000000000000000000000000000000000000000000000000000000365d3a",
    "estimate": false,
    "block": "0x9AB79"
}

```

**When SC Exists but address does NOT have a Balance:**
```
curl --location 'https://testnet.mirrornode.hedera.com/api/v1/contracts/call' \
--header 'Content-Type: application/json' \
--data '{
    "to": "0x0000000000000000000000000000000000365d39",
    "data": "0x70a082310000000000000000000000000000000000000000000000000000000000365d3a",
    "estimate": false,
    "block": "0x9AB78"
}
```

**When SC Does not exists:**
```
curl --location 'https://testnet.mirrornode.hedera.com/api/v1/contracts/call' \
--header 'Content-Type: application/json' \
--data '{
    "to": "0x0000000000000000000000000000000000365d39",
    "data": "0x70a082310000000000000000000000000000000000000000000000000000000000365d3a",
    "estimate": false,
    "block": "0x9AB10"
}
'
```

### Hedera network

mainnet, testnet, previewnet, other

### Version

v0.41.0

### Operating system

None

**Comment by AlfredoG87** [comment]
https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L1495-L1518

**Comment by Nana-EC** [comment]
@AlfredoG87 miror node is currently updating to support 0.46 on the web3 module.
I imagine some of this may be resolved by that. Especially the invalid address items.
Might want to track those changes and then retest
