### ISSUE TITLE
Leading zeros for hex causes incompatibility with common utility packages 

### ISSUE THREAD

**Issue by simsonraj** [hashgraph/hedera-json-rpc-relay#2174]
### Problem

The JSON RPC responses sometimes return gas values in Hex with leading zeros making it hard to use common utility packages such as https://pkg.go.dev/github.com/ethereum/go-ethereum/common/hexutil 
For example response from `eth_estimateGas` method

```
{
    "result": "0x0000000000006050",
    "jsonrpc": "2.0",
    "id": 1
}
```

### Solution

- Trim the leading zeros

**Comment by Nana-EC** [comment]
@simsonraj thanks for this.
We'll take a look into this to support your flow.

Beyond go-ethereum are you experiencing this on other tools?
web3js, etherjs, hardhat, truffle, foundry, the graph and many other tools don't hit this issue so it'd be great to know what other common utility packages you're noting.

**Comment by simsonraj** [comment]
The main core node is written in golang & uses go-ethereum to a certain extent, we rely on it, but haven't tested other libraries, there may be other tools or scripts using the other libraries
