### ISSUE TITLE
go-Ethereum tool fails on missing transaction fields

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#2202]
### Description

when we try to call eth_getBlockByNumber and pass specific block, which has transactions. More specifically issue is when at least one of those transactions are externalised log from precompile call. Because they miss some fields like maxPriorityFeePerGas,r,s,v and type → go-ethereum does not except null for those fields. All other cases are working.

### Steps to reproduce

Make a call to `eth_getBlockByNumber` including transactions that are the result of ContractCall .
Confirm that no failure occurs

### Hedera network

other

### Version

v0.43.0

### Operating system

None

**Comment by quiet-node** [comment]
Seems like the issue is no longer produced. There are [UTs](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/server/tests/acceptance/rpc_batch1.spec.ts#L456) for this in the repo. The UT taps on a block that has an array of transactions that have null fields like below yet still be able to finish the request. 
```bash
transactions: [
    {
      blockHash: '0x021f8fc0e1ecbf4882a01c8fd612e4596faa1a0c2c2586c3b5846218084a14eb',
      blockNumber: '0x21d',
      chainId: null,
      from: '0x2bd1ab5190d25e2cee2a6e7ab040659f2442502f',
      gas: '0x11383',
      gasPrice: null,
      hash: '0xa58edbdcb7eea68351b27ef4d0ed351e9ce675ed05d0682e5b3fe9097d38dfbb',
      input: '0x',
      nonce: '0x0',
      r: null,
      s: null,
      to: '0x0000000000000000000000000000000000000417',
      transactionIndex: '0x4',
      type: null,
      v: null,
      value: '0x5f5e100'
    },
    {
      blockHash: '0x021f8fc0e1ecbf4882a01c8fd612e4596faa1a0c2c2586c3b5846218084a14eb',
      blockNumber: '0x21d',
      chainId: null,
      from: '0x2bd1ab5190d25e2cee2a6e7ab040659f2442502f',
      gas: '0xea60',
      gasPrice: null,
      hash: '0x84c15b51981dab6c8b4ba183754990e1e68b45752f137291e57f51bf86431992',
      input: '0x0419eca50000000000000000000000000000000000000000000000000000000000000001',
      nonce: '0x0',
      r: null,
      s: null,
      to: '0x0000000000000000000000000000000000000417',
      transactionIndex: '0xb',
      type: null,
      v: null,
      value: '0x0'
    }
  ],
  ```
  
 
Just to confirm it also works with blocks that have type 2 transactions 
  ```bash
curl --location 'https://testnet.hashio.io/api' \
--header 'Content-Type: application/json' \
--data '

{ "jsonrpc":"2.0", "method":"eth_getBlockByNumber", "params":[ "0x7AD23",  true ], "id":1 }'
```
