### ISSUE TITLE
eth_getTransactionReceipt go-ethereum compatibility

### ISSUE THREAD

**Issue by rafaelkallis** [hashgraph/hedera-json-rpc-relay#226]
### Problem

We are facing a similar situation as in #149 , but for `eth_getTransactionReceipt`. Specifically there is a schema disagreement over `log.transactionHash` between the ethereum execution apis and go-ethereum. 

The ethereum execution apis do not mark that property as required https://github.com/ethereum/execution-apis/blob/main/src/schemas/receipt.json#L18.

The go-ethereum client however does mark that property as required https://github.com/ethereum/go-ethereum/blob/master/core/types/log.go#L45.

Would be great if we can include the transactionHash inside logs so that we satisfy the go-ethereum validation.

### Solution

The logs are mapped here on the relay node: 
https://github.com/hashgraph/hedera-json-rpc-relay/blob/84fffedc5f9cbe9ef449724857e01a12100dbfab/packages/relay/src/lib/eth.ts#L701-L716

```js
const logs = receiptResponse.logs.map(log => ({ ...log, transactionHash: receiptResponse.hash}));
```

**Comment by shemnon** [comment]
Can you post this finding to https://github.com/ethereum/execution-apis/issues?  This part in particular

> Specifically there is a schema disagreement over log.transactionHash between the ethereum execution apis and go-ethereum.
> 
> The ethereum execution apis do not mark that property as required https://github.com/ethereum/execution-apis/blob/main/src/schemas/receipt.json#L18.
> 
> The go-ethereum client however does mark that property as required https://github.com/ethereum/go-ethereum/blob/master/core/types/log.go#L45.

The core devs either need to make it required or geth needs to come into compliance.  Either outcome is acceptable to me.  But we should add it on our end.

**Comment by rafaelkallis** [comment]
reference https://github.com/ethereum/execution-apis/pull/240
