### ISSUE TITLE
WS socket repetitively responds with null responses when subcribed

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-json-rpc-relay#2359]
### Description

WS socket repetitively responds with null responses when subcribed

### Steps to reproduce

1. Run WS server
2. Connect to WS server
3. Observe null responses

### Hedera network

mainnet, testnet, previewnet, other

### Version

latest

### Operating system

None

**Comment by simsonraj** [comment]
With WS responses through code, we get null responses & that breaks the flows
Attached is a sample response for eth_getTransactionCount
![image (1)](https://github.com/hashgraph/hedera-json-rpc-relay/assets/5087697/a52c4722-0b34-454f-8e20-8c4f7f7486a6)
