### ISSUE TITLE
newHeads subscription now returns `Unsupported JSON-RPC method` 

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-json-rpc-relay#2360]
### Description

Looks like this PR https://github.com/hashgraph/hedera-json-rpc-relay/pull/2351 seems to break the support for newHeads by altering the utilization of the process.env.WS_NEW_HEADS_ENABLED env variable.

### Steps to reproduce

fix the logic of process.env.WS_NEW_HEADS_ENABLED

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by Nana-EC** [comment]
@quiet-node to confirm if this should be resolved

**Comment by quiet-node** [comment]
This PR https://github.com/hashgraph/hedera-json-rpc-relay/pull/2361 has resolved this issue.
