### ISSUE TITLE
WS connection and messages limit improvements

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-json-rpc-relay#2367]
### Problem

Currently, the WS server relies on environment variables `WS_CONNECTION_LIMIT` and `WS_CONNECTION_LIMIT_PER_IP` to determine the maximum amount of connections that can subscribe to the websocket. The fallback value is 10, which means if the env vars are not configured, the WS server only accepts max 10 connections from either multiple client machines or from 1 client machine (signle IP address). 

The second issue is that currently, there's no limit configured for methods sent to the server.

### Solution

Increase the fallback value for the connection limit
- WS_CONNECTION_LIMIT = TBD (currently 10)
- WS_CONNECTION_LIMIT_PER_IP = TBD (currently 10)
- WS_METHOD_REQUEST_LIMIT_PER_IP = TBD

**Comment by victor-yanev** [comment]
Blocked by #2801

**Comment by quiet-node** [comment]
I synced with @nadezhdapopovaa offline regarding `WS_METHOD_REQUEST_LIMIT_PER_IP` and learned that the WS server already rate limits IP addresses for methods by using the same rate limit class as the HTTP server (i.e., rateLimit.shouldRateLimit). Therefore, `WS_METHOD_REQUEST_LIMIT_PER_IP` is unnecessary, and we can remove it.

**Comment by quiet-node** [comment]
WS_CONNECTION_LIMIT and WS_CONNECTION_LIMIT_PER_IP have been set to 300 based on the result from the stress test performed by @nadezhdapopovaa. Thanks for the effort! 

Closing as completed.
