### ISSUE TITLE
Server reporting missing result or error claims

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#237]
### Description

The server seems to be reporting errors on
```
Error: Missing result or error
      at module.exports (/home/node/app/node_modules/koa-jsonrpc/lib/RpcResponse.js:24:11)
      at /home/node/app/node_modules/koa-jsonrpc/index.js:62:18
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Seems to be non fatal but let's get ahead of it

### Steps to reproduce

1. Run server in k8s cluster

### Hedera network

previewnet

### Version

v0.2.0-SNAPSHOT

**Comment by natanasow** [comment]
@Nana-EC Can't reproduce it. Could you provide more details about the bug or put it on hold till the next appearance?
