### ISSUE TITLE
"Error raised during getCode for address null" is not returned in the response to the client and can cause confusion.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#2376]
### Description

"Unknown error invoking RPC" is returned to the client when in the logs we see "Error raised during getCode for address null".     The "address is null" message should be returned to the client to give the user an idea of what is going on.

### Steps to reproduce

1. Run `eth_getCode` with a null address value.

### Hedera network

mainnet

### Version

v0.45.2

### Operating system

Linux

**Comment by Nana-EC** [comment]
@quiet-node please add info based on your observation
