### ISSUE TITLE
feat(cancun): Cancun should be tested E2E from the relay POV

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-json-rpc-relay#2391]
With the Cancun upgrade (targeted: services 0.50) there should be end-to-end tests of (some of the) Cancun functionality from the relay POV.

Obviously Ethereum type 3 transactions (containing "blobs") need to be rejected as mentioned in #2390 .

But there could also be tests that Cancun functionality can be used:  E.g., a contract using transient storage will work (instead of fail with invalid opcode).  

See HIPs [865](https://hips.hedera.com/hip/hip-865), [866](https://hips.hedera.com/hip/hip-866), [867](https://hips.hedera.com/hip/hip-867), and [868](https://hips.hedera.com/hip/hip-866) for the scope of Cancun.

See related issue [#725](https://github.com/hashgraph/hedera-smart-contracts/issues/725) in the smart contracts repo.

**Comment by georgi-l95** [comment]
Implementation details around rejecting type 3 transactions are ready, everything else is already included in the services. This is all tested from Relay POV in the smart contracts repo. Adding additional e2e test here to do the same thing will only make it harder for us to maintain them.
