### ISSUE TITLE
Add documentation on opcodeLogger

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#2433]
With the implementation of fully working `opcodeLogger` on `debug_traceTransaction` endpoint. It would be ideal, if we can document why is used, how to be used with the most popular tools using relay and local node.

**Comment by Nana-EC** [comment]
Resolved with this https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/docs/debugging-transactions.md
