### ISSUE TITLE
Increase batch request limit

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#2437]
Currently by default ethers and other libraries are using batch requests by default to receive information by sending `eth_chainId`, `eth_blockNumber` and more in one batch. However we are rate limiting and counting this as a single request towards tier one (similar to `eth_sendRawTransaction`). We should split up those requests and count them to their respective tiers. Otherwise, we might degrade the performance of tools using the relay.
As we can't force users to turn off batching, we need to properly limit it.

**Comment by Nana-EC** [comment]
What limit should this be increased to based on observance?

**Comment by georgi-l95** [comment]
By default ethers(for example) sends batch requests for queries like eth_chainId, eth_blockNumber and more. This can be turned off, when new provider is initialized, however most users won't.
So we either want to increase the limit or make it in tiers based on each request in the batch. Otherwise, even one users with avarage usage will hit the limit.
