### ISSUE TITLE
Accept the requests with both "data" & "input" fields, ignore the extra parameter instead of throwing error

### ISSUE THREAD

**Issue by simsonraj** [hashgraph/hedera-json-rpc-relay#2547]
### Problem

When we try to send a request with both the Input & data fields, it errors out, we do this in order to work with some chains/client which accept only Input or only Data, but they ignore the other one, instead of throwing an error

```{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "eth_call",
    "params": [
        {
            "from": "0x51E3B84966c042C278dEb61564C106B6b82aF792",
            "input": "0x7cb9357e",
            "data": "0x7cb9357e",
            "to": "0x1f35616377069168ce06dD4b36ab8A47A36Ad92f"
        },
        "latest"
    ]
}```

### Solution

- Accept requests with both fields
- Ignore the extra param

### Alternatives

_No response_

**Comment by quiet-node** [comment]
Quick question, which attributes do we take in if both `input` and `data` are present but `different values`?

**Comment by simsonraj** [comment]
The current standard is "input" https://github.com/ethereum/execution-apis/blob/main/tests/eth_call/call-contract.io
but some clients still use "Data", so if "input" is not present, we should consider the "Data" field, if both are present, it should be "input"

**Comment by quiet-node** [comment]
Gotcha thanks for the quick reply!
