### ISSUE TITLE
eth_newFilter errors out when passing more than 1 address in the parameter

### ISSUE THREAD

**Issue by simsonraj** [hashgraph/hedera-json-rpc-relay#2548]
### Description

This request in websocket errors out with "Invalid request", with HTTP it responds with "method not found"
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "eth_newFilter",
    "params": [
        {
            "fromBlock": "0x473EE5",
            "toBlock": "latest",
            "address": [
                "0x2bfe6dd9585d25c5b00308f21e1b09e91604a082",
                "0xf3cb5ee98c1e60f60d99da7c240fdc0ab7668bfd"
            ],
            "topics": [
                "0x0559884fd3a460db3073b7fc896cc77986f16e378210ded43186175bf646fc5f"
            ],
        }
    ]
}```

### Steps to reproduce

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "eth_newFilter",
    "params": [
        {
            "fromBlock": "0x473EE5",
            "toBlock": "latest",
            "address": [
                "0x2bfe6dd9585d25c5b00308f21e1b09e91604a082",
                "0xf3cb5ee98c1e60f60d99da7c240fdc0ab7668bfd"
            ],
            "topics": [
                "0x0559884fd3a460db3073b7fc896cc77986f16e378210ded43186175bf646fc5f"
            ],
        }
    ]
}```

### Hedera network

testnet

### Version

v0.48.1

### Operating system

None

**Comment by quiet-node** [comment]
So eth_newFilter is being implemented in WS server in this PR https://github.com/hashgraph/hedera-json-rpc-relay/pull/2553.

For HTTP, when I tried the exact above request against testnet and got 
```bash
{
    "error": {
        "code": -32000,
        "name": "Block range too large",
        "message": "[Request ID: 6a9d84af-7462-4817-bae0-411608b7a7d2] Exceeded maximum block range: 1000"
    },
    "jsonrpc": "2.0",
    "id": "1"
}
``` 
instead of `method not found`. Could you please tell me how you got `method not found`?
