### ISSUE TITLE
eth_getBlockByNumber failing with Error invoking RPC: Null entity ID

### ISSUE THREAD

**Issue by aaron-cottrell-vc** [hashgraph/hedera-json-rpc-relay#2557]
### Description

One of our customers reported an issue with block `0x484e45` and a bunch of others on testnet failing when queried by RPC using the `eth_getBlockByNumber` method.

We have confirmed this on our node and also the hashio public endpoint.

It seems the block in questions had a failed ethereum transaction but we weren't expecting it to crash the whole request, explorer link: https://hashscan.io/testnet/block/4738629

### Steps to reproduce

1) Make example request

`curl --request POST \
  --url https://testnet.hashio.io/api \
  --header 'Content-Type: application/json' \
  --data '{
        "jsonrpc": "2.0",
        "method": "eth_getBlockByNumber",
        "params": [
                "0x484e45",
                false
        ],
        "id": "73"
}'`

2) See example response with error

`{"error":{"code":-32603,"name":"Internal error","message":"[Request ID: b36ce3a7-d69b-4414-a137-81c1cf6acae7] Error invoking RPC: Null entity ID"},"jsonrpc":"2.0","id":"73"}%`

Expected result was to return information about that block.

### Additional context

Other blocks with issues reported to us:
4738858, 4738933, 4739048, 4707219, 4707253, 4707483, 4706754, 4706828.

### Hedera network

testnet

### Version

v0.48.0

### Operating system

None

**Comment by quiet-node** [comment]
blocking by https://github.com/hashgraph/hedera-mirror-node/issues/8430

**Comment by kevin-matthews-vc** [comment]
Hi, as the ticket this was blocked by is now completed, is this ready to make it to the next release? and if so, do you know when that release will happen? Thanks

**Comment by quiet-node** [comment]
Hello @kevin-matthews-vc and @aaron-cottrell-vc, mirror-node@v0.107.0 is now live on previewnet and testnet. With that said, this problem has also been resolved. Let us know if there's anything else we can help with! Thanks for your time!
