### ISSUE TITLE
Allow Hardhat to deploy smart contracts

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-json-rpc-relay#259]
### Problem

Currently, users will get `Internal error` when using Hardhat to deploy a smart contract. The transaction contains `INVALID_SOLIDITY_ADDRESS` error as shown in https://hashscan.io/#/testnet/transaction/0.0.46030734-1655918065-252797715?t=1655918078.085442000

Please feel free to use the following script to reproduce the problem
https://github.com/pathornteng/hedera-hardhat

Note: I can use Truffle to deploy a smart contract to Hedera network just fine.

### Solution

Hardhat might be using different formats or values. Further investigation is required.

**Comment by Nana-EC** [comment]
Likely related to #193 
Let's investigate why truffle works fine, does it just not check for a valid contract id?

**Comment by pathornteng** [comment]
@natanasow You are right. I removed the console.log and it works! 

Thanks for the answer :)
