### ISSUE TITLE
release 0.51

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#2642]
### Problem

Features for 0.51 are not yet deployed.

### Solution

**Manual release process:**

- [x] Create a release/0.51 branch off of main. Ensure github test actions run. Merge Against `release/0.51` branch
- [x]  Bump Snapshot to 0.52.0-SNAPSHOT branch off of main. Merge against Main
- [x] Tag as v0.51.0-rc2
     - [x] git tag
     - [x] Confirm new docker image version is deployed
     - [x] Deploy Version
     - [x] Finished Testing (Manual, Newman, Dapp, Acceptance)
- [x] Review and update dependencies
     - [x] @hashgraph/hedera-local 
     - [x] @hashgraph/sdk
- [x] Previewnet Testing
     - [x] Deploy tagged version
     - [x] Manual testing
     - [x] Run newman tests
     - [x] Run Dapp Example Bootstrap and manual tests
     - [x] Run acceptance tests
     - [x] Run performance tests
 - [x] Testnet Testing
     - [x] Deploy tagged version
     - [x] Manual testing
     - [x] Run newman tests
     - [x] Run Dapp Example Bootstrap and manual tests
     - [x] Run acceptance tests
     - [x] Run performance tests
- [x] Let Bake
     - [x] git tag
     - [x] Confirm new docker image version is deployed
     - [x] Write up release notes and changelist
 - [ ] Mainnet Testing
     - [ ] Deploy tagged version
     - [ ] Manual testing

**Comment by Nana-EC** [comment]
Deployed to mainnet
