### ISSUE TITLE
eth_newFilter / eth_getFilterChanges not working

### ISSUE THREAD

**Issue by max-chechel-vc** [hashgraph/hedera-json-rpc-relay#2646]
### Description

There was a breaking change introduced in [this PR](https://github.com/hashgraph/hedera-json-rpc-relay/pull/1699)

The problem is that whether shared cache is configured or not we try to write filter id to the shared cache:
https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/services/ethService/ethFilterService/index.ts#L94

But then we read the key from whatever cache is enabled:
https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/services/ethService/ethFilterService/index.ts#L212

As result if there's no shared cache set, this functionality doesn't work.

### Steps to reproduce

1. Set up Hedera JSON RPC relay so that Filters are enabled but there's no Redis cache set up
2. Create filter:
```bash
curl -H "Content-Type: application/json" -X POST -d'{"method":"eth_newFilter","params":[{"topics":["0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822"],"address":["0x1e375f8947dffee57c7713f3176b01858bfba104"]}],"id":2,"jsonrpc":"2.0"}'  http://your-hedera-relay
```
3. Try to request filter changes (while specifying the filter ID obtained on the previous step):
curl -H "Content-Type: application/json" -X POST -d'{"method":"eth_getFilterChanges","params":["<your filter id>"],"id":4,"jsonrpc":"2.0"}' http://your-hedera-relay
4. Receive an error:
```
{"error":{"code":-32001,"name":"Filter not found","message":"[Request ID: 063e3a42-c3ee-4579-a9d5-cac84cd07a42] Filter not found"},"jsonrpc":"2.0","id":4}
```

### Hedera network

mainnet, testnet

### Version

v0.50.1

### Operating system

Linux

**Comment by tknoch-symphony** [comment]
Is this fixed? I am getting same error with redis cache disabled and using version 0.55.0
