### ISSUE TITLE
Extend api_conformity tests

### ISSUE THREAD

**Issue by konstantinabl** [hashgraph/hedera-json-rpc-relay#2652]
### Problem

Currently, the **api_conformity** test suites uses these [tests](https://github.com/ethereum/execution-apis/tree/main/tests) from the Ethereum repository to ensure that we are correctly following the Ethereum RPC schema. However, in the mentioned repository, only a portion of the endpoints we maintain are tested—18 out of approximately 50.

### Solution

We would want to have conformity tests for all of our endpoints. One way to achieve this is to create similar [tests](https://github.com/ethereum/execution-apis/tree/main/tests) for the endpoints we miss, integrate them into our local repository, and add them to the existing tests. Also, we would need to create an OpenRpc schema for those in order to validate the correct format of the fields - e.g hex strings, length of  the hex etc. 
The downside of this approach is that we would need to maintain these tests and ensure they are up-to-date with the newest Ethereum RPC schema.

**Comment by Nana-EC** [comment]
Thanks @konstantinabl

Let's explore that last part more.
For example a GHA that runs and lets us know if the schema changes . It would be non blocking but would alert us if say a new API is added that we haven't added support of or noted as a "won't support".

Another option is if we take a dependency on their versions then we'll get bump requests to stay up to date and in doing so running the schema tests would tell us if there's a mismatch.

Mainly we want to ensure our supported endpoints are conformant and be made aware of additional APIs over time so we decide support.

**Comment by konstantinabl** [comment]
@Nana-EC We're already addressing this in this [issue](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2726) and this [issue](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2727) so I will close this issue
