### ISSUE TITLE
Update the OPERATOR_ID_MAIN in the localAcceptance.env to be one of the local accounts created by the local node.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#2671]
### Problem

Testing accounts should be used when running the acceptance tests.

### Solution

Update the localAcceptance.env file.

**Comment by Nana-EC** [comment]
Also ensure that the `OPERATOR_ID_MAIN` can be set as an evm address and doesn't have to be a `0.0.x` format.
We may have done this already but let's confirm
