### ISSUE TITLE
Gasprice values of Transactions in JSON RPC response denoted in GWEI 

### ISSUE THREAD

**Issue by simsonraj** [hashgraph/hedera-json-rpc-relay#2680]
### Description

The json response for a block & transactions has the gasPrices denoted in different format
`baseFeePerGas` in wei & `gasPrice` of transactions in Gwei, where it should be in wei
sample 
```
 "transactions": [
            {
                "blockHash": "0x3b75ba801136c9ee47dcbe882bb7d99c1c13e87acc65c64e7d98d1145cd1eb91",
                "blockNumber": "0x5db6f5",
                "chainId": "0x128",
                "from": "0xe471b5198df1cd42dffc2a4a83a7e4f9c74f2617",
                "gas": "0x61a80",
                "gasPrice": "0x093",
```

### Steps to reproduce

```

curl --location 'https://testnet.hashio.io/api' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": [
        "0x5db6f5",
        true
    ],
    "id": 1
}'

```

### Hedera network

testnet

### Version

"relay/0.51.0-rc2",

### Operating system

None

**Comment by natanasow** [comment]
@Nana-EC @simsonraj 

Relay's request:
```bash
{
    "method": "eth_getBlockByNumber",
    "params": [
        "0x5db6f5",
        true
    ],
    "jsonrpc": "2.0",
    "id": 1
}
```

Response:
```bash
{
    "result": {
        ...
        "baseFeePerGas": "0x13356219000",
        ...
        "transactions": [
            {
                ...
                "gasPrice": "0x093",
                "hash": "0x6b2527ec12817318961c7a2378ec6fd4bc75ecdb5697e46ef3be5f760d7bba03",
                ...
            }
        ],
        ...
        "hash": "0x3b75ba801136c9ee47dcbe882bb7d99c1c13e87acc65c64e7d98d1145cd1eb91",
        "parentHash": "0x3d1c46ba632ea7e89b5a6a4d31e75f2ae2cb0ebc233b82ec91878bb204d0c3b5"
    },
    "jsonrpc": "2.0",
    "id": 1
}
```


weibarCoef - `10_000_000_000`
baseFeePerGas - 0x13356219000 = `1_320_000_000_000` (weibars) / `10_000_000_000`= **132** (tinybars)
gasPrice - 0x093 = **147** (tinybars)

As far as I understand, the returned _gasPrice_ is not in a gwei but in tinybars . The main question is whether we want to return it in a weibar (same as baseFeePerGas) or stick to the tinybars. I think we should convert it to weibars because end users (and all of the ethereum tools) are working with wei which in hedera context is weibar. Am I missing something @Nana-EC?

**Comment by Nana-EC** [comment]
> @Nana-EC @simsonraj
> 
> Relay's request:
> 
> ```shell
> {
>     "method": "eth_getBlockByNumber",
>     "params": [
>         "0x5db6f5",
>         true
>     ],
>     "jsonrpc": "2.0",
>     "id": 1
> }
> ```
> 
> Response:
> 
> ```shell
> {
>     "result": {
>         ...
>         "baseFeePerGas": "0x13356219000",
>         ...
>         "transactions": [
>             {
>                 ...
>                 "gasPrice": "0x093",
>                 "hash": "0x6b2527ec12817318961c7a2378ec6fd4bc75ecdb5697e46ef3be5f760d7bba03",
>                 ...
>             }
>         ],
>         ...
>         "hash": "0x3b75ba801136c9ee47dcbe882bb7d99c1c13e87acc65c64e7d98d1145cd1eb91",
>         "parentHash": "0x3d1c46ba632ea7e89b5a6a4d31e75f2ae2cb0ebc233b82ec91878bb204d0c3b5"
>     },
>     "jsonrpc": "2.0",
>     "id": 1
> }
> ```
> 
> weibarCoef - `10_000_000_000` baseFeePerGas - 0x13356219000 = `1_320_000_000_000` (weibars) / `10_000_000_000`= **132** (tinybars) gasPrice - 0x093 = **147** (tinybars)
> 
> As far as I understand, the returned _gasPrice_ is not in a gwei but in tinybars . The main question is whether we want to return it in a weibar (same as baseFeePerGas) or stick to the tinybars. I think we should convert it to weibars because end users (and all of the ethereum tools) are working with wei which in hedera context is weibar. Am I missing something @Nana-EC?

Good investigation, I think we should be sending back weibar for consistency and equivalence, looks like we missed it as you noted.
