### ISSUE TITLE
Replace getRecord network calls with calls to Mirror node

### ISSUE THREAD

**Issue by Ivo-Yankov** [hashgraph/hedera-json-rpc-relay#2706]
### Problem

Calling the consensus node with `getRecord` charges the relay operator and not all such instances are captured by the metrics or the `hbarRateLimiter`. Find a way to call the mirror node where possible. A noteworthy place for this optimization is the `fileCreate / fileAppend` flow in the `sdkClient`

_No response_

**Comment by quiet-node** [comment]
A list of un-captured hbars:

- https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/clients/sdkClient.ts#L670
- https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/clients/sdkClient.ts#L693
- https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/clients/sdkClient.ts#L710
