### ISSUE TITLE
EPIC: Extend conformity tests

### ISSUE THREAD

**Issue by konstantinabl** [hashgraph/hedera-json-rpc-relay#2721]
### Problem

At the moment, we are basing our conformity tests on these [tests](https://github.com/ethereum/execution-apis/tree/main/tests) . However, they are not covering all the endpoints we currently have, so we need to create the rest on our own.

### Solution

- Create local directories for each missing endpoint and create similar tests to the ones in the repo above
- Extend the format checking currently created in this [PR](https://github.com/hashgraph/hedera-json-rpc-relay/pull/2649) for the new endpoints

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2725
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2726
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2727
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2728
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/2754
```

**Comment by quiet-node** [comment]
@konstantinabl @nadezhdapopovaa please confirm if this ticket is good to be closed now. Thanks!
