### ISSUE TITLE
Add eth_call, eth_getLogs and eth_estimateGas test to conformity tests

### ISSUE THREAD

**Issue by konstantinabl** [hashgraph/hedera-json-rpc-relay#2754]
Add test scenarios for:
- [x] eth_call - non existing contract
- [x] eth_call - existing contract view function and existing from
- [x] eth_call - existing contract tx and existing from
- [x] eth_call - existing contract tx, existing from and positive value
- [x] eth_call - existing contract view function and non-existing from
- [x] eth_call - existing contract tx and non-existing from
- [x] eth_call - existing contract tx, non-existing from and positive value
- [x] eth_estimateGas - non existing contract
- [x] eth_estimateGas - existing contract view function and existing from
- [x] eth_estimateGas - existing contract tx and existing from
- [x] eth_estimateGas - existing contract tx, existing from and positive value
- [x] eth_estimateGas - existing contract view function and non-existing from
- [x] eth_estimateGas - existing contract tx and non-existing from
- [x] eth_estimateGas - existing contract tx, non-existing from and positive value
- [x] eth_getLogs - non-existing contract
- [x] eth_getLogs - existing contract
- [x] eth_getLogs - existing contract and from/to block

**Comment by natanasow** [comment]
@Nana-EC adding 3 as points because the number of tests is pretty big but with no architecture changes. Thanks to these tests, we found a bug in the mirror node.
