### ISSUE TITLE
Inconsistent transaction execution and rate limiting issues across different JSON-RPC relays

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#2759]
### Description

When interacting with the Hedera network using different JSON-RPC relays, I've encountered two significant issues:

1. Inconsistent transaction execution: Identical transactions sent through different relays yield different results. One transaction fails while the other succeeds, with the only difference being the JSON-RPC relay used.

Example:
- Failed transaction: https://hashscan.io/mainnet/transaction/1722015963.402456003 (using thirdweb relay)
- Successful transaction: https://hashscan.io/mainnet/transaction/1722016309.781532823 (using hashio relay)

2. Rate limiting: The official hashio relay has very tight rate limits, frequently resulting in a "HBAR Rate limited exceeded" error. This forces users to seek alternative relays, which may lead to the inconsistent behavior mentioned above.

Expected behavior:
1. Transactions should execute consistently regardless of the JSON-RPC relay used.
2. Rate limits should be more accommodating to allow for reasonable usage without frequent errors.

### Steps to reproduce

1. Inconsistent transaction execution:
   a. Attempt to execute a Gnosis Safe transaction(or perhaps any tx) using the thirdweb relay (https://295.rpc.thirdweb.com).
   b. Observe that the transaction fails.
   c. Execute the same transaction using the hashio relay (https://mainnet.hashio.io/api).
   d. Observe that the transaction succeeds.

2. Rate limiting issues:
   a. Connect to the hashio relay (https://mainnet.hashio.io/api).
   b. Execute smart contract function calls at a rate of approximately 1 per minute for 5-10 minutes.
   c. Observe the "HBAR Rate limited exceeded" error occurring frequently.

Additional notes:
- The inconsistent behavior makes it challenging to rely on alternative relays when the hashio relay's rate limits are exceeded.
- This issue significantly impacts the reliability and usability of the Hedera network for developers and users.

### Hedera network

mainnet

### Version

latest on mainnet as of writing

### Operating system

None

**Comment by mshakeg** [comment]
Same issue as `thirdweb` using the `validationcloud` relay:

https://hashscan.io/mainnet/transaction/1722019233.447989003

**Comment by mshakeg** [comment]
Hey @Ivo-Yankov @natanasow @ebadiere would appreciate if this issue was taken more seriously.

I frequently run into the `HBAR Rate limit exceeded` error when simply making a few `eth_calls`(<10/min) on the **hashio mainnet relay**, and it makes for a terrible devX. Not sure why eth_calls would ever have the `HBAR Rate limit exceeded` error, as they don't cost HBAR.

**Comment by fessmm** [comment]
@Nana-EC ^

**Comment by mshakeg** [comment]
I'm also unable to deploy a contract via the hashio mainnet relay:

> [Request ID: cbf5eed7-b21c-48c4-8d77-4814930665b9] The HBAR rate limit was preemptively exceeded due to an excessively large callData size.

**Comment by ebadiere** [comment]
@mshakeg This issue is being taken seriously.  We are currently in the process of refactoring the HBar Rate Limiter to support many configuration points.  At this time Hashio is not meant to be used for production applications.  It's there to help a user get started, with the intent that the user migrates to a third party vendor.  

Issue #2739 is the Epic that is tracking this effort.

**Comment by mshakeg** [comment]
@ebadiere thanks for the update. I tried a [few other providers](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2759#issuecomment-2253285178) when I initially created this issue, **thirdweb** had issues then as well, however, their relay seems to be performing much better since though not perfectly, it frequently returns an error response, despite the tx being relayed to the core validator/s.

**Comment by Nana-EC** [comment]
Hey @mshakeg,
The hbar rate limiting enhancement project Eric mentioned has been completed.
We do not expect HashIO for example to be issuing rate limited as often as before as access is more fairly distributed.
Please let us know if you're still experiencing issues here.
Thanks

**Comment by mshakeg** [comment]
Hey @Nana-EC I switched over to using thirdweb's RPC a while back, but if this is no longer an issue with hashio then this issue can be closed.

**Comment by Nana-EC** [comment]
Sounds good. Keep us posted if anything.
The rate limit improvements should make HashIO and other relays much more available to users.
