### ISSUE TITLE
Websocket subscription creates the same subscription ID for new connection from the same client

### ISSUE THREAD

**Issue by simsonraj** [hashgraph/hedera-json-rpc-relay#2926]
### Description

when making new subscription requests from the same client, Hedera creates the same Subscription ID, whereas it should be creating a new one every time similar to other chains. this is critical because our nodes are not able to handle multiple RPC connections in a single node, causing tons of errors

### Steps to reproduce

make multiple new subscription requests to
```{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "eth_subscribe",
  "params": ["newHeads"]
}
```
when tried to connect with multiple connections for parallelisation, the existing context gets hung due to the same subscription ID
a new subscription request

### Additional context

<img width="1237" alt="image" src="https://github.com/user-attachments/assets/382cda91-29e4-48b1-91f9-db9b2219c973">

### Hedera network

testnet

### Version

latest

### Operating system

None

**Comment by Neurone** [comment]
This is intended behavior: https://github.com/hashgraph/hedera-json-rpc-relay/blob/5018b23b8c4fc2489f0f0f3fe08ecf633fe528e8/packages/relay/tests/lib/subscriptionController.spec.ts#L252

As a temporary solution to make the relay work as you expect, comment this test and the implementation: https://github.com/hashgraph/hedera-json-rpc-relay/blob/5018b23b8c4fc2489f0f0f3fe08ecf633fe528e8/packages/relay/src/lib/subscriptionController.ts#L102-L107

Waiting for the engineering team to make a decision here, my suggestion is to introduce an env variable to let choose this behavior.
