### ISSUE TITLE
Ensure Schema compliance with execution-apis schema

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#295]
### Problem

The relay has occasionally been shown to conform to different schema standards than other Eth client API's.
This has mostly been since not all clients observe the same standard.

### Solution

Conform to the [ethereum execution-apis schema](https://github.com/ethereum/execution-apis/tree/main/src/schemas)

Ensure all objects and components match expected formats

Suggestions
- Ensure open rpc document added by #114 matches [ethereum execution-apis schema](https://github.com/ethereum/execution-apis/tree/main/src/schemas) 
- Run integration (not E2E) level tests against endpoints that verify schema against doc

**Comment by ar-conmit** [comment]
There is a tool that might help running integration tests - https://github.com/open-rpc/test-coverage
