### ISSUE TITLE
`eth_getTransactionReceipt` invalid response: hex string instead of uint

### ISSUE THREAD

**Issue by rafaelkallis** [hashgraph/hedera-json-rpc-relay#302]
### Description

When performing `eth_getTransactionReceipt` the response is not valid. According to https://github.com/ethereum/execution-apis/blob/main/src/schemas/receipt.yaml#L50-L101 the `blockNumber`, `cumulativeGasUsed`, `gasUsed`, `transactionIndex`, `effectiveGasPrice` and `status` properties are `uint`, the relay response uses hex strings instead. 

A json-rpc client with client-side validation, such as go-ethereum, throws validation exceptions in such cases.

### Steps to reproduce

```sh
curl -X POST $BASE_URL \
                                       -H 'Content-Type: application/json' \
                                       -d "{\"id\":\"2\",\"jsonrpc\":\"2.0\",\"method\":\"eth_getTransactionReceipt\",\"params\":[\"$TRANSACTION_HASH\"]}" --silent
```
`BASE_URL=http://localhost:7546`
`TRANSACTION_HASH=0x9040d4244cfeb7c5fc96ac378308d9df8a6616c550e9d02162b3ef3fe889df86`

### Additional context

![image](https://user-images.githubusercontent.com/9661903/177737119-f5dab61a-ae95-4df7-be76-f410ff62544b.png)

![image](https://user-images.githubusercontent.com/9661903/177737378-202be50e-ba06-41fb-a896-ffacf365d7db.png)

### Hedera network

testnet

### Version

main

### Operating system

Linux

**Comment by Nana-EC** [comment]
Interesting, another case of non conformance. The main wiki highlights it as a hash32 [eth_getTransactionReceipt](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_gettransactionreceipt)

**Comment by shemnon** [comment]
Per the schema `uint`s are hex strings - https://github.com/ethereum/execution-apis/blob/main/src/schemas/base-types.yaml#L34-L37
