### ISSUE TITLE
[HBAR Rate Limit Redesign] Improive logging logic for hbarLimit related classes

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-json-rpc-relay#3025]
### Problem

Logging in the classes within the `hbarLimiter` repositories (e.g., `EthAddressHbarSpendingPlanRepository`, `HbarSpendingPlanRepository`, `IPAddressHbarSpendingPlanRepository`) appears to be duplicated and does not include a `requestId`. This makes it difficult to track logs during debugging.

### Solution

Improve logging for HbarLimitter related classes

**Comment by victor-yanev** [comment]
Already fixed in https://github.com/hashgraph/hedera-json-rpc-relay/pull/3014

**Comment by victor-yanev** [comment]
Okay, nvm it seems that these changes we reverted in the PR, sorry!
