### ISSUE TITLE
Ethers v6 Filter API not working with 0.55.0

### ISSUE THREAD

**Issue by tknoch-symphony** [hashgraph/hedera-json-rpc-relay#3030]
### Description

While running our instance of the latest version of Hedera JSON-RPC node (0.55.0), filter api does not work, even when filter api flag is turned on. The client calls are made by ethers v6.

```
@TODO Error: could not coalesce error (error={ "code": -32001, "message": "[Request ID: 038fa6e7-6804-47e9-8c36-a2a43f4fc4a0] Filter not found", "name": "Filter not found" }, payload={ "id": 74408, "jsonrpc": "2.0", "method": "eth_getFilterChanges", "params": [ "0x0a7c11483e1472a3cf6836580d1c0e50" ] }, code=UNKNOWN_ERROR, version=6.13.2)
    at makeError (/node_modules/ethers/lib.commonjs/utils/errors.js:129:21)
    at JsonRpcProvider.getRpcError (/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:730:41)
    at /node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:302:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'UNKNOWN_ERROR',
  error: {
    code: -32001,
    name: 'Filter not found',
    message: '[Request ID: 038fa6e7-6804-47e9-8c36-a2a43f4fc4a0] Filter not found'
  },
  payload: {
    method: 'eth_getFilterChanges',
    params: [ '0x0a7c11483e1472a3cf6836580d1c0e50' ],
    id: 74408,
    jsonrpc: '2.0'
  },
  shortMessage: 'could not coalesce error'
}
```

### Steps to reproduce

1. install Hedera JSON-RPC node (0.55.0). Turn on filter api
2. Use ethers v6 to subscribe to a smart contract event filter
3. See errors in Hedera JSON-RPC node logs mentioning filter api is not implemented

### Hedera network

testnet

### Version

0.55.0

### Operating system

Linux

**Comment by Nana-EC** [comment]
Thanks @tknoch-symphony 
We'll take a look into this, let us know if you're still experiencing this or have additional and recent data.

**Comment by simzzz** [comment]
you can assign me

**Comment by simzzz** [comment]
Hello, @tknoch-symphony I have investigated your issue using the versions provided and I had no problems accessing the Filter API, however I could reproduce your exact error in the following scenarios:

1. I restarted the server between two different calls to `eth_getFilterChanges` for the same filter
2. I waited more than 5 minutes between two different calls to `eth_getFilterChanges` which is the default TTL for a filter in the JSON RPC Relay. ([here is the logic](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/constants.ts#L185))

Could you verify these scenarios are not causing your issue? You can also modify the default TTL for a filter using the `FILTER_TTL` environment variable which takes in milliseconds.

**Comment by tknoch-symphony** [comment]
@simzzz to give more context, it works using ethers v5 but when I migrated to ethers v6, this error started showing up in the JSON-RPC. Using the public JSON-RPC (https://testnet.hashio.io/api), it works.

My suspicion was some configuration was missing when using the available docker image and subscribing to smart contract events using ether v6 (which will poll the filter API).

**Comment by simzzz** [comment]
Have you tried upgrading to the latest version of the JSON-RPC if that's feasible for you? Also would it be possible to share the config you are using so that we can take a look and try to reproduce the problem on our end? @tknoch-symphony

**Comment by simzzz** [comment]
Hi @tknoch-symphony , just wanted to follow up and see if you had a chance to look into my last message. Let me know if there's anything else I can assist with to help debug this issue!

**Comment by tknoch-symphony** [comment]
@simzzz we are updating our JSON RPC to latest version and testing, will let you know soon

**Comment by tknoch-symphony** [comment]
@simzzz I confirm it works with version 0.61.0. Closing the issue
