### ISSUE TITLE
Update `eth_getBlockByHash` and `eth_getBlockByNumber` to pass a timestamp range in mirror node queries

### ISSUE THREAD

**Issue by victor-yanev** [hashgraph/hedera-json-rpc-relay#3040]
In the `eth_getBlockByHash` and `eth_getBlockByNumber` methods, ensure the existing `timestampRangeParams` are used for subsequent API calls to `getLogsWithParams` and `resolveEvmAddress`. This change is necessary to handle the new 60-day limit on querying historical data in the mirror node.

**Comment by xin-hedera** [comment]
Disclaimer, I am not familiar with repay source code at all.

by the name of `eth_getBlockByHash` and `eth_getBlockByNumber`, I assume the input if either a block number or a block hash, if the relay queries mirrornode `/api/v1/contracts/results` endpoint with either `block.number` or `block.hash` param, there is no need to pass any timestamp range parameters. for example:

https://mainnet.mirrornode.hedera.com/api/v1/contracts/results?block.number=64665070
https://mainnet.mirrornode.hedera.com/api/v1/contracts/results?block.hash=0xffc03fb6ae5f86f6a6af4bbe5f0e854fdd2a19cfaf72ce1ef49f2f2e750889f89987b3d505d3c2b32e0f42d39db34e1f

Note the corresponding record file is `2024-06-02T19_34_12.026409003Z.rcd.gz`, far beyond the 60d range.
