### ISSUE TITLE
Update `eth_getTransactionByHash` and `eth_getTransactionReceipt` to pass a timestamp in mirror node queries

### ISSUE THREAD

**Issue by victor-yanev** [hashgraph/hedera-json-rpc-relay#3041]
Update the `eth_getTransactionByHash` and `eth_getTransactionReceipt` methods to:
- fetch the transaction from the `transactions/{transactionId}` endpoint
- extract the consensus timestamp from the fetched transaction
- pass it as a `timestamp` parameter when calling `getLogsWithParams` and `resolveEvmAddress` 

This modification ensures that transaction data is retrieved within the allowed time range under the new API restrictions.

**Comment by xin-hedera** [comment]
Q: given a ETH transaction hash, isn't it easier to get the logs via`/api/v1/contracts/results/logs?transaction.hash=X` endpoint?

**Comment by victor-yanev** [comment]
> Q: given a ETH transaction hash, isn't it easier to get the logs via`/api/v1/contracts/results/logs?transaction.hash=X` endpoint?

Yes we can, after the discussion today, this issue is no longer needed.
