### ISSUE TITLE
Record a video illustrating the new HBar Rate Limiter

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-json-rpc-relay#3052]
### Problem

HBar rate limiting can leave a less than great initial impression of the relay.

### Solution

Record in a video how a user can get rate limited in the relay.  Then move the user into a more privileged tier, and run those expensive transactions again, showing how the user is not rate limited.  Use a large smart contract that requires FileAppends to run.  The target audience for this will be partners running the relay.

**Comment by Nana-EC** [comment]
Received and will be weighed in follow up marketing efforts as needed.
Thanks @victor-yanev
