### ISSUE TITLE
Let 0-value Ethereum transactions pass

### ISSUE THREAD

**Issue by Neurone** [hashgraph/hedera-json-rpc-relay#3105]
### Problem

Currently, the JSON-RPC relay forces the Ethereum transaction value to be greater than 0 in order to be accepted. 

This isn't a real network constraint, both Hedera and Ethereum accept 0-value transactions, but it is enforced in two parts of the code (during the [validate API request](https://github.com/hashgraph/hedera-json-rpc-relay/blob/7796aca3d8028e9732c58fb6855bef4520c4b3cc/packages/relay/src/lib/eth.ts#L643) and during the [precheck transaction](https://github.com/hashgraph/hedera-json-rpc-relay/blob/7796aca3d8028e9732c58fb6855bef4520c4b3cc/packages/relay/src/lib/precheck.ts#L64)).

I removed these checks and was able to send a [correct 0-value transaction](https://hashscan.io/testnet/tx/0x29d9264df7244583e69bdb41822887df2511b6ce8b10463280bc8260abb3c778) to the network.

### Solution

- Let the JSON-RPC relay operator decide whether to accept 0-value transactions.
- Set the default for this parameter to `true`: 0-value transactions are accepted.

**Comment by simzzz** [comment]
You can assign me
