### ISSUE TITLE
Swap eth address for evm address everywhere in the hbar limiter code

### ISSUE THREAD

**Issue by konstantinabl** [hashgraph/hedera-json-rpc-relay#3125]
Addressing the following comment https://github.com/hashgraph/hedera-json-rpc-relay/pull/3110#discussion_r1804004678
Possibly adress and discuss following comment as well https://github.com/hashgraph/hedera-json-rpc-relay/pull/3110#discussion_r1805150333

**Comment by simzzz** [comment]
I've renamed EthAddress to EvmAddress
