### ISSUE TITLE
Move deleteAll method for spending plans in base class

### ISSUE THREAD

**Issue by konstantinabl** [hashgraph/hedera-json-rpc-relay#3127]
Addressing this comment https://github.com/hashgraph/hedera-json-rpc-relay/pull/3110#discussion_r1804014693

**Comment by quiet-node** [comment]
Thank you, @simzzz, for bringing this to my attention! @konstantinabl and @victor-yanev, could either of you please confirm whether this is now out of date? If so, please close the ticket as complete.

**Comment by victor-yanev** [comment]
> Thank you, @simzzz, for bringing this to my attention! @konstantinabl and @victor-yanev, could either of you please confirm whether this is now out of date? If so, please close the ticket as complete.

For deleteAll specifically it’s out of date, but the general idea still applies to other methods, we can add an abstract repository class which holds the common logic

**Comment by konstantinabl** [comment]
@quiet-node  This particular issue is out of date, if we want to address something else, we can open an issue

**Comment by Nana-EC** [comment]
NO longer applicable
