### ISSUE TITLE
Upgrade to Node JS v20

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#3156]
### Problem

The relay currently uses node version 18 which has an end of life at the end of April 2025

### Solution

Upgrade to the latest LTS version which is currently v20

- [x] Update reference of v18 to latest LTS v20
- [x] Run complete acceptance test suite on HTTP server
- [x] Run complete acceptance test suite on WS server
- [x] Confirm CI jobs run
- [x] Run DApp Tests
- [x] Run Smart contract repo test suites
- [x] Run perf tests and measure an deltas
- [x] Deploy an alpha and confirm in previewnet

### Alternatives

Make a consideration for `v22.5.1` as it was recently identified as a pinned version of nodejs for the ethers library. Something to check

**Comment by ebadiere** [comment]
Node version [22](https://nodejs.org/en/blog/announcements/v22-release-announce) contains some changes of interest.  Most notable are:

- [Running package.json scripts](https://nodejs.org/en/blog/announcements/v22-release-announce#running-packagejson-scripts)

Node.js 22 includes a new experimental feature for the execution of scripts from the package.json with the cli flag node --run <script-in-package-json>. It also supports node --run test which executes the test command inside package.json scripts.

Contributed by Yagiz Nizipli [#52190](https://github.com/nodejs/node/pull/52190)

- [WebSocket](https://nodejs.org/en/blog/announcements/v22-release-announce#websocket)
The browser-compatible implementation of WebSocket, previously behind the flag --experimental-websocket, will be enabled by default. This provides a WebSocket client to Node.js without external dependencies.

Contributed by the Undici team and Aras Abbasi in [#51594](https://github.com/nodejs/node/pull/51594)

- [ ] [glob and globSync](https://nodejs.org/en/blog/announcements/v22-release-announce#glob-and-globsync)

This release adds to the node:fsmodule the functions glob and globSync for pattern matching. Developers can now utilize these functions for matching file paths based on specified patterns.

Contributed by Moshe Atlow [#51912](https://github.com/nodejs/node/pull/51912)

Node Release [v22.5.1 ](https://nodejs.org/en/blog/release/v22.5.1)contains a fix to a regression introduced in 22.5.0

A separate issue should be opened to upgrade to this version in the relay.

**Comment by Nana-EC** [comment]
Verified by @ebadiere with note to consider upgrade to v22.5.0 in future
