### ISSUE TITLE
Publish Test Report steps in CIs are failing with 403 Forbiden code

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-json-rpc-relay#3337]
### Description

Publish Test Report steps in CIs are failing with 403 Forbiden code. 

https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/12304987717/job/34398828904?pr=3321#step:6:33
https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/12287045705/job/34336605725?pr=3328#step:6:32

### Version

latest

### Operating system

None

**Comment by andrewb1269hg** [comment]
A little more investigation below. Commits are listed from oldest (top) to newest (bottom):

PR #3328 
Commit ID: bfb33241d467ebd1e938c0105f5ca4a8836fcd9c
One test failed:
`Acceptance Tests / Test Results (push)`
The Publish Result step (with the issue identified above) was [successful](https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/12324300762)

PR #3321 
Commit ID: 60b06baa306e8f72b933f0806b333d8cb5cbcdd6
Several tests failed:
`Subgraph Tests / Test Results (push)`
`Acceptance Tests / Websocket Batch 3 / acceptance-workflow (push)`
`Acceptance Tests / ERC20 / acceptance-workflow (push)`
Despite these failures, it appears the `Publish Result` step was [successful](https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/12324304318)

PR #3330 
Commit ID: bb58a3e45ede060096faee78ae8f897c1775c153
Even more tests failed:
`Dapp Tests / Dapp Tests (push)`
`Release Integration Environment / publish (push)`
`Tests / Tests (push)`
`Acceptance Tests / ERC20 / acceptance-workflow (push)`
`Acceptance Tests / Precompile / acceptance-workflow (push)`
`Conformity Test Workflow / Test Results (push)`
In investigating these failures, the Acceptance tests did fail, but the `Publish Results` step was [successful](https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/12324306140).

PR #3333 
Commit ID: 88dd213a5d4935edff6a6c7ab0efe4a1c497a803
Tests failed again:
`Dapp Tests / Dapp Tests (push)`
`Release Integration Environment / publish (push)`
`Tests / Tests (push)`
`Tests / Test Results (push)`
While there were many tests failed, the `Acceptance` tests were [successful](https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/12324310217/job/34401627183) including the `Publish Results` step.

There are some test issues that need to be resolved, but I do not see any issues related to a 403 Forbidden code at this time.

**Comment by quiet-node** [comment]
Thank you for your effort! Probably it was an internal server issue with GitHub or some sorts. Will close the ticket for now but will continue to monitor these issues with upcoming PRs. Thanks again, @andrewb1269hg 
!
