### ISSUE TITLE
Align log with execution apis

### ISSUE THREAD

**Issue by rafaelkallis** [hashgraph/hedera-json-rpc-relay#337]
### Description

https://github.com/hashgraph/hedera-json-rpc-relay/blob/73d8244f0c811f1d74b93791f3905a67bf0c9c0b/packages/relay/src/lib/eth.ts#L825-L835

`blockNumber`, `transactionIndex`, `logIndex` require `EthImpl.numberTo0x` because they are of type `uint` (execution-api reference https://github.com/ethereum/execution-apis/blob/8e43f278b8afdf2f496383361275a515d87b80cf/src/schemas/receipt.yaml#L10-L24)

### Steps to reproduce

Fetch any transaction receipt with logs, e.g. transaction `0x9040d4244cfeb7c5fc96ac378308d9df8a6616c550e9d02162b3ef3fe889df86`

### Additional context

Transaction receipt response, compare `result.blockNumber` and `result.logs[*].blockNumber` , one of them must be wrong :)

![image](https://user-images.githubusercontent.com/9661903/178941973-b2ace762-82cc-4bea-b53d-f776b20af9fb.png)

### Hedera network

testnet

### Version

0.3.0

### Operating system

Linux

**Comment by Nana-EC** [comment]
Correct. We should be hex encoding all uints according the [schema](https://github.com/ethereum/execution-apis/blob/8e43f278b8afdf2f496383361275a515d87b80cf/src/schemas/base-types.yaml#L34)
