### ISSUE TITLE
Align transaction with ethereum execution apis

### ISSUE THREAD

**Issue by rafaelkallis** [hashgraph/hedera-json-rpc-relay#338]
### Description

https://github.com/hashgraph/hedera-json-rpc-relay/blob/73d8244f0c811f1d74b93791f3905a67bf0c9c0b/packages/relay/src/lib/eth.ts#L1032-L1052

`gas`, `transactionIndex`, `value` require `EthImpl.numberTo0x` because they are `uint` (see https://github.com/ethereum/execution-apis/blob/main/src/schemas/transaction.yaml) 

### Steps to reproduce

`eth_getBlockByNumber` `[17165012, true]`

### Additional context

![image](https://user-images.githubusercontent.com/9661903/178995417-6c13a849-0105-466c-bd0b-46c8968a532a.png)

### Hedera network

testnet

### Version

0.3.0

### Operating system

Linux

**Comment by Nana-EC** [comment]
All uints should be hex encoded according to [schema](https://github.com/ethereum/execution-apis/blob/8e43f278b8afdf2f496383361275a515d87b80cf/src/schemas/base-types.yaml#L34)
