### ISSUE TITLE
Verify consistent passes of DApp automated tests against previewnet/testnet

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#339]
### Problem

It's unclear if the TPS in production envs may affect the success rate of tests.
In local node we're in control of all submitted transactions but in production w need to be able to handle change state w regards to block and transaction details.

This may prevent the adoption of fully automated tests for each release.

### Solution

Verify consistent run passes of DApp test against previewnet & testnet.
Where inconsistencies are seen let's capture tickets to fix in the next sprint.

**Comment by ar-conmit** [comment]
Here are my findings:

***Testnet***
No issues found
25 total tests:
* 21 passed successfully
* 4 were unsuccessful. For all of them the Metamask account could not connect to the DApp. It just the Metamask window did not pop up. The same issue sometimes occurs locally.

***Previewnet***
2 issues are found:

1. Deploy contract, Transfer HTS token and Send HBARs are throwing the same error:
```
Error: invalid BigNumber string (argument="value", value="0x-7ffffffffffd2800", code=INVALID_ARGUMENT, version=bignumber/5.6.2)
```

There is some general issue with the block numbers
`https://previewnet.mirrornode.hedera.com/api/v1/blocks?order=desc&limit=2`

```
{
      "count": 1,
      "hapi_version": "0.28.0",
      "hash": "0x7f91b12560822a0646e2315e589b579ac7d15b82eac13aaf57242f763b064367d8cc92f4bd81aba3f0ab117a42533853",
      "name": "2022-07-15T11_05_06.510407045Z.rcd.gz",
      "number": -9223372036854587000,
      "previous_hash": "0x13a1f1b624df76fd8054794f9a0a7debe619e05f9fa6b2a4d741af8e48896e6532b07170241724eec828f0cad78990eb",
      "size": 847,
      "timestamp": {
        "from": "1657883106.510407045",
        "to": "1657883106.510407045"
      },
      "gas_used": 0,
      "logs_bloom": "0x"
    }
```
All blocks have a negative big number `-9223372036854587000` which in hex is `0x-7FFFFFFFFFFD1E78` - the same as the error message.

2. Error in eth_gasPrice
`eth_gasPrice: -32603 1084 ms. Error (BUG) RequestType.fromCode() does not handle code: 86`

The error is logged in local rpc relay configured against public previewnet consensus and mirror node.

**Comment by steven-sheehy** [comment]
Since previewnet uses v6 record files, consensus nodes are the source of block numbers. Previewnet should be reset or a file update should occur to correct the block numbers.

**Comment by Nana-EC** [comment]
Issue resolved in previewnet. @ar-conmit please retry and confirm consistent runs now.

Can we address the noted issues
- Metamask window not popping up. Even if cypress issue can we get a workaround
- `eth_gasPrice` error

**Comment by Kalina-Todorova** [comment]
Hi @Nana-EC @steven-sheehy 
It seems that after the reset the files for exhange rate and fees are missing:
- https://previewnet.mirrornode.hedera.com/api/v1/network/fees
- https://previewnet.mirrornode.hedera.com/api/v1/network/exchangerate
Could you help out with this?

**Comment by ar-conmit** [comment]
> Issue resolved in previewnet. @ar-conmit please retry and confirm consistent runs now.
> 
> Can we address the noted issues
> 
> * Metamask window not popping up. Even if cypress issue can we get a workaround
> * `eth_gasPrice` error

The issues are addressed and fixed. The tests seem to be consistent now.
