### ISSUE TITLE
acceptancetest check seems inconsistent

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-json-rpc-relay#381]
### Problem

The pr for issue #374 required 7 attempts to run acceptancetest check before succeeding.  When looking at the logs, many of the attempts seemed to fail on different tests.  

When running acceptancetest against a local node, what docker desktop resources are necessary to run complete successfully?

### Solution

Examine the logs to see if there is a cause for the failures can be determined.
Noticed that the acceptance tests are run without the @global flag.  Would tests succeed more consistently if this flag was turned on when running this step?

**Comment by ar-conmit** [comment]
One of the issues:
```
Error: invalid hexlify value (argument="value", value="bf6bc9564689d36d330b2e14d6983538afb6bd9aabd604903df94196d15fc5", code=INVALID_ARGUMENT, version=bytes/5.6.1)
```
Occurs when creating an alias account, the raw private key generated from the sdk is less than 32 bytes, so ethers cannot parse it and throws an error. 
Addressed and described more in details [here](https://github.com/hashgraph/hedera-sdk-js/issues/1220)

**Comment by georgi-l95** [comment]
Issue when calling eth_feeHistory with newest > latest block. We are caching the latest block and setting the newest to be 10 ahead and by the time we request the latest, it’s already one ahead. So we are expecting to be 10 blocks beyond, but sometimes it’s actually 11 blocks.

`-Request beyond head block: requested 85, head 76 

+Request beyond head block: requested 85, head 75`

**Comment by ar-conmit** [comment]
Found another issue
```
1) RPC Server Acceptance Tests
       Acceptance tests
         RPC Server Acceptance Tests
           RPC Server Acceptance Tests
             "before all" hook in "RPC Server Acceptance Tests":
     Request failed with status code 404
```

Caused by one of the record `.rcd` files that contains token create transaction. The mirror importer cannot populate the database, the insert token query is incorrect and the postgres throws `ERROR:  invalid input value for enum token_type: "CONTRACT" at character 1881`
