### ISSUE TITLE
Optimize eth_getLogs

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-json-rpc-relay#389]
The current implementation of `eth_getLogs` is not optimized well. The method requires data that is not returned by the Mirror Node in the endpoints that return Log data -
	- `contracts/results/logs`
	- `contracts/:contractId/results/logs`
The missing fields are taken from `/contracts/:contractId/results/:timestamp` and are the following:
	- `block_hash`
	- `block_number`
	- `transaction_index`
	- `hash`

The problem is that every single Log object requires a request to be made to the mirror node. This greatly increases the total number of mirror node requests.

As a solution we suggest to modify the REST endpoints `contracts/results/logs` and `contracts/:contractId/results/logs` to return the missing data but only if a flag is set to `true` - this should ensure that the additional queries do not impact the performance of existing functionallity that relies on those endpoints.

For `hash` and `transaction_index` it should be possible to perform a `join Transaction on Transaction.consensus_timestamp = ContractLog.consensus_timestamp` in the existing query to the ContractLog table.

For `block_hash` and `block_number` it would be more complicated, since the `RecordFile.timestamp` does not necessarily match the timestamp of the Log. One solution would be to call `recordFileService.getRecordFileBlockDetailsFromTimestamp` for every log object. This is not ideal, but would still reduce the total number of queries made by the Mirror Node for a single execution of `eth_getLogs`.
If those changes are made to the Mirror node we could optimize `eth_getLogs` to only perform 1 or 2 Mirror Node requests.

Another problem we noticed is that the endpoint `blocks/:blockHash` often times takes longer than 10 seconds to execute, which results in a TIMEOUT error thrown by Axios in the Relay.

**Comment by Ivo-Yankov** [comment]
Theoretically if the `contract_log` table in MR had a `record_file_index` field it would be possible to use a `JOIN` in a query when selecting multiple logs and easily retrieve their respective block data.

**Comment by Ivo-Yankov** [comment]
Regarding the poor performance of `/blocks/:blockHash` that is caused by a query that uses a `LIKE` statement to find the record file based on a given hash. It supports both 32 and 48 byte hashes. If the `record_file` table had a field for the 32 byte variant of the hash, then the `LIKE ` statement could be dropped in favour of a simple `=`.

**Comment by Ivo-Yankov** [comment]
To sum up: to solve the described issues we propose the following changes to the mirror node DB structure:
- Add a referance in `contract_log` to `record_file.index`
- Add a 32 byte hash field in `record_file`

**Comment by steven-sheehy** [comment]
Opened a ticket to address lack of block/transaction data in logs: https://github.com/hashgraph/hedera-mirror-node/issues/4217
