### ISSUE TITLE
`ethCall` doesn’t work when gas limit is above 880k

### ISSUE THREAD

**Issue by dimitrovmaksim** [hashgraph/hedera-json-rpc-relay#437]
### Problem:
[Here](https://github.com/hashgraph/hedera-sdk-js/blob/main/src/query/Query.js#L339) In the SDK `cost` is being set to the cost value calculated with `.getCost()`and set to the query instance with `.setQueryPayment(cost)` by the [sdkClient](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/clients/sdkClient.ts#L223-L226) in the relay, but later theres is an if/else condition which seems to always overwrite the value of `cost` https://github.com/hashgraph/hedera-sdk-js/blob/main/src/query/Query.js#L343-L347 so the cost will always be (i think) 1 hbar, which is around 800_000 gas. This will result the call failing with `INSUFFICIENT_TX_FEE` error, because the calculated fee is greater than 1hbar, but the payment that is being send is 1hbar(the default max fee value). This currently impacts the integration with TheGraph, because the graph-node reserves more than that when making `eth_call` from the handlers (generally graph node reserves the whole 50M which is the max on ethereum, but hedera is capped to 15M, this should probably be handled by the relay)

Additionally If you don't set the cost with `.setQueryPayment(cost)`, the SDK will throw the following error `MaxQueryPaymentExceeded [MaxQueryPaymentExceededError]: query cost of 1 ℏ HBAR exceeds max set on client: 8.73239574 ℏ HBAR ` which seems to have the two values switched.

### Solution
Possible solution would be for the sdk to configure how much to pay for contract local call

**Comment by Kalina-Todorova** [comment]
Related to https://github.com/hashgraph/hedera-sdk-js/issues/1230

**Comment by Nana-EC** [comment]
This  should have been fixed with the update to v2.18.0.
Please try this out and confirm

**Comment by dimitrovmaksim** [comment]
Looks like it's working, but `gas` should be capped at 15_000_000 in the relay
