### ISSUE TITLE
`eth_getLogs` not handling non int block params

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#472]
### Description

Currently the `eth_getLogs` endpoint parses the `fromBlock` and `toBlock` without consideration for non int values.
This results in the block time frames not being honoured

See [eth.getLogs](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L1153) where `parseInt(toBlock)` and `parseInt(fromBlock)` are used.

These should apply the `blockNumberOrTag` logic used by the other methods

### Steps to reproduce

1. `curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":"2","method":"eth_getLogs","params":[{ "fromBlock": "0x0", "toBlock": "latest", "addresss": "0x0000000000000000000000000000000002dC46Db"}]}' http://localhost:7546`
2. Results in a `blocks?block.number=lte:NaN&block.number=gte:0&order=asc 400 status`

### Hedera network

previewnet

### Version

v0.6.0

**Comment by Nana-EC** [comment]
Fix will like take the form of updating [eth.getLogs()](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L1153)
before
```ts
      if (toBlock) {
        // @ts-ignore
        filters.push(`lte:${parseInt(toBlock)}`);
        order = constants.ORDER.DESC;
      }
      if (fromBlock) {
        // @ts-ignore
        filters.push(`gte:${parseInt(fromBlock)}`);
        order = constants.ORDER.ASC;
      }
```

after
```ts
      if (toBlock) {
        const blockNumber = await this.translateBlockTag(toBlock, requestId);
        // @ts-ignore
        filters.push(`lte:${blockNumber}`);
        order = constants.ORDER.DESC;
      }
      if (fromBlock) {
        const blockNumber = await this.translateBlockTag(fromBlock, requestId);
        // @ts-ignore
        filters.push(`gte:${blockNumber}`);
        order = constants.ORDER.ASC;
      }
```

**Comment by Nana-EC** [comment]
> Wouldn't `translateBlockTag` potentially add more requests to the mirror node? I was wondering if we could do it another way. So earliest is `0` this one should be easy, and `latest` and `pending` should be the last block at the time of the query(?)
> 
> In the case of `fromBlock` being `latest` or `pending`, doesn't this mean that we should only take the last block, e.g. query the blocks by `desc` order and limit to 1?
> 
> In the case of `toBlock` being `latest` or `pending`, this should mean we want to take all blocks until the last one, so wouldn't just not setting `lte:` cover that?

@dimitrovmaksim actually made more progress on this, below is where i got to.
Challenge is the mirror node rejects time ranges greater than 7 days.
We should decide what we want to do, potentially return an error highlighting this with a suggestion of the potential blocks they could make requests for

```ts
      if (toBlock) {
        const blockResponse = await this.getHistoricalBlockResponse(toBlock, true, requestId);
        // @ts-ignore
        params.timestamp = [`lte:${blockResponse?.timestamp?.to}`];
        order = constants.ORDER.DESC;
      }
      if (fromBlock) {
        const blockResponse = await this.getHistoricalBlockResponse(fromBlock, undefined, requestId);
        // @ts-ignore
        if (params.timestamp) {
          params.timestamp.push(`gte:${blockResponse?.timestamp?.from}`);
        } else {
          params.timestamp = [`gte:${blockResponse?.timestamp?.from}`];
        }
        order = constants.ORDER.ASC;
      }
```

**Comment by dimitrovmaksim** [comment]
Many JSON-RPC providers limit the block range for eth_getLogs, bsc is 5000, Infura I think is 10_000, so I guess its fine to have a limit and return an error if the range exceeds the limit.

Wouldn't this [`lte:${blockResponse?.timestamp?.to}`] result in `lte:undefined` if there's no blockResponse? which will result in `{"_status":{"messages":[{"message":"Invalid parameter: timestamp"}]}}`.

**Comment by Nana-EC** [comment]
@dimitrovmaksim good points.

Let's start with a configureable limit of 500 and the error message

Regarding the toBlock, for the mean time as a band aid, let's 
- also ask for the latest block and get that timestamp
- compare that to the toBlock response and take the min of the timestamps.

Also open a ticket against mirror node with your suggestion that we can adopt at a later time

**Comment by dimitrovmaksim** [comment]
To sum it up:
1. Default limit is 500 blocks, but can be configurable (max limit ?)
3. Use `getHistoricalBlockResponse` to fetch the block by either number or tag
4. If `toBlock` is null or `getHistoricalBlockResponse` for `toBlock` returns `Not Found` => fetch `latest` instead
5. If `fromBlock` is not passed,  assume it's 0
6. if `fromBlock` is passed, but `getHistoricalBlockResponse` returns `Not Found` return an empty Logs array
8. Check if `toBlock` - `fromBlock` is `less than or equal` to the set limit
5. Use the timestamps from the from and to Blocks to fetch the logs
