### ISSUE TITLE
Allow for batch requests

### ISSUE THREAD

**Issue by tom-hbar** [hashgraph/hedera-json-rpc-relay#476]
### Problem

Currently, the relay doesn't allow for batch requests. Instead, clients must make multiple individual requests. It would be great if clients could make multiple calls in a single request, as per the JSON RPC spec here: https://www.jsonrpc.org/specification#batch

### Solution

- The relay accepts an array of json objects (multiple calls) as the payload
- The relay processes these requests and returns an array of json objects (responses)

**Comment by Nana-EC** [comment]
Thanks @tom-hbar 
This a is a similar suggestion to #395 
We're currently do not have this on our roadmap but will accept community attempts to address this.

**Comment by Nana-EC** [comment]
Batch requests are now supported. Relay must have `BATCH_REQUESTS_ENABLED` enabled.
