### ISSUE TITLE
Explore initial support for Trust Wallet

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#478]
### Problem

The JSON RPC provides EIP interfaces for wallets to integrate with Hedera.
It's unclear what coverage and gaps may exist for Trust Wallet with current functionality.

### Solution

Explore current coverage and take initial steps to manage gaps.

**Comment by natanasow** [comment]
**Wallet core PR**
- https://github.com/trustwallet/wallet-core/pull/2570

**Asssets PR** 
- https://github.com/trustwallet/assets/pull/22377

**Comment by Nana-EC** [comment]
External PRs addressed
