### ISSUE TITLE
According to some docs `eth_getLogs` address params could be either a single address or an array of addresses

### ISSUE THREAD

**Issue by dimitrovmaksim** [hashgraph/hedera-json-rpc-relay#486]
### Problem

According to some providers docs `eth_getLogs` address param should either be a single address or an array of addresses:
https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getlogs
https://www.quicknode.com/docs/ethereum/eth_getLogs
https://docs.alchemy.com/reference/eth-getlogs

According to Infura's doc the `address` param seems to be only a single address https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_getlogs

Also looking at the graph node code, it sends the address param as an array:
https://github.com/graphprotocol/graph-node/blob/7e4443a99147687b1aca65f74160b6daa310b2a3/chain/ethereum/src/adapter.rs#L76
https://github.com/graphprotocol/graph-node/blob/b79c21e8f335024c4464127c49aab6c513be9cce/chain/ethereum/src/ethereum_adapter.rs#L254

But currently the `getLogs` function expects address to be `string | null` https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L1129

### Solution

See if/how this could be handled by the relay and the mirror node

**Comment by Nana-EC** [comment]
@dimitrovmaksim to clarify are you saying this would block the-graph support?
I guess the suggestion here would be support `string[] | string | null` instead of `string | null` correct?

**Comment by dimitrovmaksim** [comment]
> @dimitrovmaksim to clarify are you saying this would block the-graph support? I guess the suggestion here would be support `string[] | string | null` instead of `string | null` correct?

I think I encountered an issue with that, I think when trying a subgraph with two datasources, e.g. index two contracts, will try to reproduce it, now that most of the other issues are resolved.

**Comment by dimitrovmaksim** [comment]
Testing a subgraph with two datasources/contracts

`hedera-json-rpc-relay/packages/server/src/server.ts` eth_getLogs:

params.address:
```
[
  '0x0000000000000000000000000000000000000409',
  '0x000000000000000000000000000000000000040a'
]
```

`hedera-json-rpc-relay/packages/relay/src/lib/eth.ts` getLogs:
address
```
[
  '0x0000000000000000000000000000000000000409',
  '0x000000000000000000000000000000000000040a'
]
```

The following response to the mirror node:

```
[2022-09-01 18:22:07.722 +0000] DEBUG (mirror-node/74747 on Maksims-MacBook-Pro.local): [Request ID: ab06fc16-d8b1-48a5-8a82-d35e88acff8b] [GET] contracts/0x0000000000000000000000000000000000000409,0x000000000000000000000000000000000000040a/results/logs?timestamp=gte:1662056320.672925545&timestamp=lte:1662056320.672926049&topic0=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 400 status
```

Still it is able to catch the event and save the entity, maybe there's a fallback.

**Comment by dimitrovmaksim** [comment]
Update: A subgraph with two dataSources seems to be working fine

**Comment by Kalina-Todorova** [comment]
Verified. In case we want to support a list of addresses - this would require mirror-node changes and given this is currently not a blocker we're closing this issue.
