### ISSUE TITLE
Add an example subgraph project in the relay

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-json-rpc-relay#487]
### Problem

The Graph <> Hedera integration is on the works and after the first iteration performed here: https://github.com/hashgraph/hedera-json-rpc-relay/issues/414 we can add an example subgraph project in the relay repo as we have for hardhat, truflle, etc.. and describe what it currently does and does not support along with instructions on how to run it.

### Solution

Suggestion is to add the example project here: https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/tools

**Comment by Nana-EC** [comment]
Let's get the progress made into a `the-graph` dir under tools like you mentioned.
A README can capture an overview of current status and whats missing.
Don't yet add it to the README under tools.

Let's also open tickets for any remaining items that would allow a complete graph node.
