### ISSUE TITLE
Nightly UI Test (dapp-example)

### ISSUE THREAD

**Issue by rustyShacklefurd** [hashgraph/hedera-json-rpc-relay#491]
### Problem

It would be beneficial to have a nightly run of the dapp-example test running for an environment.  This will help indicate if a deployment is having issues that may not be picked up immediately; specifically this can help identify and verify the health of endpoints used for calls.

### Solution

Initially this seems to be suited as cronjob with a configurable time to run this test.  This would allow for tests to be schedule during low usage times.

### Alternatives

Another solution could be to add this check to the liveness gates of the pod.  It is unknown what the trigger or scheduling  for a liveness gate is so some research would be required.

**Comment by Nana-EC** [comment]
@ebadiere might be worth syncing with devops on this in next sprint to see if it's still applicable and covered by your efforts

**Comment by beeradb** [comment]
Currently, the [dapp tests](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/.github/workflows/dapp.yml) run on every merge to main or a release branch and for every tag. 

I think we can close this issue out as completed.
