### ISSUE TITLE
Contract address attribute does not correspond with actual contract address

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#498]
### Description

In the [deployContract hardhat script](https://github.com/hashgraph/hedera-json-rpc-relay/blob/7c2c8ab2f1ce40b4b6f1ecedebb61cd0cc212d2d/tools/hardhat-example/scripts/deployContract.js#L28) `greeter.address !== contractAddress`, whereas they should be equal.
```js
console.log(greeter.address) // looks something like: 0x9CBfA9F814D590a92b0EE473941b7e9a86D2c1Fa
console.log(contractAddress) // looks something like: 0x000000000000000000000000000000000000055B
```

### Steps to reproduce

1. Add console logs to demonstrate the inequality

### Hedera network

other

### Version

relay v0.6.0

### Operating system

macOS

**Comment by Nana-EC** [comment]
@mshakeg thanks for the ticket.

Unfortunately, this is an issue with ethersjs.
We've captured the issue and workaround [here](https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/tools#supported-tools)

**Comment by mshakeg** [comment]
@Nana-EC I see, it might be worthwhile making a change to ethersjs such that on `contract.deployTransaction` resolving to update the contract `address` attribute internally for improved compatibility with hedera. But that'll obviously have to go through their review, which isn't guaranteed.

**Comment by Nana-EC** [comment]
> @Nana-EC I see, it might be worthwhile making a change to ethersjs such that on `contract.deployTransaction` resolving to update the contract `address` attribute internally for improved compatibility with hedera. But that'll obviously have to go through their review, which isn't guaranteed.

Yep 100%
See thread in https://github.com/hashgraph/hedera-json-rpc-relay/issues/193
