### ISSUE TITLE
Update relay SDK with connection management logic

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#508]
### Problem

During upgrades of the network or long connection times the SDK sometimes encounters issues blocking cals that rely on teh network node

### Solution

Update the SDK to set connection related properties to allow for long lived connections but also retries across different nodes.

Considerations include [Client settings](https://github.com/hashgraph/hedera-sdk-js/blob/main/src/client/Client.js#L122) 
- setMaxAttempts - Set it to 1 for immediate failure, 2 for retry with another node.
- setMaxBackoff
- setMinBackoff
- setRequestTimeout

**Comment by danielakhterov** [comment]
Hmm, I'm not sure if any of those options are really going to help for *long lived connections* as they don't really have anything to do with that. I guess it really depends on the errors. If the errors you're getting are a result of the nodes returning gRPC status errors then increasing the max attempts should help, but again it really depends on the errors. Another option which I think is silly but could work is reconstructing the client every so often. This would force new connections to be created, but it would clear the current backoff state per node that the old client had. We don't currently support any options to indicate the SDK should reconnect every so often, but maybe we should?

**Comment by Nana-EC** [comment]
@natanasow i'll leave you to investigate this a bit more. 
If there's nothing to be done I can put it back in the backlog and we can circle back once we have logs exposing the underlying issue.

**Comment by Nana-EC** [comment]
Putting back, let's see what the improved logging surfaces.
Additionally, we might want to update readiness check to go down for specific SDK errors

**Comment by Nana-EC** [comment]
`setRequestTimeout` is set.
Other configs weren't required with updated relay and SDK logic.
