### ISSUE TITLE
Configurable transaction timeout for sdkClient

### ISSUE THREAD

**Issue by Ivo-Yankov** [hashgraph/hedera-json-rpc-relay#569]
### Problem

There is no configurable timeout for the sdkClient. It is currently hardcoded to 10s

### Solution

Make it possible to configure the transaction timeout period in the sdkClient. Depends on: https://github.com/hashgraph/hedera-sdk-js/issues/1276

**Comment by Nana-EC** [comment]
timeout support was added to relay
