### ISSUE TITLE
Unit tests for HBAR Rate limit

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#582]
### Problem

There are no unit test for the hbar rate limiter. We need to cover this functionality.

### Solution

Add unit tests to test `shouldLimit`, `addExpenses`, `shouldResetLimiter`

**Comment by Nana-EC** [comment]
@georgi-l95 when addressing this can you add logic for

Enable flag that is set to false when a valid `HBAR_RATE_LIMIT_TINYBAR` and `HBAR_RATE_LIMIT_DURATION` is not set. This will support enabling and disabling
-  add checks for `this.enabled` in
   - `constructor()`, if false don't set other variables. This will require other variables to have a default value (mostly 0)
   - `shouldLimit()`, if false return false
   - `addExpense()` if false don't  decrement
