### ISSUE TITLE
HTS NFTs not supported in Metamask mobile wallet

### ISSUE THREAD

**Issue by Ashe-Oro** [hashgraph/hedera-json-rpc-relay#583]
### Problem

HTS NFTs are not supported by Metamask mobile app. When attempting to add an HTS NFT, the metamask mobile wallet errors with `Personal address detected. Input the collectible contract address`

![image](https://user-images.githubusercontent.com/5784328/193690733-3bf2aef7-f7b4-4e4d-95c3-9914ac0496b6.png)

Note: User is able to add the same NFT Collection (ie token_id) to the Metamask chrome extension. 

Details:
Platform: Hedera testnet
token_id: 0.0.48014385
evmAddress: `0x0000000000000000000000000000000002dca431`
OS: Android 13 
MM version: 5.7.0 (972)

Steps to reproduce: 
1. Create HTS NFT and send to your account
2. Open MM mobile wallet select "NFTs"
3. Click "import NFTs" 
4. Enter Address and ID of the NFT which is already in your account. 
5. Note error message `Personal address detected. Input the collectible contract address`

To test ERC721 tokens, do the exact same steps with an ERC721 asset in your account. 

### Solution

So on MM mobile, it specifically asks for the contract address and ID whereas the chrome extension does *NOT* ask for ID. The ID here is the serial number of the NFT. 

I have no issues adding a Hedera ERC721 NFT asset to MM mobile, only HTS NFTs.

**Comment by dimitrovmaksim** [comment]
Hey, the issue here is that HTS token addresses are actually account addresses and not contract addresses, this is why you get the `Personal address detected. Input the collectible contract address` error. I'm not sure if anything can be done about this

**Comment by georgi-l95** [comment]
Hey, @Ashe-Oro 
This problem will be fixed with this PR https://github.com/hashgraph/hedera-json-rpc-relay/pull/598 . You can try again to add your NFT when this change get to testnet. If you are still experiencing issues, reopen this issue or open another one.
