### ISSUE TITLE
Improve tiered rate limit for dev tools

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#609]
### Problem

Through testing it was seen that both Truffle and he Graph make a large number of calls on known functions.
The relays default IP rate limiting does not allow for this large number and rate limits

### Solution

Improve the rate limiting logic for dev tools
- Increase `TIER_2_RATE_LIMIT` to something like 1000
- Increase `TIER_3_RATE_LIMIT` to something like 2000
- Verify truffle contract deployment and the graph operations work
  - if not bump `eth_getBlockByNumber`, `eth_blockNumber` and `eth_getTransactionReceipt` down to use `TIER_3_RATE_LIMIT`
- Update defaults values in docs etc
- Explore if caching should be reorganized or improved to reduce rate limit likeliness and improve dev tools experience

**Comment by georgi-l95** [comment]
After some research, I found that only `truffle` and `the graph` are hard on request from `TIER_2`. Truffle makes a lot request during deployment to `eth_getBlockByNumber` , `eth_blockNumber`, `eth_chainId`, `eth_getTransactionReceipt`. While The Graph is making a lot of requests to mainly, while catching up with consumption of blocks `eth_getBlockByNumber` and `eth_getBlockByHash` , afterwards only once for every new block. Good thing about `The Graph` is that, even if it gets rate limited, it continues again when the rate limit is renewed. 

For deploying big contracts with truffle usually around 400-500 requests are enough, although I would suggest bumping this number with 50%, for example, just to be sure.

Caching of `eth_chainId` is possible, but for the other function would be tricky.
