### ISSUE TITLE
Support for shadow forks

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hedera-json-rpc-relay#633]
As a developer, I would like to be able to write unit tests, execute them locally but use the state of mainnet. It is common for developers to develop more and more protocols that interact with each other, f.e smart contracts that interact with a DEX. In other EVM ecosystems, the solution to that is through shadow forks. This means that tests are executed on a local EVM network, but the storage is loaded from another network (f.e mainnet).

In order for this to be enabled, rpc endpoints such as `eth_getStorageAt` must be supported. The endpoint can be supported once the `eth_call` and `eth_debug*` endpoints are supported and the EVM module is introduced in the Mirror node.

Examples of tools:
- https://book.getfoundry.sh/forge/fork-testing
- https://hardhat.org/hardhat-network/docs/guides/forking-other-networks

**Comment by acuarica** [comment]
Hi @Daniel-K-Ivanov thanks for opening this.

The Relay has supported both `eth_getCode` and `eth_getStorageAt` for a while now. Thus, fork testing should be supported by the Relay.

I'm closing this, but please feel free to reopen the issue if you encounter any problem (in particular if you're using Hedera-specific services).
