### ISSUE TITLE
The log object should return the evm address not the hedera entity address

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#644]
### Description

According to the [eth json rpc spec](https://github.com/etclabscore/ethereum-json-rpc-specification/blob/97178e7dc3b417318e2977171254f6e21d080076/openrpc.json#L1250) the log object address(i.e. `Log.address`) should be the evm address of the contract that emitted the event. However, the relay currently returns the Hedera entity id for the contract in evm address format(e.g. `0x0000000000000000000000000000000000000409` i.e. _0.0.1033_) when it should instead return the actual evm address of the contract i.e. either the `create1` or `create2` address.

A known impact is on the [subgraph data source templates](https://thegraph.com/docs/en/developing/creating-a-subgraph/#instantiating-a-data-source-template) that enables the subgraph to index logs on created contracts. For example, a `Factory` contract creates a `Child` contract and the `Factory` emits an event(say `ChildCreated`) containing the `create2` address of the `Child` contract. The subgraph handler for this `ChildCreated` event has access to the `create2` address from the `event.params` and creates a template index for that `Child` contract. However since the Hedera relay returns the Hedera entity id for the `Child` contract instead of the evm address on `Log.address` the `Child` contract's logs aren't indexed(at least for `create2` contract's at this point since `create1` addresses are currently identical to the contract's entity id).

### Steps to reproduce

1. Pull and checkout to [this branch]()
2. Start up the hedera local node
3. Start up the local graph node
4. Run `npm run test:hgf` to deploy and test the `GreeterFactory` and created `Greeter` contracts
5. In the `subgraph-example` update the `GreeterFactory` `address` and `startBlock` accordingly
6. create and deploy the subgraph to the local graph node
7. Observe that the child Greeter contract using `create1` has been [templated correctly](https://github.com/hashgraph/hedera-json-rpc-relay/pull/642/files#r999654754) as it's `handleGreetingSet` event handler has been called accordingly and observe that the child `Greeter` contract using `create2` has [not been templated correctly](https://github.com/hashgraph/hedera-json-rpc-relay/pull/642/files#r999656054) as it's handleGreetingSet is not triggered due to the address mismatch.

### Hedera network

other

### Version

@hashgraph/hedera-local@2.0.1

### Operating system

macOS

**Comment by dimitrovmaksim** [comment]
Hey, this would seem to be more of a services issue, because the relay just forwards the data that comes from the mirror node in a evm compatible format. I'll check with the services team

**Comment by mshakeg** [comment]
@dimitrovmaksim thanks, I suspected as much as the mirror node contract logs endpoint also has this issue.

**Comment by dimitrovmaksim** [comment]
So it seems with create2 the factory contract emits the alias address of the child contract, but the logs from the child contract use the long-zero address, which as you said is a problem for the dynamic datasource templates in the subgraph

**Comment by mshakeg** [comment]
@dimitrovmaksim that's correct, given the simplicity of the fix, can you comment on when you think it'll be out on testnet?

**Comment by dimitrovmaksim** [comment]
Sorry, I can't provide any ETAs

**Comment by stoqnkpL** [comment]
Hi @mshakeg! We will resolve this on the consensus node side. We will open a PR with a fix next week.

**Comment by stoqnkpL** [comment]
> Hi @mshakeg! We will resolve this on the consensus node side. We will open a PR with a fix next week.

Update: may need to discuss further with other core devs. Seems this was considered earlier and resolving it may not be straightforward. Context: https://github.com/hashgraph/hedera-services/pull/2919#discussion_r815179445

**Comment by mshakeg** [comment]
@stoqnkpL hmm, since the eth json rpc spec requires the address to be the evm(alias) address and not the hedera entity address the hedera relay should abide by this in either of the following ways(as far as I can think of):
1. The relay should overwrite the hedera entity address returned by the core layer with the evm(alias) address OR
2. In the core layer if a transaction is an ethereum transaction(i.e. a transaction submitted via the relay) the log address should be the evm(alias) address otherwise the log address can remain as is i.e. the hedera entity id address.

**Comment by dimitrovmaksim** [comment]
This PR https://github.com/hashgraph/hedera-json-rpc-relay/pull/650 should fix this temporarily, until more permanent solution is made in the mirror-nide. Reopening for visibility

**Comment by Nana-EC** [comment]
https://github.com/hashgraph/hedera-mirror-node/pull/4807 resolves this from Mirror Node side (0.69) so we can now close this
