### ISSUE TITLE
Intermittent failure of contract deploys and calls running on local node

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#645]
### Description

The local node appears to nondeterministically fail with the following error thrown on `ethers.ContractFactory.deploy`(i.e. `eth_sendRawTransaction`) or `ethers.Contract.methodCall`(i.e. `eth_call`/`eth_sendtransaction`):
```
     Unknown error invoking RPC
  ProviderError: HttpProviderError
      at HttpProvider.request (/Users/anon/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
      at LocalAccountsProvider.request (/Users/anon/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async EthersProviderWrapper.send (/Users/anon/node_modules/@tenderly/hardhat-tenderly/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```
The above error though occasionally occurring nondeterministically can be triggered deterministically by NOT setting the ethers overrides `gasLimit` sufficiently high OR by not setting it at all(which if the default `gasLimit` is not sufficient will trigger the above error). The above error is also more likely to occur if multiple **LARGE** contracts are deployed/created in immediate sequence. The above error happens around the same time as the following relay error is logged:
```
[2022-10-19 09:25:30.738 +0000] ERROR (rpc-server/50 on 82abc0524699): [Request ID: 9fa4daff-7641-4038-8157-9e94ef7adf87] [POST] eth_getTransactionByHash: -32603 6 ms
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'toString')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'toString')
              at Function.numberTo0x (/home/node/app/packages/relay/dist/lib/eth.js:834:41)
              at EthImpl.<anonymous> (/home/node/app/packages/relay/dist/lib/eth.js:761:43)
              at Generator.next (<anonymous>)
              at fulfilled (/home/node/app/packages/relay/dist/lib/eth.js:24:58)
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
    }
```

### Steps to reproduce

1. As mentioned the issue is nondeterministic and the cause unknown, except for the case where this error can be forced by the setting the `gasLimit`(either ethers default or otherwise specified) to an insufficient value(presumably the relay returns a `CONTRACT_REVERTED` or related error). Multiple successive deployments of **LARGE** contracts may cause the issue due to the consensus node's `gasLimit/s`(15m/s IIRC) being reached(presumably causing the transactions to be dropped and considered reverted by the relay).

### Hedera network

other

### Version

@hashgraph/hedera-local@2.0.1

### Operating system

macOS

**Comment by dimitrovmaksim** [comment]
Hey, I suspect this may be related to this Issue https://github.com/hashgraph/hedera-json-rpc-relay/issues/606 which has been resolved by this PR https://github.com/hashgraph/hedera-json-rpc-relay/pull/610

**Comment by dimitrovmaksim** [comment]
From the error, something is being returned as undefined, or a property is missing from the response body when doing `eth_getTransactionByHash` , that then the relay is trying to convert to hex string, but is failing.

**Comment by mshakeg** [comment]
@dimitrovmaksim I see, so presumably the relay returns a success response(for (1.)`eth_sendRawTransaction` or (2.)`eth_sendtransaction`) which doesn't have the transactionHash for some reason(possibly due to the (1.) or (2.) failing) and ethers assuming a success response makes a relay call to `getTransactionByHash` with hash undefined and since the relay doesn't validate params the above relay error is thrown.

I think #651 would address the latter issue, but I don't think there's an issue that specifically aims to address the former issue which is the root problem here.

**Comment by dimitrovmaksim** [comment]
You see there's a request id in the logs for the toString error, can you post all logs for that request id, it may give me more context what is happening. But probably i'll have to reproduce the case and debug it.

**Comment by mshakeg** [comment]
@dimitrovmaksim it seems the txHash is being sent, I've attached all logs with the same request id below:
```
[2022-10-25 17:11:41.812 +0000] DEBUG (rpc-server/50 on 6ea64ea8e9fc): [Request ID: f6811a67-e6e1-499b-81a8-38772fceaece] eth_getTransactionByHash
[2022-10-25 17:11:41.812 +0000] TRACE (relay-eth/50 on 6ea64ea8e9fc): [Request ID: f6811a67-e6e1-499b-81a8-38772fceaece] getTransactionByHash(hash=0x98f456a957cd27c685dbde2c9550860269b9376136006379e1dca55de57f51c6)
[2022-10-25 17:11:41.819 +0000] DEBUG (mirror-node/50 on 6ea64ea8e9fc): [Request ID: f6811a67-e6e1-499b-81a8-38772fceaece] [GET] contracts/results/0x98f456a957cd27c685dbde2c9550860269b9376136006379e1dca55de57f51c6 200 7 ms
[2022-10-25 17:11:41.827 +0000] DEBUG (mirror-node/50 on 6ea64ea8e9fc): [Request ID: f6811a67-e6e1-499b-81a8-38772fceaece] [GET] accounts/0x0000000000000000000000000000000000000002 404 status
[2022-10-25 17:11:41.827 +0000] ERROR (rpc-server/50 on 6ea64ea8e9fc): [Request ID: f6811a67-e6e1-499b-81a8-38772fceaece] [POST] eth_getTransactionByHash: -32603 15 ms
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'toString')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'toString')
              at Function.numberTo0x (/home/node/app/packages/relay/dist/lib/eth.js:892:41)
              at EthImpl.<anonymous> (/home/node/app/packages/relay/dist/lib/eth.js:819:43)
              at Generator.next (<anonymous>)
              at fulfilled (/home/node/app/packages/relay/dist/lib/eth.js:24:58)
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
    }
[2022-10-25 17:11:41.828 +0000] ERROR (rpc-server/50 on 6ea64ea8e9fc): returning error to sender: [Request ID: f6811a67-e6e1-499b-81a8-38772fceaece] Unknown error invoking RPC
```

**Comment by dimitrovmaksim** [comment]
That shouldn't be an issue. 

If you can simulate this locally, can you then go to `http://localhost:5551/api/v1/contracts/results/<the contract address from the log>`
And post the response

**Comment by mshakeg** [comment]
@dimitrovmaksim do you mean `http://localhost:5551/api/v1/contracts/results?from=<the contract address from the log>`? as `http://localhost:5551/api/v1/contracts/results/<txIdOrHash>` would match your path.

**Comment by dimitrovmaksim** [comment]
Like this one `contracts/results/0x98f456a957cd27c685dbde2c9550860269b9376136006379e1dca55de57f51c6` from the logs

**Comment by mshakeg** [comment]
@dimitrovmaksim ok, the txHash, your original message seems to imply the contract address.

I restarted the local node so the intermittent issue now happened elsewhere in the test, the response of the mirror call is:
```
{"amount":0,"bloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","call_result":"0x","contract_id":null,"created_contract_ids":[],"error_message":"INVALID_ACCOUNT_ID","from":"0x0000000000000000000000000000000000000002","function_parameters":"0x","gas_limit":0,"gas_used":0,"timestamp":"1666720696.873406594","to":null,"hash":"0x","block_hash":"0x46331c87ec277042f20c3e0781828bff5cb10aea52b13b6e44991add49f10a73329b41540db28a7dfb5d7523eec123a5","block_number":482,"logs":[],"result":"UNKNOWN","state_changes":[],"status":"0x0","failed_initcode":null,"access_list":"0x","block_gas_used":0,"chain_id":"0x12a","gas_price":"0x48","max_fee_per_gas":"0x","max_priority_fee_per_gas":"0x","r":"0x3a48763ace69f4275e1ab2e612ef1e15857e54c569d974753af59eae45ea48df","s":"0x9c26241a796ec32b47e32469a251722f0a60bbe742c957524d1a0afea1daea","type":0,"v":0,"nonce":69}
```

**Comment by dimitrovmaksim** [comment]
Oh yeah, my bad, it's the tx hash

**Comment by dimitrovmaksim** [comment]
From what I'm seeing the response is missing the `transaction_index` property

**Comment by mshakeg** [comment]
@dimitrovmaksim  I'm not sure what the `transaction_index` is, but it sounds similar to the `nonce`, which does exist.

Is there anything else you'd like me to do or have you been able to replicate the issue locally?

**Comment by dimitrovmaksim** [comment]
Transaction index is the position of the transaction in the block, nonce is the number of transactions sent by an address

**Comment by dimitrovmaksim** [comment]
Sorry, currently I'm not near my work computer so i haven't been able to test it, I have been responding from my phone.

**Comment by mshakeg** [comment]
@dimitrovmaksim I see, so perhaps the tx is dropped and hence isn't in the block possibly due to the block gasLimit constraint.

No worries, it's also late where you are, so we can continue tomorrow if you'd like.

**Comment by dimitrovmaksim** [comment]
Btw is this still using local-node 2.0.1? Have you tried using 2.1.x?

**Comment by mshakeg** [comment]
@dimitrovmaksim I updated to 2.1.0 since for the local hashscan.

**Comment by dimitrovmaksim** [comment]
Thanks for your help! I'll share the fidings tomorrow on the daily meeting with the team to investigate further

**Comment by mshakeg** [comment]
@dimitrovmaksim just wanted to check back with you on the team's progress. Sorry for the seeming lack of patience, but it's really frustrating having to comment out all but one test case, execute that single test case, and then restart the local node before proceeding to the next test case.

**Comment by dimitrovmaksim** [comment]
Currently I don't have an update, sorry

**Comment by mshakeg** [comment]
@dimitrovmaksim hmm, ok, hopefully soon 🤞. I suspect `INVALID_ACCOUNT_ID` is due to account `0.0.2` being _not found_ for some reason at least at the mirror level; `http://localhost:5551/api/v1/accounts/0x0000000000000000000000000000000000000002` returns _404_:
```
{"_status":{"messages":[{"message":"Not found"}]}}
```

**Comment by dimitrovmaksim** [comment]
What is the response for this request in the mirror node? `[2022-10-25 17:11:37.226 +0000] DEBUG (mirror-node/50 on 6ea64ea8e9fc): [Request ID: 3ff7f6b2-766f-4ecf-93f6-ca6187810476] [GET] accounts/0x67D8d32E9Bf1a9968a5ff53B87d777Aa8EBBEe69 200 9 ms` ?

**Comment by mshakeg** [comment]
@dimitrovmaksim from a recent run, the response seems fine.
NB: only the latest 3 transactions are shown.
```
{
  "account": "0.0.1012",
  "alias": "HIQQFM6GIFAY5CKFFTKSAKW72R2Y6RM2ZOHDMT3UD7IWZUW3PGBV2OOS",
  "auto_renew_period": 7776000,
  "balance": {
    "balance": 979552000000,
    "timestamp": "1666859090.886299885",
    "tokens": []
  },
  "created_timestamp": "1666858526.456030470",
  "decline_reward": false,
  "deleted": false,
  "ethereum_nonce": 82,
  "evm_address": "0x67d8d32e9bf1a9968a5ff53b87d777aa8ebbee69",
  "expiry_timestamp": null,
  "key": {
    "_type": "ECDSA_SECP256K1",
    "key": "02b3c641418e89452cd5202adfd4758f459acb8e364f741fd16cd2db79835d39d2"
  },
  "max_automatic_token_associations": 0,
  "memo": "auto-created account",
  "pending_reward": 0,
  "receiver_sig_required": false,
  "staked_account_id": null,
  "staked_node_id": null,
  "stake_period_start": null,
  "transactions": [
    {
      "bytes": null,
      "charged_tx_fee": 340800000,
      "consensus_timestamp": "1666859044.904255350",
      "entity_id": "0.0.1104",
      "max_fee": "200000000",
      "memo_base64": "",
      "name": "ETHEREUMTRANSACTION",
      "node": "0.0.3",
      "nonce": 0,
      "parent_consensus_timestamp": null,
      "result": "SUCCESS",
      "scheduled": false,
      "transaction_hash": "Rei5n7tglowaoZncOd1ImFQQ68Dqm/RRtTky7pp6c6y5sKJjnKUs8rH63BibCj2x",
      "transaction_id": "0.0.2-1666859034-975098114",
      "transfers": [
        {
          "account": "0.0.98",
          "amount": 340800000,
          "is_approval": false
        },
        {
          "account": "0.0.1012",
          "amount": -340800000,
          "is_approval": false
        }
      ],
      "valid_duration_seconds": "120",
      "valid_start_timestamp": "1666859034.975098114"
    },
    {
      "bytes": null,
      "charged_tx_fee": 113600000,
      "consensus_timestamp": "1666859040.160338598",
      "entity_id": "0.0.1077",
      "max_fee": "200000000",
      "memo_base64": "",
      "name": "ETHEREUMTRANSACTION",
      "node": "0.0.3",
      "nonce": 0,
      "parent_consensus_timestamp": null,
      "result": "SUCCESS",
      "scheduled": false,
      "transaction_hash": "biyeNocwnknf4knMJ1c73N2ptp41mlgDoK1kMOn7sNkOAkwy4d1jWwg3ft+R3EQ/",
      "transaction_id": "0.0.2-1666859028-970312333",
      "transfers": [
        {
          "account": "0.0.98",
          "amount": 113600000,
          "is_approval": false
        },
        {
          "account": "0.0.1012",
          "amount": -113600000,
          "is_approval": false
        }
      ],
      "valid_duration_seconds": "120",
      "valid_start_timestamp": "1666859028.970312333"
    },
    {
      "bytes": null,
      "charged_tx_fee": 113600000,
      "consensus_timestamp": "1666859035.451572720",
      "entity_id": "0.0.1074",
      "max_fee": "200000000",
      "memo_base64": "",
      "name": "ETHEREUMTRANSACTION",
      "node": "0.0.3",
      "nonce": 0,
      "parent_consensus_timestamp": null,
      "result": "SUCCESS",
      "scheduled": false,
      "transaction_hash": "xlZygT6PC7eZTaHgyqcmZWqeTKIppvDsGe1SlBS9wwd9a8YIzR6Yv6sXnXQGlR1E",
      "transaction_id": "0.0.2-1666859024-813217660",
      "transfers": [
        {
          "account": "0.0.98",
          "amount": 113600000,
          "is_approval": false
        },
        {
          "account": "0.0.1012",
          "amount": -113600000,
          "is_approval": false
        }
      ],
      "valid_duration_seconds": "120",
      "valid_start_timestamp": "1666859024.813217660"
    },
    ...
  ],
  "links": {
    "next": "/api/v1/accounts/0x67D8d32E9Bf1a9968a5ff53B87d777Aa8EBBEe69?timestamp=lt:1666858898.311595004"
  }
}
```

**Comment by dimitrovmaksim** [comment]
0.0.2 is a predefined/genesis account, that is used to pay for the transactions made by the relay, that account should be created when the consensus-node is started

**Comment by mshakeg** [comment]
@dimitrovmaksim the mirror returning 404 for account 0.0.2 might not be the issue as even on a fresh restart it returns that.

**Comment by dimitrovmaksim** [comment]
It seems there's been a fix for that, you can request the 0.0.2 in the testnet mirror node, but it seems that did not go into the current local node. We keep digging

**Comment by mshakeg** [comment]
@dimitrovmaksim I see, the first account that the current local mirror does NOT return a 404 is _0.0.1002_

**Comment by mshakeg** [comment]
@stoqnkpl I'm also doubtful that's the full issue but it does at least seem to be in part the issue given the `eth_sendRawTransaction EthereumTransaction record status: INVALID_ACCOUNT_ID (15)` error on a transaction by account 0.0.2

**Comment by stoqnkpL** [comment]
> @stoqnkpL I'm also doubtful that's the full issue but it does at least seem to be in part the issue given the `eth_sendRawTransaction EthereumTransaction record status: INVALID_ACCOUNT_ID (15)` error on a transaction by account 0.0.2

The `INVALID_ACCOUNT_ID` status may not be related to account `0.0.2`. The EthereumTransaction has a `sender` account (corresponding to an account existing in Hedera that has an alias - the ECDSA key that signed the Ethereum transaction). I think that's where we should look.

**Comment by mshakeg** [comment]
@dimitrovmaksim @stoqnkpL presumably the `sender` is encoded in the `eth_sendRawTransaction`'s data, I'm not sure how to decode and extract it and confirm if the `sender` is an issue.

eth_sendRawTransaction data from [this message](https://github.com/hashgraph/hedera-json-rpc-relay/issues/645#issuecomment-1290962563):
```
0xf88a2585a7a3582000831e848094000000000000000000000000000000000000041a80a4a76b3fda00000000000000000000000000000000000000000000000000000000000004258202789fe867953b945cb991e5e949e377d218e19058e0d6fbfdb2a8840b8f349c080aa06b67b719eed9dd93e8d76ca8e89e3f4b09ccd2adedbf6bf4a46a70bb61c8551b
```
I've also added a [simple test](https://github.com/hashgraph/hedera-json-rpc-relay/pull/657) to the _hardhat-example_ project demoing the issue.

**Comment by stoqnkpL** [comment]
Hey @mshakeg
is it possible for you to send us example code that reproduces the issue (even if it's not 100% reproducible)? 
Engineers from our side are trying to reproduce and debug the issue but we may need to add more logs and traces in order to understand exactly what is happening. 
From what I can see so far, it looks like the consensus node (main network node) is not able to resolve the account that signed the raw Ethereum transaction sent to the JSON-RPC relay. The normal flow is:
- A CryptoTransfer transaction to non-existing 0.0.KEY account in Hedera auto-creates an account that has an alias address (the key)
- A raw Ethereum transaction is created and signed with the key. This is usually done by MetaMask, ethers.js, or other existing tools
- The raw Ethereum transaction is sent to a JSON-RPC relay server, that wraps the transaction into an EthereumTransaction, signs it with the JSON-RPC relay operator account (in this case 0.0.2), and sends the wrapped transaction to a consensus node from the Hedera network
- The consensus node unwraps the raw Ethereum transaction and tries to resolve the account that signed it. At this point, we look for an account that has the same alias as the ECDSA key that signed the raw Ethereum transaction
I think at this point the resolving of the account fails and INVALID_ACCOUNT_ID is returned. It's also possible that there is a bug in the consensus node and a wrong response is returned.

Update: I see you have provided example code 🙏 We will continue investigating

**Comment by mshakeg** [comment]
@stoqnkpL thanks for the extensive answer, I managed to decode the `eth_sendRawTransaction` data using [this tool](https://flightwallet.github.io/decode-eth-tx/) and got the following:
```
{
  "nonce": 37,
  "gasPrice": 720000000000,
  "gasLimit": 2000000,
  "to": "0x000000000000000000000000000000000000041a",
  "value": 0,
  "data": "a76b3fda0000000000000000000000000000000000000000000000000000000000000425",
  "from": "0x67d8d32e9bf1a9968a5ff53b87d777aa8ebbee69",
  "r": "e867953b945cb991e5e949e377d218e19058e0d6fbfdb2a8840b8f349c080a",
  "v": "0278",
  "s": "6b67b719eed9dd93e8d76ca8e89e3f4b09ccd2adedbf6bf4a46a70bb61c8551b"
}
```
Presumably `from` is what you were referring to as `sender` in which case there isn't an issue there.

Hope my code example helps.

**Comment by stoqnkpL** [comment]
I can see there is a `to` account. Is this a contract call transaction? Maybe what cannot be resolved is account 0.0.1050 (0x41a)

**Comment by mshakeg** [comment]
@stoqnkpL correct, it's a contract call in this case, though the issue also shows up on contract deploys as my code example demonstrates.

**Comment by mshakeg** [comment]
@stoqnkpL just wanted to confirm if y'all have been able to replicate the issue on your side and if progress has been made.

**Comment by Ivo-Yankov** [comment]
Hi @mshakeg, yes, we have replicated the issue and are currently debugging it.

**Comment by mshakeg** [comment]
Hi @Ivo-Yankov , great to hear! It's beyond frustrating having to restart the local node every time this issue shows up and on some of my tests it's impossible to execute them to completion(due to the numerous contracts deployed in those tests).

**Comment by mshakeg** [comment]
Hi @Ivo-Yankov , I see this issue has been included in the 0.12.0 release milestones scheduled for 11 Nov, which is great! I just wanted to confirm if the root cause affects all `eth_sendRawTransaction`, `eth_sendTransaction` and `eth_call`, as it's not just an issue with contract deploys but also contract txs and calls.

**Comment by stoqnkpL** [comment]
@mshakeg this issue is added to the milestone because we're currently working on it, but it is not yet resolved and may be delayed. I will update you as soon as we have more information. I understand it's reproducible both with deploys and calls. 
I also understand it's a very frustrating issue and I hope to be able to resolve this as soon as possible and include a fix for 11 Nov.

**Comment by mshakeg** [comment]
@stoqnkpL I see, appreciate your understanding. Deving is quite miserable atm :(

**Comment by tinker-michaelj** [comment]
@mshakeg should be fixed by https://github.com/hashgraph/hedera-services/issues/4180

**Comment by mshakeg** [comment]
@tinker-michaelj how would that actually fix the issue? if that's the issue wouldn't that affect every `eth_sendRawTransaction` from the very first not on a seemingly random `eth_sendRawTransaction` after a few contract deployments?

**Comment by stoqnkpL** [comment]
> @tinker-michaelj how would that actually fix the issue? if that is the root issue wouldn't that affect every `eth_sendRawTransaction` from the very first not on a seemingly random `eth_sendRawTransaction` after a few contract deployments?

@mshakeg, the issue is reproduced when the `r` or the `s` field of the signature of the Ethereum transaction starts with one or more zeroes since the RLP library we use to decode the Ethereum transactions trims the `r` and `s` fields' leading zeroes. That's why sending the same transaction in a for loop, like in the example you provided, always fails on the third transaction - because the nonce field of the transaction changes every time, starting with 0, 1, 2, which changes the signed transaction bytes, and my guess is when signing the transaction bytes that contain a specific nonce, either `r` or `s` have 1 or more leading zeroes.

**Comment by mshakeg** [comment]
@stoqnkpL ah I see, that makes sense. Though in my experience(not the example I gave) it doesn't happen specifically on the 3rd, I suppose I'll be able to confirm with the next local node release if this fixes it there as well.

**Comment by mshakeg** [comment]
Hi @stoqnkpL , I just wanted to ask if you have an idea when the next local node release is? I'd like to test if the change to hedera-services fixes my issue specifically.

**Comment by stoqnkpL** [comment]
Hi @mshakeg, I think today or early next week an image of the consensus node will be created and uploaded to the registry, then we can update and release a new version of the `local-node` that will include this fix. 
I'll let you know when we release it.

**Comment by mshakeg** [comment]
@stoqnkpL sounds good, hopefully the next `local-node` release also includes `relay@0.11.0` as that also has another bug fix namely #644

**Comment by stoqnkpL** [comment]
Hey @mshakeg! 
we haven't released a new version of `local-node` yet, but `local-node` [supports different network configurations](https://github.com/hashgraph/hedera-local-node#network-specific-configuration), and if you update your `local` config with 
```
[...]
"nodeImageTag": "0.32.0",
"havegedImageTag": "0.32.0", 
"relayImageTag": "main",
[...]
```

and run the `local-node` with the `local` network flag, I believe this issue will be no longer reproducible 🥳 

Please note that these versions for the network node and relay are not yet stable and fully tested though, and some other issues may arise.

**Comment by mshakeg** [comment]
Hey @stoqnkpL great to hear, I have the local-node as a dev dependency in my project, if the next release is anytime time soon I'll wait, if not will clone the local-node repo and start it up as you suggested.

**Comment by mshakeg** [comment]
@stoqnkpL `local-node@2.2.1` was released yesterday however the network node and relay images weren't updated, is there a why?

**Comment by mshakeg** [comment]
Hi @dimitrovmaksim , I suppose you'd probably know why yesterday's local node release doesn't point to the latest network node and relay images. The latest network node has a fix to this issue and the latest relay(0.11.0) has a few bug fixes.

**Comment by dimitrovmaksim** [comment]
Hm, it seems as an oversight on our part, we will release a patch version, meanwhile you can try to configure it yourself, creating a `configs` folder in the root folder of the project you're running the local node from, then create a config (for example named `local2.json`) based on this one https://github.com/hashgraph/hedera-local-node/blob/main/configs/local.json and replace the relay and network node image versions, then run the start command with the --network <network_name> option (without the .json extension) `hedera start --network local2`

**Comment by mshakeg** [comment]
@dimitrovmaksim I see, ok, thanks, will do if the patch isn't release sometime today.

**Comment by mshakeg** [comment]
@Nana-EC I haven't yet tried, was hoping @dimitrovmaksim would have released the patch to local-node by now, will instead try config the local node to the latest images manually and let you know later today.

**Comment by mshakeg** [comment]
Hi @Nana-EC , I finally got around to testing this issue with the latest local-node release, this issue might have been resolved but seems to have exposed at least 2 additional issues, the first I've [created an issue on the local-node](https://github.com/hashgraph/hedera-local-node/issues/239) and the 2nd I suspect has to do with rate limiting on the evm as I'm now experiencing eth calls failing intermittently(haven't yet created an issue for the this).

**Comment by georgi-l95** [comment]
Hey @mshakeg , I'm unable to reproduce this bug with `eth_call` being rate limited. Can you check again with the new release and open issue with example, if issue still persist ?

**Comment by mshakeg** [comment]
Hey @georgi-l95 sure, will do by EOD.

**Comment by mshakeg** [comment]
@georgi-l95 the evm rate limiting still seems to be an issue with the latest local node release, will try to create an example first thing tomorrow.

**Comment by mshakeg** [comment]
@georgi-l95 this issue has been fixed and I haven't yet been able to create an example that replicates the evm rate limiting, will create a new issue if and when I am.
