### ISSUE TITLE
List all graph node env variables for hedera

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#700]
### Problem

Hedera isn't supported by The Graph's hosted service, so developers looking to deploy their subgraphs will have to setup their own graph node. The `subgraph-example` doesn't list the graph node's [env variables](https://github.com/graphprotocol/graph-node/blob/master/docs/environment-variables.md) optimised for hedera. It would be helpful to anyone looking to set up a graph node to use that list of env variables instead of using their own guesses or the default values.

For example `ETHEREUM_POLLING_INTERVAL` defaults to 500ms, however looking at [hashscan's blocks](https://hashscan.io/testnet/blocks) the block time seems to be about 2000ms and looking at [hedera metrics](https://hedera.com/#metrics) the time to finality is ~5.45s so perhaps a more suitable `ETHEREUM_POLLING_INTERVAL` is between 6_000 - 10_000 ms.

Another example would be the `GRAPH_ETHEREUM_BLOCK_INGESTOR_MAX_CONCURRENT_JSON_RPC_CALLS_FOR_TXN_RECEIPTS` variable which defaults to 1_000, however, should probably be based on the relay service limits which in the case of Arkhia's Enterprise tier should be 200.

### Solution

- List all the graph node's [environment variables](https://github.com/graphprotocol/graph-node/blob/master/docs/environment-variables.md) optimised for Hedera in the `subgraph-example`

**Comment by dimitrovmaksim** [comment]
This may take some time to figure out, probably after other issues are resolved and the whole thin is stable and can be tested extendedly.

**Comment by AlfredoG87** [comment]
even when in the docs says that this value defaults to 1000, i've seen is variable, and Hedera-Json-RPC-Relay does have a `1000` limit that in case it receives a higher block range it returns an error.

GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE=1000

**Comment by mshakeg** [comment]
@AlfredoG87 I recall going through the code a while back and it scales up/down based on failed calls, so `GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE` is just the `MAX` number of blocks it'll try to get concurrently, not sure what the limit is on hashio, but you'd want `GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE` to correspond with that limit or probably less since it's not a private dedicated relay.

**Comment by mshakeg** [comment]
@AlfredoG87 I recall going through the code a while back and it scales up/down based on failed calls, so `GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE` is just the `MAX` number of blocks it'll try to get concurrently, not sure what the limit is on hashio, but you'd want `GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE` to correspond with that limit or probably less since it's not a private dedicated relay.

**Comment by AlfredoG87** [comment]
Indeed the graph-node does scale up and down, but for the times it goes up, it fails.
yeah, the max on the relay is 1000, so this variable (`GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE` )should be 1000 or less.

**Comment by Nana-EC** [comment]
@AlfredoG87 let's update https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/tools/subgraph-example#prerequisites section with any custom graph env variables for optimized ingestion.
