### ISSUE TITLE
Add extended ERC20/ERC721 and Gravatar subgraph examples

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-json-rpc-relay#706]
### Problem

We want to extend the [subgraph examples folder](https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/tools/subgraph-example) to contain ERC20/ERC721 and Gravatar subgraph examples and have them available as a reference for subgraph developers on Hedera.

### Solution

The example should contain:
    - contracts
    - deploy and interaction scripts
    - subgraph
It can be configures to run against local-node but can be also easily modified to run against previewnet, testnet, mainnet.

**Comment by georgi-l95** [comment]
Fixed in https://github.com/hashgraph/hedera-json-rpc-relay/pull/737
