### ISSUE TITLE
Add extended HTS precompile subgraph examples

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-json-rpc-relay#707]
### Problem

We want to extend the [subgraph examples folder](https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/tools/subgraph-example) to contain a source for fungible HTS token treated like an ERC20 and a source for fungible HTS token treated like an ERC721.

### Solution

The example should contain:
- contracts
- deploy and interaction scripts
- subgraph
It can be configures to run against local-node but can be also easily modified to run against previewnet, testnet, mainnet.

**Comment by Nana-EC** [comment]
@Kalina-Todorova i think this was addressed right?
We should link the PR and close if so

**Comment by georgi-l95** [comment]
Yes this was addressed in https://github.com/hashgraph/hedera-json-rpc-relay/pull/737.
