### ISSUE TITLE
Events not returned on getPastEvents call

### ISSUE THREAD

**Issue by tonimateos** [hashgraph/hedera-json-rpc-relay#711]
### Description

There are events that are returned upon an `allEvents` query, via `contract.getPastEvents("allEvents")`, but not when querying for a particular event name, via `contract.getPastEvents(eventName)`. This behaviour is inconsistent, some events are correctly returned when specifying their eventName, some are not.

The web3js spec can be found [here](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#getpastevents) 

### Steps to reproduce

There is a Solidity contract deployed in the Hedera Testnet, on `0x0000000000000000000000000000000002ea7fc1`. The JSON ABI interface can be found [here](https://freeverse.mypinata.cloud/ipfs/QmRBDoUJL67GvYsyrwWyoTS1M1igFwNNij9ZpxUUUYVSSV).

There is an event that can be [correctly parsed](https://freeverse.mypinata.cloud/ipfs/QmQeN4qhzPpG6jVqJoXo2e86eHYPbFpKeUkJcTfrA5hJwz), and one that [cannot be parsed](https://freeverse.mypinata.cloud/ipfs/QmXgNFVQWsxnTreJNkNca66Ufgn8bQLkfLyCySk3k4Rtm6). 

To show the **correct** parsing of the first event, open a truffle console, making it point to a Hedera json-rpc relay, such as `https://testnet.hashio.io/api`.

1. `truffle console --network hedera`
2. `contract = await IUpdates.at('0x0000000000000000000000000000000002ea7fc1') `
3. `events = await contract.getPastEvents("allEvents", { fromBlock: 27314216, toBlock: 27314219})`
4. `events[0].event` => returns `OwnershipTxFormatVersion`
5. `events = await contract.getPastEvents("OwnershipTxFormatVersion", { fromBlock: 27432921, toBlock: 27432923 })` => returns the same as in point 3.

To show the **incorrect** parsing of the second event:

1. `truffle console --network hedera`
2. `contract = await IUpdates.at('0x0000000000000000000000000000000002ea7fc1') `
3. `events = await contract.getPastEvents("allEvents", { fromBlock: 27432921, toBlock: 27432923 })`
4. `events[0].event` => returns `NewTXsRoot`
5. `events = await contract.getPastEvents("NewTXsRoot", { fromBlock: 27432921, toBlock: 27432923 })` => returns nothing, empty array `[]`

The same issue can be reproduced using go-ethereum, so it is not truffle-related.

### Additional context

![Screenshot](https://freeverse.mypinata.cloud/ipfs/QmYkuKiF3AFqCz93UL1KShAi8PFfnHaEUmvjDxxsmvR2p6)

### Hedera network

testnet

### Version

0.11.0

### Operating system

Linux

**Comment by Nana-EC** [comment]
Thanks @tonimateos we'll take a look.

**Comment by dimitrovmaksim** [comment]
The issue here seems to be, because the second event has 2 indexed params. In this case web3js sends topic1 and topic2 as null `contracts/0x0000000000000000000000000000000002ea7fc1/results/logs?timestamp=gte:1669066650.853466552&timestamp=lte:1669066655.999999003&topic0=0x6f3984a8056b744a2405c513c3027efbcc8f00fb16be25a2e3fb772238b3455d&topic1=null&topic2=null&limit=100&order=asc 400 status`, but for the mirror node `null` is an invalid value for the topic param, so the request fails and the relay returns an empty array.
