### ISSUE TITLE
Error setting the envoy proxy and hedera node

### ISSUE THREAD

**Issue by raludi** [hashgraph/hedera-json-rpc-relay#712]
### Description

Our issue is the following:

1- We create a transaction in frontend with the client:     
 ```js 
  // THIS .ENV VARIABLE IS OUR PROXY IP THAT REDIRECTS TO HEDERA http://35.186.191.247:50211
  client = Client.forNetwork({
      [`https://${PUBLIC_HEDERA_PROXY_IP}:444`]: 
        AccountId.fromString('0.0.4')
    });
  client.setOperator(AccountId.fromString(accountId), operatorKey);
```
  
  and we freeze the transaction setting the node
  
  ```js 
const transferTransaction = new TransferTransaction()
    .setNodeAccountIds([AccountId.fromString('0.0.4')])
    .freezeWith(client);

    return transferTransaction.signWithOperator(client); 
```

We send a request to our backend attaching the transaction encoded
```js
  transaction: encode(freezeTrx.toBytes()),
```

and we execute the transaction in the backend after decoding it with a new client
```js
  const client = Client.forNetwork({
    [`http://35.186.191.247:50211`]: AccountId.fromString('0.0.4')
  });
   transaction.execute(client);
```

This does not work there is an infinite loop getting the nodes inside hedera code. (Image attached)

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/17050784/203658716-36ae0d4c-d837-4410-812b-0a26574eee34.png">

So it is not possible to configure a custom envoy proxy in frontend  with a custom node account in backend different from the default node (myHBARWallet)

### Steps to reproduce

1. Set a custom envoy proxy that redirects to Hedera node 4
2. Create a new client using this new envoy proxy in  Client.forNetwork({[`https://${PUBLIC_HEDERA_PROXY_IP}:444`]: AccountId.fromString('0.0.4')});
3. Create a new transaction setting the node 4 as valid.
4. Freeze this transaction with the client created
5. Make a request to backend, sending the transaction encoded.
6. Decode transaction
7. Create a new client using the IP from Hedere Mainnet Nodes 
Client.forNetwork({
    [`http://35.186.191.247:50211`]: AccountId.fromString('0.0.4')
  });
8. Execute the transaction with this client.

### Hedera network

mainnet

### Version

v2.18.6

### Operating system

Windows

**Comment by Nana-EC** [comment]
Hi @raludi I think you have the wrong repo.
Your issues seems related to the Hedera JS SDK - https://github.com/hashgraph/hedera-sdk-js
You'll want to open this issue their for triage.

@ochikov heads up.

**Comment by ochikov** [comment]
We are going to investigate the issue. Thank you.

**Comment by AdriMsM91** [comment]
@ochikov  Looks like setting a default Network in our BackEnd and not setting any Node in TrxFree its working.

```js
const client = Client.forNetwork(network);
```

So right now our last problem are the timers.... as you can see in this image, for each action (**Mint, TransferTransaction...etc**) it's **getting 5 Receipts** and It's increasing the timings a lot!

https://user-images.githubusercontent.com/59306428/203734198-467d0cb1-86fd-433f-b827-66594af25dee.png

Thanks you.

**Comment by ochikov** [comment]
@AdriMsM91 As we synced offline through Discord and with deep research, this is expected behavior since we are waiting for the receipt and the SDK by architecture is getting the transaction status until the transaction reached consensus on the network.
