### ISSUE TITLE
Failed to send/recv `storage` err=GetStorage() when testing with Foundry

### ISSUE THREAD

**Issue by a-ridley** [hashgraph/hedera-json-rpc-relay#732]
### Description

I have successfully set up Foundry to work with Hedera by configuring it to work with npm modules. We can run unit test, and complete fuzz testing. Github repo [here](https://github.com/a-ridley/hedera-smart-contract-testing-with-foundry).

The issue lies when attempting to use Foundry's fork testing to test against a smart contract that is deployed on testnet. In my test set up, I provided my smart contract's evm address (which I grabbed from hashscan).

Below is a snippet of my test set up.
```
function setUp() public {
        counter = Counter(0x0000000000000000000000000000000002Eba2A0);
        //counter.setNumber(0);
    }
```

The expected output is for my tests to run successfully. However, the result of running my tests gives the following error:

```
2022-12-01T18:28:36.945764Z ERROR sharedbackend: Failed to send/recv `storage` err=GetStorage(0x0000000000000000000000000000000002eba2a0, 0, 
(code: -32603, message: [Request ID: 6153887f-a84f-42e9-93c7-8fcb32047a21] Error invoking RPC: , data: None)) address=0x0000000000000000000000000000000002eba2a0 index=0

Running 1 test for test/foundry/Counter.t.sol:CounterTest
[FAIL. Reason: EvmError: FatalExternalError] testIncrement() (gas: 9223372036854754743)
Test result: FAILED. 0 passed; 1 failed; finished in 38.01s

Failing tests:
Encountered 1 failing test in test/foundry/Counter.t.sol:CounterTest
[FAIL. Reason: EvmError: FatalExternalError] testIncrement() (gas: 9223372036854754743)
```

### Steps to reproduce

1. Unzip the project below and open it in vscode
[simulate-swap-hedera.zip](https://github.com/hashgraph/hedera-json-rpc-relay/files/10137040/simulate-swap-hedera.zip)
2. edit the .env file
3. Open a terminal in the project's dir
4. run `HEDERA_RPC_URL=https://testnet.hashio.io/api `
5. run `forge test --fork-url $HEDERA_RPC_URL -vv --fork-block-number <block number>`

### Additional context

**note: block number needs to be at least 15 minutes in the past or you'll get the error below.**
`(code: -32007, message: [Request ID: 3804b205-6ef8-471d-92a2-e640d9131558] Historical balance data is available only after 15 minutes., data: None)) address=0x0000000000000000000000000000000002eba2a0`

### Hedera network

testnet

### Version

v2.18.5

### Operating system

macOS

**Comment by Nana-EC** [comment]
Seems like an error in the `eth_getStaorageAt()`
It makes a call to `https://testnet.mirrornode.hedera.com/api/v1/contracts/0x0000000000000000000000000000000002eba2a0/results/1669763444.249631003`
But then fails with 
```
Failed to retrieve contract result details for contract address 0x0000000000000000000000000000000002eba2a0 at timestamp=1669763444.249631003
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'value_written')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'value_written')
              at .../hedera-json-rpc-relay/packages/relay/dist/lib/eth.js:418:46
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    }
```
Since the `state_changes` is an empty array it passes the check for non null but when extracting `stateChange` it returns undefined which would result in the error above - https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/eth.ts#L501
