### ISSUE TITLE
Return appropriate http response codes

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#751]
### Description

From what I can tell the response code for all requests is set to 200 even for calls that hit rate limits, according to [this comment](https://forum.thegraph.com/t/are-contract-calls-always-deterministic/1216/3) the graph node expects a NOT OK(specifically 429) response code to retry a call that hit a rate limit.

I'm not sure if there's a spec that defines all response codes, but last I checked the eth json rpc spec doesn't have this detail.

### Steps to reproduce

1. Observe that a 200 ok response is returned for json rpc calls that "reverted" due to the rate limit.

### Hedera network

other

### Version

relay@v0.12.0

### Operating system

None

**Comment by dimitrovmaksim** [comment]
IMO, in general the graph should not be rate limited, even if the appropriate response code is returned, there's a retry limit anyways, so there's the possibility of blocks/data being skipped.

**Comment by mshakeg** [comment]
@dimitrovmaksim do you know what happens once the retry limit is reached?

Also it's got more to do with an event handler making an eth_call request and the hedera relay returning a call "revert" response instead of a rate limit response.

**Comment by dimitrovmaksim** [comment]
For consuming blocks at least it think it skips the block after 10 or 15 retries

**Comment by mshakeg** [comment]
@dimitrovmaksim hmm, does it ever try to recover and reconstruct subgraphs on the skipped blocks. It doesn't make much sense that it would skip blocks and consume later blocks that may only make sense given txs in previous skipped blocks.

**Comment by dimitrovmaksim** [comment]
Tbf it's hard to track all that is happening with the logs spam. Will have to test it again somehow. I may be wrong for the skipping, I may be confusing with fetching the transaction receipt
