### ISSUE TITLE
(subgraph-example) Yarn doesn't like @hedera-subgraph-greeter-example name

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-json-rpc-relay#756]
### Description

When installing with `yarn` it complains with `yarn install v1.22.19
error package.json: Name contains illegal characters`

changing `@hedera-subgraph-greeter-example` to `hedera-subgraph-greeter-example` enables yarn to install

### Steps to reproduce

See above

### Hedera network

testnet

### Version

https://github.com/hashgraph/hedera-json-rpc-relay/commit/75dc43f9213044321df98d3b9478ea10dcaa026d

### Operating system

macOS

**Comment by Kalina-Todorova** [comment]
Hi @gregscullard this has been resolved with this PR: https://github.com/hashgraph/hedera-json-rpc-relay/pull/737 Let us know if you face any further issues.
