### ISSUE TITLE
function call with long input data length fails

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#765]
### Description

I would like to make a large number of calls(via multicall) in a single call, however there appears to be limitations to the length of data for a call as demonstrated [here](https://github.com/mshakeg/hedera-json-rpc-relay/pull/7).

The first discrepancy is that the hedera local-node appears to work with a much higher input length compared to the hashio testnet relay. However even the local-node does not allow inputs as high as the hardhat local node.

### Steps to reproduce

Checkout to the branch in the aforementioned mentioned [PR](https://github.com/mshakeg/hedera-json-rpc-relay/pull/7)

(I) Demo the issue on the hedera local node
1. cd into the `hardhat-example` project's root then start the local node: `npm run hedera-start`
2. Run the `multicaller.test.ts` script against the hedera local-node: `npm run test:multicaller:local`
3. Observe that the local relay returns valid responses for calls where `iterations <= 1637` and fails for calls where `iterations >= 1638`

(II) Demo the issue on the hashio testnet relay
1. Run the `multicaller.test.ts` script against the hashio testnet relay: `npm run test:multicaller:testnet`
2. Observe that the testnet relay returns valid responses for calls where `iterations <= 42` and fails for calls where `iterations >= 43`

(III) Demo the expected multicall capacity on the hardhat local node
1. start the hardhat local node: `npm run hardhat-start`
1. Run the `multicaller.test.ts` script against the hardhat local node: `npm run test:multicaller`
2. Observe that the hardhat relay returns valid responses for calls where `iterations <= 2_936` and fails for calls where `iterations >= 2_937`

### Hedera network

testnet, other

### Version

hashio-relay@0.13.0 & @hashgraph/hedera-local@2.3.2

### Operating system

None

**Comment by mshakeg** [comment]
Hi @Ivo-Yankov this issue seems like it could be related to #533 just inverted i.e. instead of there being an issue with the call result length the issue is with the input parameter length.

**Comment by Ivo-Yankov** [comment]
Hi @mshakeg , the issue is that you have reached a 1mb limit on the input size in the relay. These PRs add a way to increase it via the `INPUT_SIZE_LIMIT` env variable:
https://github.com/hashgraph/hedera-json-rpc-relay/pull/792
https://github.com/hashgraph/hedera-local-node/pull/250

**Comment by mshakeg** [comment]
Hi @Ivo-Yankov can the default be increased to about 10mb, AFAIK there's no size limit on typical json rpcs(infura) other than the gasLimit, and a 15m gasLimit can accommodate an input of at least 100mb as demonstrating in the example code.

**Comment by georgi-l95** [comment]
Hey @mshakeg , we'll discuss this proposal and let you know.

**Comment by mshakeg** [comment]
Hi @georgi-l95 just wanted to ask if y'all plan on increasing the default input beyond 1mb? 100mb would obviously be ideal as that corresponds with the maximum allowable given the 15m gasLimit, however 10mb is fine too.

**Comment by mshakeg** [comment]
Hi @georgi-l95 , I'm guessing y'all settled on a default of 1mb?

**Comment by Ivo-Yankov** [comment]
Hi @mshakeg, there is still an ongoing discussion regarding this issue. We merged the PR to allow users to change the config on the local node for testing purposes, but all public networks will continue to have a limit ot 1mb for now.
