### ISSUE TITLE
Issue with specific contract deploy on hashio testnet relay

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#771]
### Description

I have a contract X that deploys fine to my hedera local-node and also deploys fine using the `@hashgraph/sdk` however this specific contract X fails to deploy via the hashio testnet relay, I also don't see a revert reason returned so not sure exactly what the issue is. All of my other contracts deploy fine.

The last attempted deploy request id trace is below, if that isn't sufficient I can maybe share the contract and demo its failure to deploy.

[Request ID: 716003bf-b99a-4e87-924f-3b927f7fe9f4]

### Steps to reproduce

See above, for privacy reasons I'd prefer to not publicly share the contract.

### Hedera network

testnet

### Version

hashio-relay@0.13.0

### Operating system

None

**Comment by Kalina-Todorova** [comment]
Hi @mshakeg, is this issue still ongoing for you? If so I can get in touch with you so that we can get more info and debug.

**Comment by mshakeg** [comment]
Hi @Kalina-Todorova yes it is, apologies for the late reply, been mostly AFK, I've demonstrated the issue in [this PR](https://github.com/mshakeg/hedera-json-rpc-relay/pull/8).

* the contract can be deployed to the hedera local node(`npm run test:pc` script to demo this)
* the contract can NOT be deployed to the hedera testnet via the hashio relay(`npm run test:pc:testnet` script to demo this)

I've only attached a minimal `abi` and `bytecode` in the `ProblemContract.json` file, to obfuscate details unnecessary to demoing the issue.

**Comment by Kalina-Todorova** [comment]
Thanks @mshakeg we will review and reproduce it and will get back to you.

**Comment by mshakeg** [comment]
Hi @Kalina-Todorova & @natanasow , can this issue please be reopened as the example problem contract I mentioned [above](https://github.com/hashgraph/hedera-json-rpc-relay/issues/771#issuecomment-1366494167) still cannot be deployed. I'm getting back the following response even on multiple attempts(other contracts deploy fine):
```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```
