### ISSUE TITLE
static contract call and transaction revert with INVALID_SOLIDITY_ADDRESS

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#805]
### Description

Low-level solidity calls(i.e. `address.call`) should NOT revert if the contract address specified is invalid(i.e. non-existent). Hedera currently reverts with the error message: `INVALID_SOLIDITY_ADDRESS`.

This may not be an issue if only a single low-level call reverts in this way, however if making a multicall with BOTH valid and invalid contract addresses, developers would want the data for BOTH the valid&invalid calls returned, with each calls success/failure identified by a boolean `success` field or `0x` return data for example.

### Steps to reproduce

1. Checkout to the branch in [this PR](https://github.com/mshakeg/hedera-json-rpc-relay/pull/9)
2. Run the `low-level-call.test.ts` script against the **hardhat local node**: `npm run test:llc` and observe NO reverts for both the transaction and static call
3. Run the `low-level-call.test.ts` script against the **hedera local node**: `npm run test:llc:local` and observe BOTH the transaction and static call revert

To test on testnet replace `h_local` with `h_testnet` in the `test:llc:local` script

### Hedera network

testnet

### Version

v0.14.0

### Operating system

None

**Comment by mshakeg** [comment]
I tried to find a hack around using [OpenZeppelin's isContract util function](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/a28aafdc85a592776544f7978c6b1a462d28ede2/contracts/utils/Address.sol#L40), as a precheck before doing the low level _address.call_, however, that also reverts with `INVALID_SOLIDITY_ADDRESS`
```solidity
    function isContract(address account) public view returns (bool) {
        // This method relies on extcodesize/address.code.length, which returns 0
        // for contracts in construction, since the code is only stored at the end
        // of the constructor execution.

        return account.code.length > 0;
    })
```

**Comment by Kalina-Todorova** [comment]
Hi @mshakeg this will be covered as part of: https://github.com/hashgraph/hedera-services/issues/4672, will update here as well once we have progress.

**Comment by stefan-stefanooov** [comment]
Handled in here:
https://github.com/hashgraph/hedera-services/pull/9628
