### ISSUE TITLE
Testing Precompiles Using Foundry results in Unknown error invoking RPC

### ISSUE THREAD

**Issue by a-ridley** [hashgraph/hedera-json-rpc-relay#806]
### Description

I am using the Hedera Precompiles to create a simple fungible token. I set up a smart contract that imports the precompiles and create a function called createFungible(). I then set up a test and used foundry to test the create fungible token function.

When running the test, it fails with the following error:

```
% forge test --fork-url https://testnet.hashio.io/api -vvvv
[⠆] Compiling...
No files changed, compilation skipped
2023-01-06T00:23:10.655008Z ERROR sharedbackend: Failed to send/recv `storage` err=GetStorage(0x7109709ecfa91a80626ff3989d68f67f5b1dd12d, 46308022326495007027972728677917914892729792999299745830475596687180801507328, 
(code: -32603, message: [Request ID: 8fd7fec6-5fc5-40eb-9288-343083ef40c7] Unknown error invoking RPC, data: None)) address=0x7109709ecfa91a80626ff3989d68f67f5b1dd12d index=46308022326495007027972728677917914892729792999299745830475596687180801507328

Running 1 test for test/foundry/MyContract.t.sol:MyContractTest
[FAIL. Reason: Assertion failed.] test_CreateFungible() (gas: 8937393460516744731)
Logs:
  Error: a == b not satisfied [int]
    Expected: 22
      Actual: 21

Traces:
  [8937393460516744731] MyContractTest::test_CreateFungible() 
    ├─ [8937393460516724677] 0x0000000000000000000000000000000002eF1D37::339d1f60(000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000006acfc00000000000000000000000000000000000000000000000000000000000000006546573744654000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035446540000000000000000000000000000000000000000000000000000000000) 
    │   ├─ [0] 0x0000000000000000000000000000000000000167::c23baeb6(000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000002ef1d3700000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002ef1d3700000000000000000000000000000000000000000000000000000000006acfc0000000000000000000000000000000000000000000000000000000000000000654657374465400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003544654000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000) 
    │   │   └─ ← ()
    │   └─ ← 0x00000000000000000000000000000000000000000000000000000000000000150000000000000000000000000000000000000000000000000000000000000000
    ├─ emit log(: Error: a == b not satisfied [int])
    ├─ emit log_named_int(key:   Expected, val: 22)
    ├─ emit log_named_int(key:     Actual, val: 21)
    ├─ [0] VM::store(VM: [0x7109709ECfa91a80626fF3989D68f67F5b1DD12D], 0x6661696c65640000000000000000000000000000000000000000000000000000, 0x0000000000000000000000000000000000000000000000000000000000000001) 
    │   └─ ← "Failed to get storage for 0x7109709ecfa91a80626ff3989d68f67f5b1dd12d at 46308022326495007027972728677917914892729792999299745830475596687180801507328: 
(code: -32603, message: [Request ID: 8fd7fec6-5fc5-40eb-9288-343083ef40c7] Unknown error invoking RPC, data: None)"
    └─ ← ()

Test result: FAILED. 0 passed; 1 failed; finished in 27.41s
```

I expect to be able to test my contracts functions which utilize the hedera precompiles.

### Steps to reproduce

1.Unzip the project below and open it in vscode
[hedera_precompile_foundry.zip](https://github.com/hashgraph/hedera-json-rpc-relay/files/10356478/hedera_precompile_foundry.zip)
2. edit the .env file
3. Open a terminal in the project's dir
4. run forge test --fork-url https://testnet.hashio.io/api -vvvv

### Additional context

![image](https://user-images.githubusercontent.com/18725916/210905866-cabf0ccc-b693-4fce-bae3-468d1702ea68.png)

### Hedera network

testnet

### Version

2.18.5

### Operating system

macOS

**Comment by mshakeg** [comment]
The Foundry EVM doesn't support the precompiles, you'll have to run it against the hedera local node, which is much slower as it currently stands.

**Comment by mshakeg** [comment]
The Foundry EVM doesn't support the precompiles, won't you have to run it against the hedera local node, which is much slower as it currently stands. The hardhat local node would have the same issue. It would be nice if we could run it against the Foundry or Hardhat node as they're much faster and they implement debugging methods not currently available on the hedera relay.

**Comment by georgi-l95** [comment]
Yes, you can run tests against [hedera-local-node](https://github.com/hashgraph/hedera-local-node) which supports precompiles.

**Comment by Kalina-Todorova** [comment]
Given that there is no action item here other than the option to use local-node, I'm closing this issue.

**Comment by vea-vecturne** [comment]
I ran this test against the local node (current main branch) and had the same issue.  I looked at the output in the local-node docker compose logs and found it was trying to get data on a contract at address 0x7109709ecfa91a80626ff3989d68f67f5b1dd12d.

![Screenshot from 2023-01-12 10-42-52](https://user-images.githubusercontent.com/95554982/212116124-8c8fab17-6a88-414d-8a34-225e9dcc1944.png)

That address appears to be related to foundry 'cheat codes'  contract that performs different functions for testing.

https://github.com/foundry-rs/foundry/blob/master/forge/README.md

**Comment by stoqnkpL** [comment]
Hey @vea-vecturne

Unfortunately, it looks like what you're trying to achieve is currently impossible. 
There are two setups you can use to execute tests:

1. Using the local node would run the tests in the Hedera EVM - the Hedera precompiled contracts will work, but the Foundry custom `cheat codes` contract won't be available
2. Using the Foundry EVM - the `cheat codes` contract will be available, but the Hedera system contracts will not be there

There is no Foundry support currently in Hedera.
