### ISSUE TITLE
Add `blockParam` to endpoints according to EIP-1898

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#822]
According to [EIP-1898](https://eips.ethereum.org/EIPS/eip-1898) we should make the following endpoints accept block parameter ( tag, block number or object with block hash or block number ):

- [x] eth_getBalance
- [x] eth_getStorageAt
- [ ] eth_getTransactionCount
- [ ] eth_getCode
- [ ] eth_call
- [ ] eth_getProof

We currently only support blockParam on `eth_call`. Infura and Alchemy as well on support blockParam on the same endpoint.
Research and expand the rest of the endpoints, if needed.
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1856
- [ ] https://github.com/hashgraph/hedera-json-rpc-relay/issues/1857
```

**Comment by Nana-EC** [comment]
Converted list to tasks.

SUpported endpoints have the tag added.
However not all support historical cases as Mirror Node may not yet support it

**Comment by georgi-l95** [comment]
Resolved for all relevant endpoints.Thus closing this issue.
