### ISSUE TITLE
Executing a contract call using ethers.js and the json-rpc relay intermittently returns different errors for the same call

### ISSUE THREAD

**Issue by vea-vecturne** [hashgraph/hedera-json-rpc-relay#828]
### Description

In the process of testing a simple smart contract, I've received various errors when trying to make calls to the relay.  Some times the call will revert as expected, some times it returns a 500 and other times a 502.

The contract is very simple, it sets a value in the smart contract and then reverts.  

```
// SPDX-License-Identifier: BUSL-1.1
pragma solidity =0.8.12;

contract Simple {
    uint256 num;
    error ErrorOut(uint value);

    function checkCall(uint256 n) public returns (uint256){
        num = n;
        if(true) {
            revert ErrorOut(0x13);
        }
        return num+1;
    }
}
typescript testing:
async function test() {
    // pk is the ECDSA private key for the testnet account created in the hedera portal
    // solAddr is the address of the deployed contract
    // ex: 0000000000000000000000000000000002f1b9e4

    let jsonRpc = new ethers.providers.JsonRpcProvider('https://testnet.hashio.io/api')
    let signer = new ethers.Wallet(pk.toBytesRaw(), jsonRpc)

    let options = { gasPrice: '6000000000000', gasLimit: '500000'}
    let colCon = new Contract(solAddr, Simple.abi, signer)
    let resp
    try {
        resp = await colCon.checkCall(100000000, options)
        console.log(resp)
    } catch (error) {
        console.log(error)
    }
    try {
        let w = await resp.wait()
        console.log(w)
    } catch (error) {
        console.log(error)
    }
}
```

### Steps to reproduce

1. deploy contract and get the address
2. create the necessary pieces to make the function call using ethers (see code above)
3. run the test function several times

expected:
a contract revert

actual:
failing for various reasons, with an occasional revert

note:
Currently i'm receiving a 502 response each time i try to run this test with the above setup on hashio for testnet.  The time is Jan 23, 11:28 AM EST.

### Additional context

502:
![image](https://user-images.githubusercontent.com/95554982/214090325-048cee83-235e-418f-80f8-85f153a247b2.png)
500:
![image](https://user-images.githubusercontent.com/95554982/214090402-ae1b3ecf-65f0-4078-89ad-9c4561794075.png)
Expected Revert:
![image](https://user-images.githubusercontent.com/95554982/214097407-2d12f6ab-9188-4f9d-933d-a1585200f898.png)

### Hedera network

testnet

### Version

Current Version of testnet hashio

### Operating system

Linux

**Comment by georgi-l95** [comment]
Hey @vea-vecturne  Can you try again, as we've introduced some bugfixes, if the issue still persist?

**Comment by Nana-EC** [comment]
@vea-vecturne pinging here to check. Thanks

**Comment by vea-vecturne** [comment]
Hey @georgi-l95 @Nana-EC 

Sorry for the late reply.  It seems to be a little better, I did get one other error though:

  ```
reason: 'bad response',
  code: 'SERVER_ERROR',
  status: 400,
  headers: {
    date: 'Tue, 07 Feb 2023 01:44:27 GMT',
    'content-type': 'application/json; charset=utf-8',
    'content-length': '172',
    connection: 'close',
    'access-control-allow-origin': '*',
    'access-control-allow-methods': 'GET,HEAD,PUT,POST,DELETE',
    via: '1.1 google',
    'cf-cache-status': 'DYNAMIC',
    server: 'cloudflare',
    'cf-ray': '79587076ab53daa3-MIA'
  },
  body: '{"jsonrpc":"2.0","id":53,"error":{"code":-32010,"name":"Request timeout","message":"[Request ID: 2b0e4fcc-1b4e-4cd3-b8c2-7802a028c9fc] Request timeout. Please try again."}}',
  requestBody: '{"method":"eth_getTransactionReceipt","params":["0xb3e8a733b1418f4e39cd9c49109d05c2720f278eb67e0bfb8e42ba04ec36a4ea"],"id":53,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://testnet.hashio.io/api'
```

I did the same thing above for the steps to reproduce.

**Comment by Kalina-Todorova** [comment]
Hi @vea-vecturne is my understanding that it works properly now correct?

**Comment by vea-vecturne** [comment]
> Hi @vea-vecturne is my understanding that it works properly now correct?

We haven't seen any issues with this lately.

**Comment by Kalina-Todorova** [comment]
Great to hear @vea-vecturne. I'm closing the ticket in this case. Feel free to reopen it or file another one if you face further issues.
