### ISSUE TITLE
Deploy Smart Contract using Foundry throws Failed to create wallet from private key: signature error 

### ISSUE THREAD

**Issue by a-ridley** [hashgraph/hedera-json-rpc-relay#834]
### What I did:
I am attempting to use Foundry to deploy a smart contract to the Hedera testnet. When i run the following command
`forge create --rpc-url <your_rpc_url> --private-key <your_private_key> contracts/MyContract.sol:MyContract`
I received the following error:

`[⠔] Compiling...
No files changed, compilation skipped
Error: 
Failed to create wallet from private key: signature error`

### What I expected to happen:
My Contract to be deployed successfully and a similar message to the one below:

```
[⠰] Compiling...
No files changed, compilation skipped
Deployer: 0x4DdC478A1F35Bbf266D2F5767AE399f4d6E83857
Deployed to: 0x47c81E6e3f2880a42149574f08DCaBffCa10e164
Transaction hash: 0xfec3c5a6d726a4f94a57011c7c5f6fe3f54dad70700652570cda626f58a81dca
```

### Steps to reproduce

1.Unzip the project below and open it in vscode
[hedera_foundry_fork_testVendingMachine.zip](https://github.com/hashgraph/hedera-json-rpc-relay/files/10494681/hedera_foundry_fork_testVendingMachine.zip)
2. edit the .env file
3. Open a terminal in the project's dir
4. run `forge create --rpc-url https://testnet.hashio.io/api --private-key <your_private_key> contracts/TodoList.sol:TodoList`

### Additional context

![Screenshot 2023-01-24 at 3 09 29 PM](https://user-images.githubusercontent.com/18725916/214441445-a7cdc549-c1d4-4145-889d-49654b1f3e32.png)

### Hedera network

testnet

### Version

2.18.5

### Operating system

macOS

**Comment by georgi-l95** [comment]
Hey @a-ridley , what kind of private key are you using ? I've tried with `ECDSA` key. Reproduced the steps and this is my result:

```
[⠢] Compiling...
No files changed, compilation skipped
Deployer: 0x8CA7bF156EB354f8Afb4846fC7603154Ae00Ce29
Deployed to: 0xCe8fCA94EAd2f464A2B2A9Cb2D8A45b03CD304Ea
Transaction hash: 0xae27c10111bc938322d1c15ddf46a8cb7a8e02d681048ab149a22da3131dbad7
```
Although I need to make a little change in the relay for it to work, which I'll open a PR soon for it.

**Comment by a-ridley** [comment]
@georgi-l95 Oh, right! I was not using an `ECDSA` key. I was using `ED25519`. 
Now that I've updated to use an ECDSA key, I see the error you mentioned above.

```
[⠰] Compiling...
No files changed, compilation skipped
Error: 
Deserialization Error: invalid type: string "0x0.8", expected f64 at line 1 column 138. Response: {"baseFeePerGas":["0x12eae09c800","0x12eae09c800","0x12eae09c800","0x12eae09c800","0x12eae09c800","0x12eae09c800"],"gasUsedRatio":["0x0.8","0x0.8","0x0.8","0x0.8","0x0.8"],"oldestBlock":"0x1c7b495","reward":[["0x0","0x0","0x0"],["0x0","0x0","0x0"],["0x0","0x0","0x0"],["0x0","0x0","0x0"],["0x0","0x0","0x0"]]}
```

Thanks for linking the issue that addresses the problem associated with the error above. 🙏

**Comment by georgi-l95** [comment]
@a-ridley Hey , we've fixed the issue, can you try again on `testnet` and `previewnet` as well.

**Comment by a-ridley** [comment]
@georgi-l95 sorry for the late responst! yup, everything looks great! Are we not able to search hashscan by transaction hash atm?
