### ISSUE TITLE
add block to web3_clientVersion

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#850]
### Problem

It would be helpful to developers to know at which block a json rpc relay was deployed.

This would be useful in at least one scenario. Say an issue was introduced with `version x` of the relay that was deployed at `block y`, since devs now know the exact block at which `version x` was deployed they can then deploy a grafted subgraph starting at `block y` as soon as the fix is deployed in `version x+1`.

### Solution

Suffix the block number to the `web3_clientVersion` e.g. `relay/0.16.0@{blockNumber}`.

Or another existing json rpc method if it's more appropriate there.

**Comment by mshakeg** [comment]
Since the relay has downstream dependencies that may also introduce bugs with later versions such as the hedera mirror node, those services should also state the block number at which a particular version was deployed.

**Comment by Nana-EC** [comment]
Hey @mshakeg interesting suggestion.
We'll look into it and what items it brings along with it.

**Comment by Nana-EC** [comment]
Hey @mshakeg ,
Thanks for this.
Similar to the other ticket the Ethereum JSON RPC API doesn't give provision for the block number at which an RPC was deployed.
Also given the service is stateless this isn't something that is held on to for any reason.

For more context can you share what use case that this would serve?

**Comment by mshakeg** [comment]
Hey @Nana-EC I think #1024 can be addressed with this issue.

I wouldn't consider the relay entirely stateless as it does cache and so it could cache invalid data from upstream dependencies such as the mirror node.

Perhaps expose a `/config` endpoint which returns the relay config and also the blocks at which the relay was deployed(assuming it's an in memory cache to get an idea of how old the relay's cache is or alternatively add a `last- updated` fields to the response headers) and the blocks at which any upstream dependencies such as the mirror node were deployed(so if for example, say the mirror node starts returning invalid data from a given block which results in subgraph's being corrupted from that block onwards, now when a fix is deployed to the mirror node developers can now use this block as a starting point to continue reindexing their subgraphs to correct them).

**Comment by Nana-EC** [comment]
Yeah, valid points about the cache.
I still don't believe we would extend any of the Ethereum JSON RPC API's to return data that isn't typical of RPCs and not defined in the spec standard or EIPs.

You can open another ticket with your suggestion of a `/config` endpoint for consideration.
I'll be closing this and #1024 as won't fix due to the nature of the breaking API

In the new API if you can mentioned other RPCs that you've observed do this and define the details of the results that would assist consideration.

Thanks

**Comment by Nana-EC** [comment]
Closing as implementing would break conformance with API response expectations
