### ISSUE TITLE
Research `eth_subscribe` to expose

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-json-rpc-relay#861]
### Problem

Currently the relay does not expose `eth_subscribe` and `eth_unsubscribe`, therefore these not support any subscription functionality. 

### Solution

It works by subscribing to particular events and for each subscription an id is returned. For each event that matches the subscription a notification with relevant data is sent together with the subscription id. 
For now we need to explore only subscribing to event logs. 

Example Request:
```
>{"jsonrpc":"2.0", "id": 1, "method": "eth_subscribe", "params": ["logs", {"address":"0x8320fe7702b96808f7bbc0d4a888ed1468216cfd", "topics": ["0xd78a0cb8bb633d06981248b816e7bd33c2a35a6089241d099fa519e361cab902"]}]}
```

Example Response for successful subscription:

```
{
    "id": 1, 
    "jsonrpc": "2.0", 
    "result": "0x9cef478923ff08bf67fde6c64013158d"
}
```

Example Response for new log:
```
// logs Subscription
{
    "jsonrpc":"2.0",
    "method":"eth_subscription",
    "params": {
        "subscription":"0x4a8a4c0517381924f9838102c5a4dcb7",
        "result": {
            "address":"0x8320fe7702b96808f7bbc0d4a888ed1468216cfd","blockHash":"0x61cdb2a09ab99abf791d474f20c2ea89bf8de2923a2d42bb49944c8c993cbf04",
            "blockNumber":"0x29e87","data":"0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000003",
            "logIndex":"0x0",
            "topics":["0xd78a0cb8bb633d06981248b816e7bd33c2a35a6089241d099fa519e361cab902"],"transactionHash":"0xe044554a0a55067caafd07f8020ab9f2af60bdfe337e395ecd84b4877a3d1ab4",
            "transactionIndex":"0x0"
        }
    }
}
```

**Comment by Ivo-Yankov** [comment]
I wasn't able to find a clear documentation for how a relay server is expected to behave when handling websocket communication, so I looked at some existing server (Infura, Alchemy) and client (ethers WebSocketProvider) implementations and reverse engineered the basic requirements for `eth_subscribe`. 

- First we will need to install a WebSocket library and create a `WebSocketServer` wrapper class. The `WebSocketProvider` from `ethersjs` uses [ws](https://www.npmjs.com/package/ws), which I think will be sufficient for our needs. Another possible alternative is [socket.io](https://www.npmjs.com/package/socket.io), althouth it is not as light-weight as ws.

- This mocked code is the minimum required to achieve a subscription:

```typescript
const express = require('express');
const path = require('path');
const { createServer } = require('http');
const { WebSocketServer } = require('ws');

const app = express();
app.use(express.static(path.join(__dirname, '/public')));

const server = createServer(app);
const wss = new WebSocketServer({ server });

wss.on('connection', function (ws) {
  ws.on('message', function (msg) {
    const msgString = msg.toString('base64');
    const request = JSON.parse(Buffer.from(msgString, 'base64').toString('ascii'));
    const {method, params} = request;

    if (method === 'eth_subscribe') {
      const event = params[0];

      if (event === 'log') {

	      const filter = params[1];
	      // Cache the `event`, `filter`, `SUBSCRIPTION_ID` and the current block number values

	      // This establishes the subscription
	      ws.send(JSON.stringify({
	        id: request.id,
	        result: SUBSCRIPTION_ID,
	        jsonrpc: '2.0'
	      }));
      }

      // Handle other types of events: newPendingTransactions, newHeads, syncing
    }


    // The WebSocketProvider emits an event to `eth_chainId` right after establishing a connection
    else if(method === 'eth_chainId') {
      ws.send(JSON.stringify({
        id: request.id,
        result: {
          result: CHAIN_ID,
        },
        jsonrpc: '2.0'
      }));
    }

    // Handle other methods
  });

  ws.on('error', console.error);

  ws.on('close', function () {
    // remove subscriptions from cache
  });

});
```

- Run a scheduled cron job that runs loops through all saved `filter` values and sends the results to the corresponding sockets with the respective `SUBSCRIPTION_ID` values. This would basically execute the logic from eth_getLogs with applied block, address and topic filters. The relay will need to remember the last checked blockNumber. 


Send the data to the subscribed client:

```typescript
ws.send(JSON.stringify({
  method: 'eth_subscription',
  params: {
    result: LOG_OBJECT,
    subscription: SUBSCRIPTION_ID
  }
}));
```

Note that this response is not in the json-rpc format.


### Other things to consider

WebSockets in general are resource intensive. We could implement a throttling mechanism. 
- [Limits in Alchemy](https://docs.alchemy.com/reference/subscription-api#websocket-limits)
- [Ethers suggests relays charge extra fees for web-sockets](https://docs.ethers.org/v5/api/providers/other/#WebSocketProvider)

We should perform some stress tests to determine how many connections are sustainable and decide on what limits should be implemented. Every live socket connection would also result in additional requests to the Mirror Node every n seconds.

WebSockets often require additional server configuration to work properly with https. We should make sure everything is setup properly before enabling this on the public relays.


### Useful links

- https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/subscription-methods/eth_subscribe
- https://docs.alchemy.com/reference/logs
