### ISSUE TITLE
fail to transfer HBAR to new evm address and latest gas price does not work

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#871]
### Description

I tried to do an HBAR transfer(`sendTransaction`) in Metamask to a new EOA i.e. an Ethereum(ECDSA) account that has not yet been instantiated on Hedera, but that transaction failed with [INVALID_CONTRACT_ID](https://hashscan.io/testnet/tx/0x3d1a22ee9b60b50e98a88c06f8b37c0c9fccf2c246dacd03de89cd8ab1a1d934).

I wrote a simple test script to demo the issue and noticed another issue with the `gasPrice`. Using the latest `gasPrice` from `eth_gasPrice` is insufficient but 100x of the `gasPrice` works.

### Steps to reproduce

1. Checkout to the branch in [this PR](https://github.com/mshakeg/hedera-json-rpc-relay/pull/13/files)
2. Run the `test:th:testnet` script: `npm run test:th:testnet`
3. Observe that only 1/4 test cases succeeds specifically:
* _CAN transfer to **existing account** at 100x gas price_

All other test cases fail:
* _CANNOT transfer(but should) to **existing account** at current gas price_
* _CANNOT transfer(but should) to **new account** at current gas price_
* _CANNOT transfer(but should) to **new account** at 100x gas price_

### Hedera network

testnet

### Version

relay/0.17.0-rc1

### Operating system

None

**Comment by mshakeg** [comment]
Hi @georgi-l95 thanks, I've been able to confirm that `sendTransaction` to new accounts works on `previewnet`, however the `gasPrice` issue also exists on `previewnet`.

**Comment by georgi-l95** [comment]
@mshakeg Okay thank you, we'll take a look at the gasPrice issue.

**Comment by natanasow** [comment]
@mshakeg In the example, you've provided, you're loading the provider via `ethers.getDefaultProvider()` which returns a `FallbackProvider`. The `FallbackProvider.getGasPrice()` method returns Ethereum's main net gas price. In order to make the example workable, you can initialize an ethers json-rpc provider instead.

```typescript
export async function getGasPrice(): Promise<BigNumber> {
  // const defaultProvider = ethers.getDefaultProvider();
  const defaultProvider = new ethers.providers.JsonRpcProvider(process.env.RELAY_ENDPOINT);
  return defaultProvider.getGasPrice();
}
```

**Comment by mshakeg** [comment]
@natanasow you're right, alternatively you can also get the provider for the active hardhat network without having to explicitly load the relay URL(other than in your hardhat config) using:
```
const activeNetworkProvider = ethers.provider;
```
