### ISSUE TITLE
Ability to send funds from Metamask wallet to Hedera account ID

### ISSUE THREAD

**Issue by sergmetelin** [hashgraph/hedera-json-rpc-relay#890]
### Problem

At the moment, Metamask users can only send funds to another alias, not to a Hedera native account ID. This creates confusion over where to send funds to if an explicit alias wasn't given.

![image](https://user-images.githubusercontent.com/2141500/217957745-46f8b401-a86d-415f-80c9-7c380873df1b.png)

### Solution

It would be awesome if we could find a way to send funds from a ECDSA Metamask account to Hedera ID using Metamask. 
Maybe working with Metamask's support for ENS could be the key? Maybe we could emulate an ENS endpoint to point to the aliases of the accounts on Hedera, for example. I'm not sure if ENS endpoints are hardcoded in Metamask. Or, potentially, talking to ENS directly to support this functionality? Supporting IDs in Metamask would be a significant win for the RPC API Nodes and Metamask integration.

**Comment by Ashe-Oro** [comment]
From my understanding, MM only supports ENS as a name resolver. And ENS only supports the *.eth extension. If that's true, then asheoro.eth could resolve to my Hedera ECDSA alias pub addr, but not my Hedera native account_id. 

Someone plz check me here.

**Comment by georgi-l95** [comment]
This is definitely issue for MM repo, we cannot change this from the relay. When you enter address, MM makes internal validations before sending request to the relay.
But that's definitely a reasonable and very good suggestion. We'll look deeper into this.

**Comment by Neurone** [comment]
Actually MM uses the [ethereum-ens-network-map](https://github.com/flyswatter/ethereum-ens-network-map) (that is actually a [simple file with a mapping chainid-> address](https://github.com/danfinlay/ethereum-ens-network-map/blob/master/index.js)) to check for ENS support and for the address to the main ENS contract. Thereafter, ENS domain names are checked on-chain querying that contract.

If we want ENS support, technically we can deploy that on Hedera and create a PR to ethereum-ens-network-map.

@Ashe-Oro ENS is not technically limited to .eth domains, that just a convention to easily identify names that should be resolved by ENS, and not with other systems like DNS.
