### ISSUE TITLE
Add cache to eth_getTransactionReceipt endpoint

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#900]
### Problem

Currently every time eth_getTransactionReceipt is called we call the mirror node for deatils.
However, for a transaction that exists we know the receipt won't change so we should cache it 

### Solution

Utilize the LRU cache to store the receipt of valid transactions to reduce load on Mirror Node

**Comment by AlfredoG87** [comment]
I saw that we are using this LRU Cache (on-memory) on several other places within the codebase, have we discussed the possibility of using a distributed cache like redis instead of on-memory?

 the argument being that every we currently have 2 instances of the relay on hashio and supoosedly the data con instance1 gets cached, there is a 50% chance the next call, where this cached object would be needed will happen in instance2 of the relay. hence having to call the mirror node and not getting full advantange of the cached values.
 This problem would exacerbate with more intances in case we need to scale-out in the future.

**Comment by georgi-l95** [comment]
I think one of our main goals are to keep the relay stateless.

**Comment by georgi-l95** [comment]
Actually @AlfredoG87 is right. It would be better to have one cache for all instances of the relay. Currently every instance is using it's own cache and inefficiency grows with the number of instances of the relay.

**Comment by Ivo-Yankov** [comment]
What is the scenario where a single transaction receipt would be requested multiple times? In the most common use-cases a transaction is submitted, then the receipt is requested only once. It could be cached, but I'm not sure how usefull that would be.

**Comment by AlfredoG87** [comment]
@georgi-l95 thanks for your feedback, I was thinking about the stateless thing you mentioned, and here I could add 2 things.  first we could think of the cache as another downstream service, kind of like mirror-node and consensus-node (but a very small one). and second, a distributed cache, adds complexity and points of failure, so I could work on an implementation that only enables cache based on flag on .env properties, and second, in case the cache is down or unreachable, just keeps working as it does right now. we could even add a failover on-memory cache, but I think that would add even more complexity that would be seldomly used and the cost/benefit might not be attractive.

**Comment by AlfredoG87** [comment]
@Ivo-Yankov, yes your suggestion to implement the cache on the client side of the consumer of the mirror-node makes complete sense.

In practice how I like to implement this sort of cache, is to make it transparent to the users consuming the mirror-node, when they in this case call `/contracts/results/{hash}` the client itself will look first on cache and if not available, will perform the call to the mirror-node, hence transparent to the consumers of the method on mirror-node client.

I am not too familiar with the codebase yet and unsure if we have implementations for clients for each downstream service, but I would look for the simpler (code wise) way to implement it, keeping it transparent.
