### ISSUE TITLE
Add support to configure server port number

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#955]
### Problem

Currently the server port number is statically set to `7546` even though an env variable exists to modify it.
The variable is currently only used in test cases and as such operator of the relay are forced to use this value

### Solution

Update server package logic to pick up the custom port number if set. If not set default to `7546`

**Comment by georgi-l95** [comment]
@Nana-EC This was addressed [here](https://github.com/hashgraph/hedera-json-rpc-relay/pull/960/files#diff-8e6dfbbfb522575fe7c568c2de518bf9de351de83c9dbb48eaa865cd54450eb3R24).
