### ISSUE TITLE
Expose BLOCK_GAS_LIMIT

### ISSUE THREAD

**Issue by bmino** [hashgraph/hedera-json-rpc-relay#982]
### Problem

When indexing a graph node against the relayer, eth_call requests cannot specify gas limits and the relayer defaults to the maximum possible quantity as defined by `BLOCK_GAS_LIMIT`. When only using the relayer for graph indexing, this is far too big of a gas quantity especially when the few eth_call requests will be simple queries like HTS.name() HTS.symbol() etc. These requests are not frequent but can occur via indexing depending on graph mappings.

Can we expose `BLOCK_GAS_LIMIT` via an environment variable to avoid building from source? Or perhaps a better solution to handle eth_call requests without a specified gas quantity?

### Solution

- Expose `BLOCK_GAS_LIMIT` via environment variable
- Alternative handling of eth_call requests without a specified gas limit

### Alternatives

I've been modifying `packages/relay/src/lib/constants.ts` property `BLOCK_GAS_LIMIT` to something lower like `50_000` or `100_000` to cover required calls much cheaper and then building from source code

**Comment by Nana-EC** [comment]
Hey @bmino, thanks for the ticket.
Can you elaborate on the negative impact here?

If the value you use or usually encounter is less than the `15_000_000` limit from the network I want to understand the undesired UX here.

For content we limit since it's a consensus node level property and would result in a transaction that won't succeed.

I think making this config is  change is doable once we better understand the use case.

It's a minor change so something that a community member could open a PR for.

**Comment by bmino** [comment]
I tried to explain an overview in the OP. It mostly relates to handling legacy `eth_call` requests that do not specify a gas limit. The relayer will set the maximum gas limit of `BLOCK_GAS_LIMIT` and the call will consume 80% of this as per Hedera's gas refund policy. Typically, a caller would simply specify a proper gas limit, but this is aimed to address use cases where the caller cannot/does not specify.

In my specific use case I know all possible `eth_call` requests that will come through the relayer so setting the `BLOCK_GAS_LIMIT` lower is a palatable solution. Most relayers will not find this acceptable however since they likely handle a wide variety of request types with varying costs.

Another possibility is something like a "DEFAULT_GAS_LIMIT" for requests that do not specify gas limits?

**Comment by daniel-bcw** [comment]
I guess under `constants.ts` we can probably have something like
 BLOCK_GAS_LIMIT: process.env. DEFAULT_GAS_LIMIT ? process.env. DEFAULT_GAS_LIMIT : 15_000_000
(and adding the mapping in the configmap.yaml)

**Comment by bmino** [comment]
I like this solution @Nana-EC and will implement soon as I can spare some time. I did some investigation and found that `BLOCK_GAS_LIMIT` was working effectively for me since the request first had its gas set to `TX_DEFAULT_GAS` (or in some cases I see hardcoded 400000 values ..) and then was truncated to my custom `BLOCK_GAS_LIMIT` which was even lower

**Comment by bmino** [comment]
testing this behavior is difficult when the initialization of the default gas is done on creation of `EthImpl` based on environment variables at that time. changing the environment variable within the tests will not alter the actual state of the `EthImpl` being tested

**Comment by Nana-EC** [comment]
If your test needs a custom EthImpl you can always create one for you section of tests.
Here's an instantiation example https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/tests/lib/eth.spec.ts#L109
Also you can add a separate test file
